# Generated by Django 6.0.4 on 2026-05-27 05:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allotment', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfEntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('bill_of_entry_number', models.CharField(max_length=25)),
                ('bill_of_entry_date', models.DateField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('product_name', models.CharField(default='', max_length=255)),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('is_fetch', models.BooleanField(default=False)),
                ('boe_pdf_copy', models.FileField(blank=True, help_text='Original ICEGATE BOE PDF uploaded during Fetch', null=True, upload_to='boe_copies/')),
                ('failed', models.IntegerField(default=0)),
                ('appraisement', models.CharField(blank=True, max_length=255, null=True)),
                ('ooc_date', models.CharField(blank=True, max_length=255, null=True)),
                ('cha', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('allotment', models.ManyToManyField(blank=True, related_name='bill_of_entry', to='allotment.allotmentmodel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_entry', to='core.companymodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boe_port', to='core.portmodel')),
            ],
            options={
                'verbose_name': 'Bill of Entry',
                'verbose_name_plural': 'Bills of Entry',
                'ordering': ('-bill_of_entry_date',),
            },
        ),
        migrations.CreateModel(
            name='RowDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('row_type', models.CharField(choices=[('AR', 'ARO'), ('AT', 'Allotment')], default='AT', max_length=2)),
                ('transaction_type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='D', max_length=2)),
                ('cif_inr', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cif_fc', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('is_frozen', models.BooleanField(default=False, help_text='Set to True when this row is created/updated from a ledger upload. Frozen rows cannot be edited from the frontend.')),
                ('is_dispute', models.BooleanField(default=False, help_text='Flagged when this BOE row is missing from the latest ledger upload. Shown in red for manual review.')),
                ('bill_of_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='bill_of_entry.billofentrymodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Detail',
                'verbose_name_plural': 'Item Details',
                'ordering': ['transaction_type', 'bill_of_entry__bill_of_entry_date'],
            },
        ),
    ]
