# Generated by Django 6.0.4 on 2026-07-29 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0003_alter_billofentrymodel_unique_together'),
        ('license', '0014_backfill_licenseitemplan_baseline_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rowdetails',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rowdetails',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rowdetails',
            name='hidden_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rowdetails',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Marks this DEBIT row as belonging to a previous licence owner — excluded from every balance/financial calculation but retained and visible in the Customs History audit view.'),
        ),
        migrations.AddField(
            model_name='rowdetails',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rowdetails',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rowdetails',
            index=models.Index(fields=['is_hidden'], name='bill_of_ent_is_hidd_171aa5_idx'),
        ),
    ]
