# Generated by Django 6.0.4 on 2026-07-30 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0004_rowdetails_hidden_at_rowdetails_hidden_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rowdetails',
            name='bill_of_ent_is_hidd_171aa5_idx',
        ),
        migrations.RemoveField(
            model_name='rowdetails',
            name='hidden_at',
        ),
        migrations.RemoveField(
            model_name='rowdetails',
            name='hidden_by',
        ),
        migrations.RemoveField(
            model_name='rowdetails',
            name='hidden_reason',
        ),
        migrations.RemoveField(
            model_name='rowdetails',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='rowdetails',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='rowdetails',
            name='restored_by',
        ),
    ]
