# Generated by Django 5.0.3 on 2026-02-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0005_add_composite_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billofentrymodel',
            name='boe_company_date_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='billofentrymodel',
            name='boe_port_date_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='billofentrymodel',
            name='boe_invoice_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='billofentrymodel',
            name='boe_fetch_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='billofentrymodel',
            name='boe_product_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='billofentrymodel',
            name='boe_company_port_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='rowdetails',
            name='row_sr_transaction_idx',
        ),
        migrations.RemoveIndex(
            model_name='rowdetails',
            name='row_boe_sr_idx',
        ),
        migrations.RemoveIndex(
            model_name='rowdetails',
            name='row_transaction_boe_idx',
        ),
        migrations.RemoveIndex(
            model_name='rowdetails',
            name='row_type_boe_idx',
        ),
        migrations.RemoveIndex(
            model_name='rowdetails',
            name='row_balance_calc_idx',
        ),
    ]
