# Generated by Django 6.0.4 on 2026-08-07 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0005_remove_rowdetails_bill_of_ent_is_hidd_171aa5_idx_and_more'),
        ('core', '0011_split_milk_into_swp_dwp_wpc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofentrymodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_of_entry', to='core.companymodel'),
        ),
        migrations.AlterField(
            model_name='billofentrymodel',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boe_port', to='core.portmodel'),
        ),
    ]
