# Generated by Django 6.0.4 on 2026-08-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0007_rowdetails_planning_target_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowdetails',
            name='planning_mapping_status',
            field=models.CharField(choices=[('MAPPED_EXPLICIT', 'Mapped explicitly'), ('MAPPED_DETERMINISTIC', 'Mapped from a unique target'), ('UNMAPPED_AMBIGUOUS', 'Target is ambiguous'), ('UNMAPPED_NO_TARGET', 'No configured target'), ('INVALID_PERSISTED_TARGET', 'Persisted target is invalid')], db_index=True, default='UNMAPPED_AMBIGUOUS', max_length=32),
        ),
    ]
