# Generated by Django 6.0.4 on 2026-08-18 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0009_remove_rowdetails_planning_mapping_source_and_more'),
        ('core', '0016_merge_numbered_norm_suffixed_item_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofentrymodel',
            name='planning_target_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boe_planning_targets', to='core.itemnamemodel'),
        ),
    ]
