# Generated by Django 6.0.4 on 2026-08-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0009_billofentry_parent_planning_target'),
        ('bill_of_entry', '0010_alter_billofentrymodel_planning_target_item'),
    ]

    operations = [
    ]
