# Generated by Django 6.0.4 on 2026-05-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_scheme_and_notification_to_fk'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='licensedetailsmodel',
            name='license_lic_notific_5b1519_idx',
        ),
        migrations.RemoveIndex(
            model_name='licensedetailsmodel',
            name='license_lic_scheme__3280bf_idx',
        ),
    ]
