# Generated by Django 5.2.7 on 2025-10-30 14:30

import accounts.models
import django.utils.timezone
from django.db import migrations, models

# Generated by Django 5.2.7 on 2025-11-04 04:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
    ]

