# Generated by Django 5.0.3 on 2025-12-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('accounts', 'Accounts')], default='accounts', max_length=20),
        ),
    ]
