# Generated by Django 5.0.3 on 2025-11-18 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0002_alter_billofentrymodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                -- Add columns to bill_of_entry_rowdetails
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='bill_of_entry_rowdetails' AND column_name='created_on') THEN
                    ALTER TABLE bill_of_entry_rowdetails ADD COLUMN created_on timestamp with time zone DEFAULT NOW() NOT NULL;
                END IF;

                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='bill_of_entry_rowdetails' AND column_name='modified_on') THEN
                    ALTER TABLE bill_of_entry_rowdetails ADD COLUMN modified_on timestamp with time zone DEFAULT NOW() NOT NULL;
                END IF;

                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='bill_of_entry_rowdetails' AND column_name='created_by_id') THEN
                    ALTER TABLE bill_of_entry_rowdetails ADD COLUMN created_by_id integer;
                END IF;

                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='bill_of_entry_rowdetails' AND column_name='modified_by_id') THEN
                    ALTER TABLE bill_of_entry_rowdetails ADD COLUMN modified_by_id integer;
                END IF;

                -- Add columns to bill_of_entry_billofentrymodel
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='bill_of_entry_billofentrymodel' AND column_name='created_on') THEN
                    ALTER TABLE bill_of_entry_billofentrymodel ADD COLUMN created_on timestamp with time zone DEFAULT NOW() NOT NULL;
                END IF;

                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='bill_of_entry_billofentrymodel' AND column_name='modified_on') THEN
                    ALTER TABLE bill_of_entry_billofentrymodel ADD COLUMN modified_on timestamp with time zone DEFAULT NOW() NOT NULL;
                END IF;

                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='bill_of_entry_billofentrymodel' AND column_name='created_by_id') THEN
                    ALTER TABLE bill_of_entry_billofentrymodel ADD COLUMN created_by_id integer;
                END IF;

                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='bill_of_entry_billofentrymodel' AND column_name='modified_by_id') THEN
                    ALTER TABLE bill_of_entry_billofentrymodel ADD COLUMN modified_by_id integer;
                END IF;

                -- Add foreign key constraints
                IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name='bill_of_entry_rowdetails_created_by_id_fkey') THEN
                    ALTER TABLE bill_of_entry_rowdetails ADD CONSTRAINT bill_of_entry_rowdetails_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES auth_user(id) ON DELETE SET NULL;
                END IF;

                IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name='bill_of_entry_rowdetails_modified_by_id_fkey') THEN
                    ALTER TABLE bill_of_entry_rowdetails ADD CONSTRAINT bill_of_entry_rowdetails_modified_by_id_fkey FOREIGN KEY (modified_by_id) REFERENCES auth_user(id) ON DELETE SET NULL;
                END IF;

                IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name='bill_of_entry_billofentrymodel_created_by_id_fkey') THEN
                    ALTER TABLE bill_of_entry_billofentrymodel ADD CONSTRAINT bill_of_entry_billofentrymodel_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES auth_user(id) ON DELETE SET NULL;
                END IF;

                IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name='bill_of_entry_billofentrymodel_modified_by_id_fkey') THEN
                    ALTER TABLE bill_of_entry_billofentrymodel ADD CONSTRAINT bill_of_entry_billofentrymodel_modified_by_id_fkey FOREIGN KEY (modified_by_id) REFERENCES auth_user(id) ON DELETE SET NULL;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE bill_of_entry_rowdetails
            DROP COLUMN IF EXISTS created_on,
            DROP COLUMN IF EXISTS modified_on,
            DROP COLUMN IF EXISTS created_by_id,
            DROP COLUMN IF EXISTS modified_by_id;

            ALTER TABLE bill_of_entry_billofentrymodel
            DROP COLUMN IF EXISTS created_on,
            DROP COLUMN IF EXISTS modified_on,
            DROP COLUMN IF EXISTS created_by_id,
            DROP COLUMN IF EXISTS modified_by_id;
            """
        ),
    ]
