# Generated by Django 5.0.3 on 2025-11-20 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0012_add_performance_indexes'),
        ('bill_of_entry', '0003_add_audit_fields_to_rowdetails'),
        ('core', '0015_alter_invoiceentity_address_line_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billofentrymodel',
            index=models.Index(fields=['bill_of_entry_number'], name='bill_of_ent_bill_of_73d627_idx'),
        ),
        migrations.AddIndex(
            model_name='billofentrymodel',
            index=models.Index(fields=['company', 'bill_of_entry_date'], name='bill_of_ent_company_490ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='billofentrymodel',
            index=models.Index(fields=['port', 'bill_of_entry_date'], name='bill_of_ent_port_id_2e6325_idx'),
        ),
        migrations.AddIndex(
            model_name='billofentrymodel',
            index=models.Index(fields=['bill_of_entry_date'], name='bill_of_ent_bill_of_b80252_idx'),
        ),
        migrations.AddIndex(
            model_name='billofentrymodel',
            index=models.Index(fields=['invoice_no', 'invoice_date'], name='bill_of_ent_invoice_182ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='billofentrymodel',
            index=models.Index(fields=['is_fetch'], name='bill_of_ent_is_fetc_01a03d_idx'),
        ),
        migrations.AddIndex(
            model_name='billofentrymodel',
            index=models.Index(fields=['product_name'], name='bill_of_ent_product_8e07f4_idx'),
        ),
    ]
