# Generated by Django 6.0.4 on 2026-05-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0008_alter_rowdetails_cif_fc_cif_inr'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofentrymodel',
            name='boe_pdf_copy',
            field=models.FileField(blank=True, help_text='Original ICEGATE BOE PDF uploaded during Fetch', null=True, upload_to='boe_copies/'),
        ),
    ]
