# Generated by Django 6.0.4 on 2026-05-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0009_add_boe_pdf_copy_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowdetails',
            name='is_dispute',
            field=models.BooleanField(default=False, help_text='Flagged when this BOE row is missing from the latest ledger upload. Shown in red for manual review.'),
        ),
    ]
