export const REPORT_ROLES = [
    "REPORT_VIEWER",
    "LICENSE_MANAGER",
    "LICENSE_VIEWER",
    "TRADE_MANAGER",
    "TRADE_VIEWER",
    "ALLOTMENT_MANAGER",
    "BOE_MANAGER",
    "INCENTIVE_LICENSE_MANAGER",
];
