# Generated by Django 4.2.14 on 2024-08-08 18:54

from django.db import migrations

from django.db import migrations
from django.db.models import Sum


def calculate_debits(apps, schema_editor):
    # Get the model from the versioned app registry.
    LicenseImportItemsModel = apps.get_model('license', 'LicenseImportItemsModel')
    RowDetails = apps.get_model('bill_of_entry', 'RowDetails')

    for license_item in LicenseImportItemsModel.objects.all():
        related_rows = RowDetails.objects.filter(sr_number=license_item)
        license_item.debited_value = related_rows.aggregate(Sum('cif_inr'))['cif_inr__sum'] or 0
        license_item.debited_quantity = related_rows.aggregate(Sum('qty'))['qty__sum'] or 0
        license_item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('license', '0017_remove_licenseimportitemsmodel_blocked_quantity_and_more'),  # replace with the actual name of the last migration
    ]

    operations = [
        migrations.RunPython(calculate_debits),
    ]