# Generated by Django 3.1.6 on 2022-05-25 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iec', models.CharField(max_length=10, unique=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_fetch', models.BooleanField(default=False)),
                ('failed', models.IntegerField(default=0)),
                ('is_self', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HeadSIONNormsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_fetch', models.BooleanField(default=False)),
                ('tpages', models.IntegerField(default=1)),
                ('tcurrent', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HSCodeDutyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=8, unique=True)),
                ('basic_custom_duty', models.FloatField(default=0)),
                ('additional_duty_of_customs', models.FloatField(default=0)),
                ('custom_health_CESS', models.FloatField(default=0)),
                ('social_welfare_surcharge', models.FloatField(default=0)),
                ('additional_CVD', models.FloatField(default=0)),
                ('IGST_levy', models.FloatField(default=0)),
                ('compensation_cess', models.FloatField(default=0)),
                ('total_duty', models.FloatField(default=0)),
                ('sample_on_lakh', models.FloatField(default=0)),
                ('is_fetch', models.BooleanField(default=False)),
                ('is_fetch_xls', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HSCodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=8, unique=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('basic_duty', models.CharField(blank=True, max_length=225, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('policy', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('hs_code',),
            },
        ),
        migrations.CreateModel(
            name='ItemHeadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hs_code', models.CharField(max_length=255)),
                ('unit_rate', models.FloatField(default=0)),
                ('biscuit_priority', models.FloatField(default=0)),
                ('confectionery_priority', models.FloatField(default=0)),
                ('is_restricted', models.BooleanField(default=True)),
                ('is_amend', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.itemheadmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MEISMODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exporter', models.CharField(max_length=255)),
                ('importer', models.CharField(max_length=255)),
                ('cif_inr', models.CharField(max_length=255)),
                ('dfia_date', models.CharField(max_length=255)),
                ('dfia_no', models.CharField(max_length=255)),
                ('file_no', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferLetterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tl', models.FileField(upload_to='tl')),
            ],
        ),
        migrations.CreateModel(
            name='SionNormClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_created=True)),
                ('norm_class', models.CharField(max_length=10)),
                ('url', models.URLField(blank=True, help_text='Please Enter Exim Guru URL', null=True)),
                ('is_fetch', models.BooleanField(default=False)),
                ('modified_on', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sion_created', to=settings.AUTH_USER_MODEL)),
                ('head_norm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sion_head', to='core.headsionnormsmodel')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='norm_class', to='core.itemnamemodel')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sion_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SIONImportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(default=0)),
                ('quantity', models.FloatField(default=0.0)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('hs_code', models.ManyToManyField(blank=True, related_name='import_norms', to='core.HSCodeModel')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sion_import', to='core.itemnamemodel')),
                ('norm_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_norm', to='core.sionnormclassmodel')),
            ],
            options={
                'ordering': ['sr_no'],
            },
        ),
        migrations.CreateModel(
            name='SIONExportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('hs_code', models.ManyToManyField(blank=True, related_name='export_norms', to='core.HSCodeModel')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sion_export', to='core.itemnamemodel')),
                ('norm_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export_norm', to='core.sionnormclassmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.TextField()),
                ('hs_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_descriptions', to='core.hscodedutymodel')),
            ],
        ),
        migrations.CreateModel(
            name='PortModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('code', 'name'),
                'unique_together': {('name', 'code')},
            },
        ),
    ]
