# Generated by Django 2.2.3 on 2019-07-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portmodel',
            old_name='port_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='portmodel',
            old_name='port_name',
            new_name='name',
        ),
    ]
