# Generated by Django 3.1.6 on 2022-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='director_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='director_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
