# Generated by Django 2.2.3 on 2019-07-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
