# Generated by Django 3.1.6 on 2022-09-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220722_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscodemodel',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
