# Generated by Django 2.2.3 on 2020-04-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transferlettermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlettermodel',
            name='tl',
            field=models.FileField(upload_to='tl'),
        ),
    ]
