# Generated by Django 2.2.3 on 2019-07-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190717_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portmodel',
            options={'ordering': ('code', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='portmodel',
            unique_together={('name', 'code')},
        ),
    ]
