# Generated by Django 3.1.6 on 2022-09-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hscodemodel_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPriceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.FloatField(default=0)),
            ],
        ),
    ]
