# Generated by Django 2.2.3 on 2019-07-26 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sionnormclassmodel_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sionnormclassmodel',
            name='company_name',
        ),
        migrations.AddField(
            model_name='sionexportmodel',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sion', to='core.CompanyModel'),
        ),
    ]
