# Generated by Django 2.2.3 on 2020-05-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200426_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemheadmodel',
            name='biscuit_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemheadmodel',
            name='confectionery_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemheadmodel',
            name='unit_rate',
            field=models.FloatField(default=0),
        ),
    ]
