# Generated by Django 2.2.3 on 2020-05-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200508_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemheadmodel',
            name='biscuit_priority',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itemheadmodel',
            name='confectionery_priority',
            field=models.FloatField(default=0),
        ),
    ]
