# Generated by Django 2.2.3 on 2019-07-26 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190726_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sionexportmodel',
            name='norm_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_norm', to='core.SionNormClassModel'),
        ),
    ]
