# Generated by Django 3.1.6 on 2022-09-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_unitpricemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitpricemodel',
            name='label',
            field=models.CharField(default='', max_length=255),
        ),
    ]
