# Generated by Django 3.1.6 on 2023-02-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_unitpricemodel_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='address_line_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='address_line_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
