# Generated by Django 2.2.3 on 2019-07-26 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190726_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sionexportmodel',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='sionexportmodel',
            name='norm_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export_norm', to='core.SionNormClassModel'),
        ),
    ]
