# Generated by Django 3.1.6 on 2021-09-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200508_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEISMODEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exporter', models.CharField(max_length=255)),
                ('importer', models.CharField(max_length=255)),
                ('cif_inr', models.CharField(max_length=255)),
                ('dfia_date', models.CharField(max_length=255)),
                ('dfia_no', models.CharField(max_length=255)),
            ],
        ),
    ]
