# Generated by Django 3.1.6 on 2021-09-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_meismodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='meismodel',
            name='file_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
