# Generated by Django 4.1.7 on 2024-01-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230201_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sionexportmodel',
            name='hs_code',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='export_norms', to='core.hscodemodel'),
        ),
        migrations.AlterField(
            model_name='sionimportmodel',
            name='hs_code',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='import_norms', to='core.hscodemodel'),
        ),
    ]
