# Generated by Django 4.1.7 on 2024-02-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230201_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymodel',
            old_name='is_self',
            new_name='is_ge',
        ),
    ]
