# Generated by Django 2.2.3 on 2019-07-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190726_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sionimportmodel',
            options={'ordering': ['sr_no']},
        ),
        migrations.AlterField(
            model_name='sionimportmodel',
            name='sr_no',
            field=models.IntegerField(default=0),
        ),
    ]
