# Generated by Django 3.1.6 on 2021-11-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_meismodel_file_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymodel',
            options={'ordering': ['name']},
        ),
    ]
