# Generated by Django 2.2.3 on 2019-07-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190728_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='is_fetch',
            field=models.BooleanField(default=False),
        ),
    ]
