# Generated by Django 4.2.14 on 2024-08-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_is_self_companymodel_is_ge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemheadmodel',
            name='biscuit_priority',
        ),
        migrations.RemoveField(
            model_name='itemheadmodel',
            name='confectionery_priority',
        ),
    ]
