# Generated by Django 2.2.3 on 2019-07-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companymodel_is_fetch'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
