# Generated by Django 4.2.15 on 2024-08-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_itemheadmodel_biscuit_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnamemodel',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
