# Generated by Django 2.2.3 on 2019-07-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_companymodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='failed',
            field=models.IntegerField(default=0),
        ),
    ]
