# Generated by Django 4.2.15 on 2024-08-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_itemnamemodel_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemheadmodel',
            name='is_amend',
        ),
        migrations.AddField(
            model_name='itemheadmodel',
            name='dict_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
