# Generated by Django 4.2.15 on 2024-08-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_itemheadmodel_is_amend_itemheadmodel_dict_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemheadmodel',
            name='hs_code',
        ),
        migrations.AlterField(
            model_name='itemheadmodel',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
