# Generated by Django 2.2.3 on 2019-08-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190807_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemheadmodel',
            name='hs_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
