# Generated by Django 4.2.15 on 2024-08-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_itemheadmodel_hs_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portmodel',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
