# Generated by Django 4.2.15 on 2024-08-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_portmodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnamemodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
