# Generated by Django 2.2.3 on 2019-08-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_itemheadmodel_hs_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='is_self',
            field=models.BooleanField(default=True),
        ),
    ]
