# Generated by Django 4.2.15 on 2024-10-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_itemnamemodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemnamemodel',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
