# Generated by Django 2.2.3 on 2019-10-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_companymodel_is_self'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemheadmodel',
            name='is_amend',
            field=models.BooleanField(default=False),
        ),
    ]
