# Generated by Django 2.2.3 on 2019-12-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_itemheadmodel_is_amend'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemheadmodel',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
