# Generated by Django 2.2.3 on 2019-12-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_itemheadmodel_is_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemheadmodel',
            name='is_restricted',
            field=models.BooleanField(default=True),
        ),
    ]
