# Generated by Django 2.2.3 on 2020-03-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191229_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCodeDutyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=8, unique=True)),
                ('basic_custom_duty', models.FloatField(default=0)),
                ('additional_duty_of_customs', models.FloatField(default=0)),
                ('custom_health_CESS', models.FloatField(default=0)),
                ('social_welfare_surcharge', models.FloatField(default=0)),
                ('additional_CVD', models.FloatField(default=0)),
                ('IGST_levy', models.FloatField(default=0)),
                ('compensation_cess', models.FloatField(default=0)),
                ('total_duty', models.FloatField(default=0)),
            ],
        ),
    ]
