# Generated by Django 2.2.3 on 2020-03-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_hscodedutymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscodedutymodel',
            name='sample_on_lakh',
            field=models.FloatField(default=0),
        ),
    ]
