# Generated by Django 2.2.3 on 2020-03-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_hscodedutymodel_sample_on_lakh'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscodedutymodel',
            name='is_fetch',
            field=models.BooleanField(default=False),
        ),
    ]
