# Generated by Django 2.2.3 on 2020-03-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_hscodedutymodel_is_fetch'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscodedutymodel',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
