# Generated by Django 2.2.3 on 2020-03-26 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_hscodedutymodel_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hscodedutymodel',
            name='product_description',
        ),
        migrations.CreateModel(
            name='ProductDescriptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.TextField()),
                ('hs_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_descriptions', to='core.HSCodeModel')),
            ],
        ),
    ]
