# Generated by Django 2.2.3 on 2020-03-26 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200326_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescriptionmodel',
            name='hs_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_descriptions', to='core.HSCodeDutyModel'),
        ),
    ]
