# Generated by Django 2.2.3 on 2020-03-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200326_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscodedutymodel',
            name='is_fetch_xls',
            field=models.BooleanField(default=False),
        ),
    ]
