export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/v1/auth/login/',
    LOGOUT: '/api/v1/auth/logout/',
    REFRESH: '/api/v1/auth/token/refresh/',
    ME: '/api/v1/auth/me/',
    CHANGE_PASSWORD: '/api/v1/auth/change-password/',
    UPDATE_PROFILE: '/api/v1/auth/me/',
  },
  LICENSES: {
    LIST: '/api/v1/licenses/',
    DETAIL: (id: number | string) => `/api/v1/licenses/${id}/`,
    ITEMS: (id: number | string) => `/api/v1/licenses/${id}/items/`,
    BALANCE: (id: number | string) => `/api/v1/licenses/${id}/balance/`,
    ITEM_USAGE: (id: number | string) => `/api/v1/licenses/${id}/item-usage/`,
    BALANCE_PDF: (id: number | string) => `/api/v1/licenses/${id}/balance-pdf/`,
    BALANCE_EXCEL: '/api/v1/licenses/balance-excel/',
    GENERATE_PDF: (id: number | string) => `/api/v1/licenses/${id}/generate-pdf/`,
    MERGED_DOCUMENTS: (id: number | string) => `/api/v1/licenses/${id}/merged-documents/`,
    SEARCH: '/api/v1/licenses/search/',
    EXPORT_ITEMS: (id: number | string) => `/api/v1/licenses/${id}/export-items/`,
    DOCUMENTS: (id: number | string) => `/api/v1/licenses/${id}/documents/`,
    HISTORY: (id: number | string) => `/api/v1/licenses/${id}/history/`,
    ITEM_PLANS: (id: number | string) => `/api/v1/licenses/${id}/item-plans/`,
    ITEM_PLANS_BULK_UPSERT: (id: number | string) => `/api/v1/licenses/${id}/item-plans/bulk-upsert/`,
    NORM_PREFILL: (id: number | string) => `/api/v1/license-item-plans/${id}/norm-prefill/`,
    ACTIVE_DFIA_REPORT: '/api/v1/licenses/active-dfia-report/',
    EXPIRING_LICENSES_REPORT: '/api/v1/licenses/expiring-licenses/',
    ACTIVE_LICENSES_REPORT: '/api/v1/licenses/active-licenses/',
    BULK_BALANCE_EXCEL: '/api/v1/licenses/bulk-balance-excel/',
  },
  ALLOTMENTS: {
    LIST: '/api/v1/allotments/',
    DETAIL: (id: number | string) => `/api/v1/allotments/${id}/`,
    GENERATE_PDF: (id: number) => `/api/v1/allotments/${id}/generate-pdf/`,
    AVAILABLE_LICENSES: (id: number) => `/api/v1/allotment-actions/${id}/available-licenses/`,
    ALLOCATE_ITEMS: (id: number) => `/api/v1/allotment-actions/${id}/allocate-items/`,
    DELETE_ITEM: (id: number, itemId: number) => `/api/v1/allotment-actions/${id}/delete-item/${itemId}/`,
    GENERATE_TRANSFER_LETTER: (id: number) => `/api/v1/allotment-actions/${id}/generate-transfer-letter/`,
    COPY: (id: number) => `/api/v1/allotments/${id}/copy/`,
  },
  TRADES: {
    LIST: '/api/v1/trades/',
    DETAIL: (id: number | string) => `/api/v1/trades/${id}/`,
    SUMMARY: (id: number | string) => `/api/v1/trades/${id}/summary/`,
    PREFILL_INVOICE: '/api/v1/trades/prefill-invoice-number/',
    PURCHASE_INVOICE_PDF: (id: number | string) => `/api/v1/trades/${id}/generate-purchase-invoice/`,
    BILL_OF_SUPPLY_PDF: (id: number | string) => `/api/v1/trades/${id}/generate-bill-of-supply/`,
    LINES: '/api/v1/trades/lines/',
    PAYMENTS: '/api/v1/trades/payments/',
    LINK_TRADE: (id: number | string) => `/api/v1/trades/${id}/link-trade/`,
  },
  BILLS_OF_ENTRY: {
    LIST: '/api/v1/bills-of-entry/',
    DETAIL: (id: number | string) => `/api/v1/bills-of-entry/${id}/`,
    UPDATE_INVOICE: (id: number | string) => `/api/v1/bills-of-entry/${id}/update-invoice/`,
  },
  INCENTIVE_LICENSES: {
    LIST: '/api/v1/incentive-licenses/',
    DETAIL: (id: number | string) => `/api/v1/incentive-licenses/${id}/`,
  },
  USERS: {
    LIST: '/api/v1/auth/users/',
    DETAIL: (id: number | string) => `/api/v1/auth/users/${id}/`,
    CREATE: '/api/v1/auth/users/',
    AVAILABLE_ROLES: '/api/v1/auth/users/available-roles/',
    RESET_PASSWORD: (id: number | string) => `/api/v1/auth/users/${id}/reset-password/`,
  },
  REPORTS: {
    LIST: '/api/v1/reports/',
    BALANCE: '/api/v1/reports/balance/generate/',
    ITEMS: '/api/v1/reports/items/generate/',
    PIVOT: '/api/v1/reports/pivot/generate/',
    LEDGER: '/api/v1/reports/ledger/generate/',
    TASK_STATUS: (taskId: string) => `/api/v1/reports/task/${taskId}/status/`,
  },
  LEDGER: {
    UPLOAD: '/api/v1/licenses/upload-ledger/',
    TASK_STATUS: (taskId: string) => `/api/v1/licenses/ledger-task-status/${taskId}/`,
    LIST: '/api/v1/ledger/',
  },
  TRANSFER_LETTERS: {
    LIST: '/api/v1/transfer-letters/',
    GENERATE: '/api/v1/transfer-letters/generate/',
  },
  BILL_OF_ENTRY: {
    LIST: '/api/v1/bill-of-entries/',
    DETAIL: (id: number) => `/api/v1/bill-of-entries/${id}/`,
    ROWS: (id: number) => `/api/v1/bill-of-entries/${id}/rows/`,
    ROW: (id: number, rowId: number) => `/api/v1/bill-of-entries/${id}/rows/${rowId}/`,
    RESOLVE_DISPUTE: (id: number, rowId: number) => `/api/v1/bill-of-entries/${id}/rows/${rowId}/resolve-dispute/`,
    UPLOAD_LEDGER: '/api/v1/bill-of-entries/upload-ledger/',
    PARSE_PDF: '/api/v1/bill-of-entries/parse-pdf/',
    FETCH_ALLOTMENT_DETAILS: '/api/v1/bill-of-entries/fetch-allotment-details/',
    GENERATE_TRANSFER_LETTER: (id: number) => `/api/v1/bill-of-entries/${id}/generate-transfer-letter/`,
    MERGE: (id: number) => `/api/v1/bill-of-entries/${id}/merge/`,
    UPDATE_INVOICE_NO: (id: number) => `/api/v1/bill-of-entries/${id}/update-invoice-no/`,
  },
  TASKS: {
    LIST: '/api/v1/tasks/',
    DETAIL: (id: number | string) => `/api/v1/tasks/${id}/`,
    COMPLETE: (id: number | string) => `/api/v1/tasks/${id}/complete/`,
    REJECT: (id: number | string) => `/api/v1/tasks/${id}/reject/`,
    REOPEN: (id: number | string) => `/api/v1/tasks/${id}/reopen/`,
    REMARKS: (id: number | string) => `/api/v1/tasks/${id}/remarks/`,
    ASSIGNABLE_USERS: '/api/v1/tasks/assignable-users/',
  },
  MASTERS: {
    ACTIVITY_LOGS: '/api/v1/masters/activity-logs/',
    COMPANIES: '/api/v1/masters/companies/',
    COMPANY: (id: number) => `/api/v1/masters/companies/${id}/`,
    PORTS: '/api/v1/masters/ports/',
    PORT: (id: number) => `/api/v1/masters/ports/${id}/`,
    HS_CODES: '/api/v1/masters/hs-codes/',
    HS_CODE: (id: number) => `/api/v1/masters/hs-codes/${id}/`,
    ITEM_GROUPS: '/api/v1/masters/item-groups/',
    ITEM_GROUP: (id: number) => `/api/v1/masters/item-groups/${id}/`,
    ITEM_NAMES: '/api/v1/masters/item-names/',
    ITEM_NAME: (id: number) => `/api/v1/masters/item-names/${id}/`,
    SION_NORM_CLASSES: '/api/v1/masters/sion-norm-classes/',
    SION_NORM_CLASS: (id: number) => `/api/v1/masters/sion-norm-classes/${id}/`,
    EXCHANGE_RATES: '/api/v1/masters/exchange-rates/',
    EXCHANGE_RATE: (id: number) => `/api/v1/masters/exchange-rates/${id}/`,
    SCHEME_CODES: '/api/v1/masters/scheme-codes/',
    NOTIFICATION_NUMBERS: '/api/v1/masters/notification-numbers/',
    PURCHASE_STATUSES: '/api/v1/masters/purchase-statuses/',
  },
  DASHBOARD: {
    STATS: '/api/v1/dashboard/stats/',
    UTILISATION_CHART: '/api/v1/dashboard/charts/utilisation/',
    ACTIVITY_CHART: '/api/v1/dashboard/charts/activity/',
    EXPIRING_LICENSES: '/api/v1/dashboard/expiring-licenses/',
  },
  LICENSE_LEDGER: {
    LIST: '/api/v1/license-ledger/',
    DETAIL: (id: number | string) => `/api/v1/license-ledger/${id}/`,
    LEDGER_DETAIL: (id: number | string) => `/api/v1/license-ledger/${id}/ledger_detail/`,
    SUMMARY: '/api/v1/license-ledger/summary/',
    COMPANY_WISE: '/api/v1/license-ledger/company-wise/',
    LICENSE_WISE: '/api/v1/license-ledger/license-wise/',
    COMPANY_LEDGER: '/api/v1/license-ledger/company-ledger/',
    EXPORT_ALL: '/api/v1/license-ledger/export/all/',
  },
  NOTIFICATIONS: {
    BALANCE_LIST: '/api/v1/notifications/balance/',
    BALANCE_DETAIL: (id: number) => `/api/v1/notifications/balance/${id}/`,
    BALANCE_ACKNOWLEDGE: (id: number) => `/api/v1/notifications/balance/${id}/acknowledge/`,
    BALANCE_RESOLVE: (id: number) => `/api/v1/notifications/balance/${id}/resolve/`,
  },
} as const
