export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/v1/auth/login/',
    LOGOUT: '/api/v1/auth/logout/',
    REFRESH: '/api/v1/auth/token/refresh/',
    ME: '/api/v1/auth/me/',
    CHANGE_PASSWORD: '/api/v1/auth/change-password/',
    UPDATE_PROFILE: '/api/v1/auth/me/',
  },
  LICENSES: {
    LIST: '/api/v1/licenses/',
    DETAIL: (id: number | string) => `/api/v1/licenses/${id}/`,
    ITEMS: (id: number | string) => `/api/v1/licenses/${id}/items/`,
    BALANCE: (id: number | string) => `/api/v1/licenses/${id}/balance/`,
    ITEM_USAGE: (id: number | string) => `/api/v1/licenses/${id}/item-usage/`,
    BALANCE_PDF: (id: number | string) => `/api/v1/licenses/${id}/balance-pdf/`,
    BALANCE_EXCEL: '/api/v1/licenses/balance-excel/',
    GENERATE_PDF: (id: number | string) => `/api/v1/licenses/${id}/generate-pdf/`,
    MERGED_DOCUMENTS: (id: number | string) => `/api/v1/licenses/${id}/merged-documents/`,
    SEARCH: '/api/v1/licenses/search/',
  },
  ALLOTMENTS: {
    LIST: '/api/v1/allotments/',
    DETAIL: (id: number | string) => `/api/v1/allotments/${id}/`,
    GENERATE_PDF: (id: number) => `/api/v1/allotments/${id}/generate-pdf/`,
  },
  TRADES: {
    LIST: '/api/v1/trades/',
    DETAIL: (id: number | string) => `/api/v1/trades/${id}/`,
    SUMMARY: (id: number | string) => `/api/v1/trades/${id}/summary/`,
    PREFILL_INVOICE: '/api/v1/trades/prefill-invoice-number/',
    PURCHASE_INVOICE_PDF: (id: number | string) => `/api/v1/trades/${id}/generate-purchase-invoice/`,
    BILL_OF_SUPPLY_PDF: (id: number | string) => `/api/v1/trades/${id}/generate-bill-of-supply/`,
    LINES: '/api/v1/trades/lines/',
    PAYMENTS: '/api/v1/trades/payments/',
    LINK_TRADE: (id: number | string) => `/api/v1/trades/${id}/link-trade/`,
  },
  BILLS_OF_ENTRY: {
    LIST: '/api/v1/bills-of-entry/',
    DETAIL: (id: number | string) => `/api/v1/bills-of-entry/${id}/`,
    UPDATE_INVOICE: (id: number | string) => `/api/v1/bills-of-entry/${id}/update-invoice/`,
  },
  INCENTIVE_LICENSES: {
    LIST: '/api/v1/incentive-licenses/',
    DETAIL: (id: number | string) => `/api/v1/incentive-licenses/${id}/`,
  },
  USERS: {
    LIST: '/api/v1/users/',
    DETAIL: (id: number | string) => `/api/v1/users/${id}/`,
  },
  REPORTS: {
    LIST: '/api/v1/reports/',
    BALANCE: '/api/v1/reports/balance/generate/',
    ITEMS: '/api/v1/reports/items/generate/',
    PIVOT: '/api/v1/reports/pivot/generate/',
    LEDGER: '/api/v1/reports/ledger/generate/',
    TASK_STATUS: (taskId: string) => `/api/v1/reports/task/${taskId}/status/`,
  },
  LEDGER: {
    UPLOAD: '/api/v1/ledger/upload/',
    LIST: '/api/v1/ledger/',
  },
  TRANSFER_LETTERS: {
    LIST: '/api/v1/transfer-letters/',
    GENERATE: '/api/v1/transfer-letters/generate/',
  },
  BILL_OF_ENTRY: {
    LIST: '/api/v1/bill-of-entries/',
    DETAIL: (id: number) => `/api/v1/bill-of-entries/${id}/`,
    ROWS: (id: number) => `/api/v1/bill-of-entries/${id}/rows/`,
    ROW: (id: number, rowId: number) => `/api/v1/bill-of-entries/${id}/rows/${rowId}/`,
    RESOLVE_DISPUTE: (id: number, rowId: number) => `/api/v1/bill-of-entries/${id}/rows/${rowId}/resolve-dispute/`,
    UPLOAD_LEDGER: '/api/v1/bill-of-entries/upload-ledger/',
  },
  TASKS: {
    LIST: '/api/v1/tasks/',
    DETAIL: (id: number | string) => `/api/v1/tasks/${id}/`,
    COMPLETE: (id: number | string) => `/api/v1/tasks/${id}/complete/`,
    REJECT: (id: number | string) => `/api/v1/tasks/${id}/reject/`,
    REOPEN: (id: number | string) => `/api/v1/tasks/${id}/reopen/`,
    REMARKS: (id: number | string) => `/api/v1/tasks/${id}/remarks/`,
    ASSIGNABLE_USERS: '/api/v1/tasks/assignable-users/',
  },
  MASTERS: {
    COMPANIES: '/api/v1/masters/companies/',
    COMPANY: (id: number) => `/api/v1/masters/companies/${id}/`,
    PORTS: '/api/v1/masters/ports/',
    PORT: (id: number) => `/api/v1/masters/ports/${id}/`,
    HS_CODES: '/api/v1/masters/hs-codes/',
    HS_CODE: (id: number) => `/api/v1/masters/hs-codes/${id}/`,
    ITEM_GROUPS: '/api/v1/masters/item-groups/',
    ITEM_GROUP: (id: number) => `/api/v1/masters/item-groups/${id}/`,
    ITEM_NAMES: '/api/v1/masters/item-names/',
    ITEM_NAME: (id: number) => `/api/v1/masters/item-names/${id}/`,
    SION_NORM_CLASSES: '/api/v1/masters/sion-norm-classes/',
    SION_NORM_CLASS: (id: number) => `/api/v1/masters/sion-norm-classes/${id}/`,
    EXCHANGE_RATES: '/api/v1/masters/exchange-rates/',
    EXCHANGE_RATE: (id: number) => `/api/v1/masters/exchange-rates/${id}/`,
  },
  DASHBOARD: {
    STATS: '/api/v1/dashboard/stats/',
    UTILISATION_CHART: '/api/v1/dashboard/charts/utilisation/',
    ACTIVITY_CHART: '/api/v1/dashboard/charts/activity/',
    EXPIRING_LICENSES: '/api/v1/dashboard/expiring-licenses/',
  },
} as const
