# Generated by Django 6.0.4 on 2026-07-15 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('license', '__first__') removed — license models are managed=False
        # (tables owned by legacy DB, no migrations directory). The FK to
        # license.licensedetailsmodel is still valid at the DB level; Django
        # does not need to sequence this migration against an unmanaged app.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseBalanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='active', max_length=20)),
                ('balance_cif', models.DecimalField(decimal_places=2, max_digits=15)),
                ('last_boe_reference', models.CharField(blank=True, default='', max_length=255)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_remarks', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_balance_notifications', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_notifications', to='license.licensedetailsmodel')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_balance_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_licensebalancenotification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['license', 'status'], name='notificatio_license_dc5d08_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_315036_idx')],
            },
        ),
    ]
