# Generated by Django 5.2.7 on 2025-11-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_invoiceentity_gst_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MEISMODEL',
        ),
    ]
