# Generated by Django 5.2.7 on 2025-11-15 01:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_hscodedutymodel_igst_levy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceentity',
            name='gst_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number.', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='ifsc_code',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code.', regex='^[A-Z]{4}0[A-Z0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='pan_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')]),
        ),
        migrations.AlterField(
            model_name='itemnamemodel',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
    ]
