# Generated by Django 5.0.3 on 2025-11-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_sr_no_to_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescriptionmodel',
            name='hs_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_descriptions', to='core.hscodemodel'),
        ),
    ]
