# Generated by Django 5.0.3 on 2025-11-17 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_hscodedutymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sionimportmodel',
            name='hs_code',
        ),
        migrations.AddField(
            model_name='sionimportmodel',
            name='hsn_code',
            field=models.ForeignKey(blank=True, db_column='hsn_code_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sion_imports', to='core.hscodemodel'),
        ),
    ]
