# Generated by Django 5.0.3 on 2025-11-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_restriction_fields_to_item_head'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemnamemodel',
            options={'ordering': ['head__name', 'name']},
        ),
    ]
