# Generated by Django 6.0.4 on 2026-10-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_durable_sync_event_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncconflictlog',
            name='natural_key',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='syncevent',
            name='natural_key',
            field=models.CharField(db_index=True, max_length=2000),
        ),
    ]
