# Generated by Django 5.0.3 on 2025-12-02 07:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_sion_notes_conditions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of the exchange rate', unique=True)),
                ('usd', models.DecimalField(decimal_places=4, help_text='USD to INR exchange rate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('euro', models.DecimalField(decimal_places=4, help_text='Euro to INR exchange rate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pound_sterling', models.DecimalField(decimal_places=4, help_text='Pound Sterling to INR exchange rate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('chinese_yuan', models.DecimalField(decimal_places=4, help_text='Chinese Yuan to INR exchange rate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='core_exchan_date_684554_idx')],
            },
        ),
    ]
