# Generated by Django 5.0.3 on 2026-02-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_create_materialized_views'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companymodel',
            name='company_iec_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='companymodel',
            name='company_pan_iec_idx',
        ),
        migrations.RemoveIndex(
            model_name='companymodel',
            name='company_gst_iec_idx',
        ),
        migrations.RemoveIndex(
            model_name='hscodemodel',
            name='hscode_code_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='hscodemodel',
            name='hscode_unit_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='itemnamemodel',
            name='item_active_group_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='itemnamemodel',
            name='item_sion_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='itemnamemodel',
            name='item_restriction_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='itemnamemodel',
            name='item_order_group_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchasestatus',
            name='status_active_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='sionnormclassmodel',
            name='sion_active_head_idx',
        ),
        migrations.RemoveIndex(
            model_name='sionnormclassmodel',
            name='sion_class_active_idx',
        ),
    ]
