# Generated by Django 3.1.6 on 2022-05-25 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingBillDetailsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField(blank=True, null=True)),
                ('sr_no', models.IntegerField(blank=True, null=True)),
                ('shipping_port', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_bill', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_date', models.CharField(blank=True, max_length=255, null=True)),
                ('cha_number', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('fob_inr', models.CharField(blank=True, max_length=255, null=True)),
                ('drawback', models.CharField(blank=True, max_length=255, null=True)),
                ('str', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.CharField(blank=True, max_length=255, null=True)),
                ('current_status', models.CharField(blank=True, max_length=255, null=True)),
                ('DBK_scroll_no', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDetailsOther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField(blank=True, null=True)),
                ('sr_no', models.IntegerField(blank=True, null=True)),
                ('shipping_port', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_bill', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_date', models.CharField(blank=True, max_length=255, null=True)),
                ('iec', models.CharField(blank=True, max_length=255, null=True)),
                ('cha_number', models.CharField(blank=True, max_length=255, null=True)),
                ('job_no', models.CharField(blank=True, max_length=255, null=True)),
                ('job_date', models.CharField(blank=True, max_length=255, null=True)),
                ('total_package', models.CharField(blank=True, max_length=255, null=True)),
                ('port_of_discharge', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('fob', models.CharField(blank=True, max_length=255, null=True)),
                ('total_cess', models.CharField(blank=True, max_length=255, null=True)),
                ('drawback', models.CharField(blank=True, max_length=255, null=True)),
                ('str', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.CharField(blank=True, max_length=255, null=True)),
                ('leo_date', models.CharField(blank=True, max_length=255, null=True)),
                ('scroll_date', models.CharField(blank=True, max_length=255, null=True)),
                ('dbk_scroll_no', models.CharField(blank=True, max_length=255, null=True)),
                ('failed', models.IntegerField(default=0)),
                ('file_number', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_file_number', models.CharField(blank=True, max_length=255, null=True)),
                ('time_of_upload', models.CharField(blank=True, max_length=255, null=True)),
                ('fetch_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iec_code', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_time', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files_shipping_bill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
