// RBAC role codes — sourced from legacy/backend/apps/accounts/permissions.py
// Superusers bypass all role checks (checked server-side and client-side).

export const ROLES = {
  LICENSE_MANAGER: 'LICENSE_MANAGER',
  LICENSE_VIEWER: 'LICENSE_VIEWER',
  TRADE_MANAGER: 'TRADE_MANAGER',
  TRADE_VIEWER: 'TRADE_VIEWER',
  ALLOTMENT_MANAGER: 'ALLOTMENT_MANAGER',
  ALLOTMENT_VIEWER: 'ALLOTMENT_VIEWER',
  BOE_MANAGER: 'BOE_MANAGER',
  BOE_VIEWER: 'BOE_VIEWER',
  INCENTIVE_LICENSE_MANAGER: 'INCENTIVE_LICENSE_MANAGER',
  INCENTIVE_LICENSE_VIEWER: 'INCENTIVE_LICENSE_VIEWER',
  USER_MANAGER: 'USER_MANAGER',
  REPORT_VIEWER: 'REPORT_VIEWER',
  ACCOUNT_ACCESS: 'ACCOUNT_ACCESS',
  TL_GENERATE: 'TL_GENERATE',
  LEDGER_MANAGER: 'LEDGER_MANAGER',
} as const

export type Role = (typeof ROLES)[keyof typeof ROLES]

// Convenience groupings for common permission checks
export const ROLE_GROUPS = {
  LICENSE_ANY: [ROLES.LICENSE_MANAGER, ROLES.LICENSE_VIEWER] as Role[],
  TRADE_ANY: [ROLES.TRADE_MANAGER, ROLES.TRADE_VIEWER] as Role[],
  ALLOTMENT_ANY: [ROLES.ALLOTMENT_MANAGER, ROLES.ALLOTMENT_VIEWER] as Role[],
  BOE_ANY: [ROLES.BOE_MANAGER, ROLES.BOE_VIEWER] as Role[],
  INCENTIVE_ANY: [ROLES.INCENTIVE_LICENSE_MANAGER, ROLES.INCENTIVE_LICENSE_VIEWER] as Role[],
  CAN_VIEW_REPORTS: [
    ROLES.REPORT_VIEWER,
    ROLES.LICENSE_MANAGER,
    ROLES.TRADE_MANAGER,
    ROLES.ALLOTMENT_MANAGER,
    ROLES.BOE_MANAGER,
    ROLES.INCENTIVE_LICENSE_MANAGER,
  ] as Role[],
  CAN_GENERATE_TL: [
    ROLES.TL_GENERATE,
    ROLES.BOE_MANAGER,
    ROLES.BOE_VIEWER,
    ROLES.ALLOTMENT_MANAGER,
    ROLES.ALLOTMENT_VIEWER,
    ROLES.TRADE_MANAGER,
    ROLES.TRADE_VIEWER,
    ROLES.LICENSE_MANAGER,
  ] as Role[],
} as const
