# Generated by Django 2.2.3 on 2019-07-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('license', '0001_initial'),
        ('core', '0001_initial'),
        ('allotment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_of_entry_number', models.CharField(max_length=25, unique=True)),
                ('bill_of_entry_date', models.DateField(blank=True, null=True)),
                ('exchange_rate', models.FloatField(default=0)),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('allotment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_entry', to='allotment.AllotmentModel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_entry', to='core.CompanyModel')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boe_port', to='core.PortModel')),
            ],
        ),
        migrations.CreateModel(
            name='RowDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.CharField(choices=[('AR', 'ARO'), ('AT', 'Allotment')], default='AT', max_length=2)),
                ('transaction_type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='C', max_length=2)),
                ('cif_inr', models.FloatField(default=0.0)),
                ('cif_fc', models.FloatField(default=0.0)),
                ('qty', models.FloatField(default=0.0)),
                ('bill_of_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='bill_of_entry.BillOfEntryModel')),
                ('sr_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='license.LicenseImportItemsModel')),
            ],
            options={
                'ordering': ['sr_number__sr_number', 'sr_number__type'],
            },
        ),
    ]
