# Generated by Django 2.2.3 on 2020-04-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('license', '0001_initial'),
        ('core', '0001_initial'),
        ('allotment', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfEntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_of_entry_number', models.CharField(max_length=25, unique=True)),
                ('bill_of_entry_date', models.DateField(blank=True, null=True)),
                ('exchange_rate', models.FloatField(default=0)),
                ('product_name', models.CharField(default='', max_length=255)),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('is_fetch', models.BooleanField(default=False)),
                ('failed', models.IntegerField(default=0)),
                ('cha', models.CharField(blank=True, max_length=255, null=True)),
                ('allotment', models.ManyToManyField(blank=True, related_name='bill_of_entry', to='allotment.AllotmentModel')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_entry', to='core.CompanyModel')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boe_port', to='core.PortModel')),
            ],
            options={
                'ordering': ('-bill_of_entry_date',),
            },
        ),
        migrations.CreateModel(
            name='RowDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_type', models.CharField(choices=[('AR', 'ARO'), ('AT', 'Allotment')], default='AT', max_length=2)),
                ('transaction_type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='D', max_length=2)),
                ('cif_inr', models.FloatField(default=0.0)),
                ('cif_fc', models.FloatField(default=0.0)),
                ('qty', models.FloatField(default=0.0)),
                ('bill_of_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='bill_of_entry.BillOfEntryModel')),
                ('sr_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='license.LicenseImportItemsModel')),
            ],
            options={
                'ordering': ['transaction_type', 'bill_of_entry__bill_of_entry_date'],
            },
        ),
    ]
