# Generated by Django 3.1.6 on 2022-06-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofentrymodel',
            name='assessable_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='billofentrymodel',
            name='duty_paid',
            field=models.FloatField(default=0),
        ),
    ]
