# Generated by Django 4.1.7 on 2023-08-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230201_0928'),
        ('bill_of_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofentrymodel',
            name='bill_of_entry_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='billofentrymodel',
            unique_together={('company', 'bill_of_entry_number', 'bill_of_entry_date')},
        ),
    ]
