# Generated by Django 2.2.3 on 2020-06-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofentrymodel',
            name='appraisement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
