# Generated by Django 2.2.3 on 2019-07-21 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowdetails',
            name='bill_of_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='bill_of_entry.BillOfEntryModel'),
        ),
    ]
