# Generated by Django 2.2.3 on 2020-07-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0002_billofentrymodel_appraisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofentrymodel',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
