# Generated by Django 4.2.21 on 2025-07-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_itemnamemodel_unit_price'),
        ('bill_of_entry', '0002_alter_billofentrymodel_bill_of_entry_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billofentrymodel',
            unique_together={('bill_of_entry_number', 'bill_of_entry_date', 'port')},
        ),
    ]
