# Generated by Django 2.2.3 on 2019-07-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0002_auto_20190721_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofentrymodel',
            name='product_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
