# Generated by Django 4.1.7 on 2024-01-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0001_initial'),
        ('bill_of_entry', '0002_alter_billofentrymodel_bill_of_entry_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofentrymodel',
            name='allotment',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='bill_of_entry', to='allotment.allotmentmodel'),
        ),
    ]
