# Generated by Django 2.2.3 on 2019-07-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0003_billofentrymodel_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofentrymodel',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
