# Generated by Django 4.2.21 on 2025-07-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0031_alter_licensedetailsmodel_purchase_status'),
        ('bill_of_entry', '0003_alter_billofentrymodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rowdetails',
            unique_together={('bill_of_entry', 'sr_number', 'transaction_type')},
        ),
    ]
