# Generated by Django 3.1.6 on 2022-01-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0003_billofentrymodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofentrymodel',
            name='ooc_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
