# Generated by Django 2.2.3 on 2019-07-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0004_billofentrymodel_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofentrymodel',
            name='is_fetch',
            field=models.BooleanField(default=False),
        ),
    ]
