# Generated by Django 2.2.3 on 2019-07-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0005_billofentrymodel_is_fetch'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofentrymodel',
            name='cha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billofentrymodel',
            name='failed',
            field=models.IntegerField(default=0),
        ),
    ]
