# Generated by Django 2.2.3 on 2019-08-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0006_auto_20190728_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofentrymodel',
            options={'ordering': ('-bill_of_entry_date',)},
        ),
    ]
