# Generated by Django 2.2.3 on 2019-08-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0007_auto_20190824_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowdetails',
            name='transaction_type',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], default='D', max_length=2),
        ),
    ]
