# Generated by Django 2.2.3 on 2020-01-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0008_auto_20190824_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rowdetails',
            options={'ordering': ['transaction_type', 'bill_of_entry__bill_of_entry_date']},
        ),
    ]
