# Generated by Django 2.2.3 on 2020-04-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0004_auto_20200220_0848'),
        ('bill_of_entry', '0009_auto_20200122_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofentrymodel',
            name='allotment',
        ),
        migrations.AddField(
            model_name='billofentrymodel',
            name='allotment',
            field=models.ManyToManyField(blank=True, null=True, related_name='bill_of_entry', to='allotment.AllotmentModel'),
        ),
    ]
