# Generated by Django 2.2.3 on 2020-04-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0010_auto_20200409_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofentrymodel',
            name='allotment',
            field=models.ManyToManyField(blank=True, related_name='bill_of_entry', to='allotment.AllotmentModel'),
        ),
    ]
