# Generated by Django 5.2.7 on 2025-11-09 05:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill_of_entry', '0002_alter_billofentrymodel_options_and_more'),
        ('core', '0004_delete_meismodel'),
        ('license', '0002_invoice_invoiceitem_licensepurchase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale')], db_index=True, max_length=10)),
                ('from_pan', models.CharField(blank=True, max_length=32, null=True)),
                ('from_gst', models.CharField(blank=True, max_length=32, null=True)),
                ('from_addr_line_1', models.TextField(blank=True, null=True)),
                ('from_addr_line_2', models.TextField(blank=True, null=True)),
                ('to_pan', models.CharField(blank=True, max_length=32, null=True)),
                ('to_gst', models.CharField(blank=True, max_length=32, null=True)),
                ('to_addr_line_1', models.TextField(blank=True, null=True)),
                ('to_addr_line_2', models.TextField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('roundoff', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('purchase_invoice_copy', models.FileField(blank=True, null=True, upload_to='trade/purchase_invoices/')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('boe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_trades', to='bill_of_entry.billofentrymodel')),
                ('from_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_from_company', to='core.companymodel')),
                ('to_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_to_company', to='core.companymodel')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LicenseTradeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('mode', models.CharField(choices=[('QTY', 'Quantity (Kg × Rate)'), ('CIF_INR', 'CIF (INR × %)'), ('FOB_INR', 'FOB (INR × %)')], db_index=True, default='QTY', max_length=10)),
                ('qty_kg', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('rate_inr_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('cif_fc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('exc_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('cif_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('fob_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('pct', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=9)),
                ('amount_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('sr_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_lines', to='license.licenseimportitemsmodel')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='trade.licensetrade')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LicenseTradePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trade.licensetrade')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='licensetrade',
            constraint=models.CheckConstraint(condition=models.Q(('from_company__isnull', True), ('to_company__isnull', True), models.Q(('from_company', models.F('to_company')), _negated=True), _connector='OR'), name='chk_from_to_companies_different'),
        ),
        migrations.AddConstraint(
            model_name='licensetrade',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'PURCHASE'), models.Q(('invoice_number', ''), _negated=True)), fields=('from_company', 'invoice_number'), name='uniq_purchase_supplier_invoice'),
        ),
        migrations.AddConstraint(
            model_name='licensetrade',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'SALE'), models.Q(('invoice_number', ''), _negated=True)), fields=('to_company', 'invoice_number'), name='uniq_sale_buyer_invoice_nonblank'),
        ),
    ]
