# Generated by Django 3.1.6 on 2022-05-25 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('usd_import', models.FloatField(default=0)),
                ('gbp_import', models.FloatField(default=0)),
                ('euro_import', models.FloatField(default=0)),
                ('usd_export', models.FloatField(default=0)),
                ('gbp_export', models.FloatField(default=0)),
                ('euro_export', models.FloatField(default=0)),
                ('notification_no', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iec', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_time', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_port', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_bill', models.CharField(max_length=255)),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('cha_number', models.CharField(blank=True, max_length=255, null=True)),
                ('job_no', models.CharField(blank=True, max_length=255, null=True)),
                ('job_date', models.CharField(blank=True, max_length=255, null=True)),
                ('total_package', models.CharField(blank=True, max_length=255, null=True)),
                ('port_of_discharge', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('fob', models.CharField(blank=True, max_length=255, null=True)),
                ('total_cess', models.CharField(blank=True, max_length=255, null=True)),
                ('drawback', models.CharField(blank=True, max_length=255, null=True)),
                ('str', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.CharField(blank=True, max_length=255, null=True)),
                ('leo_date', models.CharField(blank=True, max_length=255, null=True)),
                ('scroll_date', models.CharField(blank=True, max_length=255, null=True)),
                ('dbk_scroll_no', models.CharField(blank=True, max_length=255, null=True)),
                ('file_number', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_file_number', models.CharField(blank=True, max_length=255, null=True)),
                ('time_of_upload', models.CharField(blank=True, max_length=255, null=True)),
                ('failed', models.IntegerField(default=0)),
                ('ebrc', models.BooleanField(default=False)),
                ('scroll_details', models.BooleanField(default=False)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_bills', to='ebrc.fileuploaddetails')),
            ],
        ),
        migrations.CreateModel(
            name='EbrcDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brc_date', models.CharField(blank=True, max_length=255, null=True)),
                ('brc_status', models.CharField(blank=True, max_length=255, null=True)),
                ('realised_value', models.FloatField(default=0)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_realisation', models.CharField(blank=True, max_length=255, null=True)),
                ('brc_utilisation_status', models.CharField(blank=True, max_length=255, null=True)),
                ('ebrcNumb', models.CharField(blank=True, max_length=255, null=True)),
                ('recid', models.CharField(blank=True, max_length=255, null=True)),
                ('iec', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebrc_list', to='ebrc.shippingdetails')),
            ],
        ),
    ]
