# Generated by Django 3.2.5 on 2021-08-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebrc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('usd_import', models.FloatField(default=0)),
                ('gbp_import', models.FloatField(default=0)),
                ('euro_import', models.FloatField(default=0)),
                ('usd_export', models.FloatField(default=0)),
                ('gbp_export', models.FloatField(default=0)),
                ('euro_export', models.FloatField(default=0)),
                ('notification_no', models.CharField(max_length=255)),
            ],
        ),
    ]
