# Generated by Django 6.0.4 on 2026-05-27 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allotment', '0001_initial'),
        ('core', '0001_initial'),
        ('license', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allotmentitems',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allotment_details', to='license.licenseimportitemsmodel'),
        ),
        migrations.AddField(
            model_name='allotmentitems',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allotmentmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_allotments', to='core.companymodel'),
        ),
        migrations.AddField(
            model_name='allotmentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allotmentmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allotmentmodel',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='core.portmodel'),
        ),
        migrations.AddField(
            model_name='allotmentmodel',
            name='related_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_company', to='core.companymodel'),
        ),
        migrations.AddField(
            model_name='allotmentitems',
            name='allotment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allotment_details', to='allotment.allotmentmodel'),
        ),
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['company', 'estimated_arrival_date'], name='allotment_a_company_0dd483_idx'),
        ),
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['port', 'estimated_arrival_date'], name='allotment_a_port_id_200ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['related_company'], name='allotment_a_related_0e68da_idx'),
        ),
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['estimated_arrival_date'], name='allotment_a_estimat_ce64be_idx'),
        ),
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['is_boe', 'is_allotted'], name='allotment_a_is_boe_c48035_idx'),
        ),
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['type'], name='allotment_a_type_6be869_idx'),
        ),
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['invoice'], name='allotment_a_invoice_59d4eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='allotmentitems',
            unique_together={('item', 'allotment')},
        ),
    ]
