# Generated by Django 6.0.4 on 2026-06-17 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0002_initial'),
        ('core', '0003_create_materialized_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allotmentmodel',
            name='item_name_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allotments', to='core.itemnamemodel'),
        ),
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['item_name_fk'], name='allotment_a_item_na_3573d2_idx'),
        ),
    ]
