# Generated by Django 6.0.4 on 2026-08-07 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0003_allotmentitems_indexes'),
        ('core', '0011_split_milk_into_swp_dwp_wpc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotmentmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_allotments', to='core.companymodel'),
        ),
        migrations.AlterField(
            model_name='allotmentmodel',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allotments', to='core.portmodel'),
        ),
        migrations.AlterField(
            model_name='allotmentmodel',
            name='related_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_company', to='core.companymodel'),
        ),
    ]
