# Generated by Django 6.0.4 on 2026-08-10 16:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0005_allocation_lifecycle'),
        ('core', '0011_split_milk_into_swp_dwp_wpc'),
        ('license', '0017_alter_licensedetailsmodel_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RELEASED', 'Released'), ('REACTIVATED', 'Reactivated'), ('COMPLETED', 'Completed')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('cif_fc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('change_reason', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('ALLOCATION', 'Allocation Created'), ('RELEASE', 'Allocation Released'), ('REVERSAL', 'Release Reversed'), ('REACTIVATION', 'Allocation Reactivated'), ('BOE_RECONCILIATION', 'BOE Reconciliation'), ('COMPANY_CHANGE', 'Company Changed'), ('SHORTFALL_FULFILLMENT', 'Shortfall Fulfilled')], db_index=True, max_length=30)),
                ('quantity_before', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('quantity_after', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('cif_before', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cif_after', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Shortfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('required_cif', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocated_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('allocated_cif', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('FULFILLED', 'Fulfilled')], db_index=True, default='PENDING', max_length=30)),
                ('fulfilled_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.RenameIndex(
            model_name='allotmentitems',
            new_name='allotment_a_status_0046e6_idx',
            old_name='allotment_a_status_idx',
        ),
        migrations.RenameIndex(
            model_name='allotmentitems',
            new_name='allotment_a_allotme_f4e8bc_idx',
            old_name='allotment_a_allot_status_idx',
        ),
        migrations.AddField(
            model_name='allocationversion',
            name='allocation_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='allotment.allotmentitems'),
        ),
        migrations.AddField(
            model_name='allocationversion',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.companymodel'),
        ),
        migrations.AddField(
            model_name='allocationversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationversion',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='allocation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='allotment.allotmentitems'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='company_after',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_to', to='core.companymodel'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='company_before',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_from', to='core.companymodel'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortfall',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortfall',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortfalls', to='license.licensedetailsmodel'),
        ),
        migrations.AddField(
            model_name='shortfall',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='allocationversion',
            index=models.Index(fields=['allocation_item', '-created_on'], name='allotment_a_allocat_57b921_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['allocation_item', '-created_on'], name='allotment_a_allocat_a7c3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', '-created_on'], name='allotment_a_action_bee9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', '-created_on'], name='allotment_a_actor_i_2e3045_idx'),
        ),
        migrations.AddIndex(
            model_name='shortfall',
            index=models.Index(fields=['license', 'status'], name='allotment_s_license_0d80cb_idx'),
        ),
        migrations.AddIndex(
            model_name='shortfall',
            index=models.Index(fields=['created_on'], name='allotment_s_created_cac8ef_idx'),
        ),
    ]
