# Generated by Django 6.0.4 on 2026-08-18 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0008_planning_mapping_statuses'),
        ('core', '0016_merge_numbered_norm_suffixed_item_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotmentmodel',
            name='planning_mapping_source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='allotmentmodel',
            name='planning_mapping_status',
            field=models.CharField(db_index=True, default='UNMAPPED_AMBIGUOUS', max_length=32),
        ),
        migrations.AddField(
            model_name='allotmentmodel',
            name='planning_target_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allotment_planning_targets', to='core.itemnamemodel'),
        ),
    ]
