# Generated by Django 6.0.4 on 2026-08-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0009_allotment_parent_planning_target'),
        ('allotment', '0009_allotmentmodel_planning_mapping_source_and_more'),
    ]

    operations = [
    ]
