# Generated by Django 6.0.4 on 2026-05-27 05:11

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill_of_entry', '0001_initial'),
        ('core', '0001_initial'),
        ('license', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('COMMISSION_PURCHASE', 'Commission Purchase'), ('COMMISSION_SALE', 'Commission Sale')], db_index=True, max_length=20)),
                ('license_type', models.CharField(choices=[('DFIA', 'DFIA License'), ('INCENTIVE', 'Incentive License')], db_index=True, default='DFIA', help_text='Type of license to use for this trade', max_length=20)),
                ('from_pan', models.CharField(blank=True, max_length=32, null=True)),
                ('from_gst', models.CharField(blank=True, max_length=32, null=True)),
                ('from_addr_line_1', models.TextField(blank=True, null=True)),
                ('from_addr_line_2', models.TextField(blank=True, null=True)),
                ('to_pan', models.CharField(blank=True, max_length=32, null=True)),
                ('to_gst', models.CharField(blank=True, max_length=32, null=True)),
                ('to_addr_line_1', models.TextField(blank=True, null=True)),
                ('to_addr_line_2', models.TextField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('roundoff', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('purchase_invoice_copy', models.FileField(blank=True, null=True, upload_to='trade/purchase_invoices/')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('boe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_trades', to='bill_of_entry.billofentrymodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_created', to=settings.AUTH_USER_MODEL)),
                ('from_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_from_company', to='core.companymodel')),
                ('incentive_license', models.ForeignKey(blank=True, help_text='Incentive License (RODTEP/ROSTL/MEIS) - used when license_type is INCENTIVE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='license.incentivelicense')),
                ('linked_trade', models.ForeignKey(blank=True, help_text='Links this trade to its paired counterpart (Sale↔Purchase)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_trades', to='trade.licensetrade')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_modified', to=settings.AUTH_USER_MODEL)),
                ('to_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_to_company', to='core.companymodel')),
            ],
            options={
                'ordering': ['-invoice_date', '-invoice_number', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='IncentiveTradeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='License value in INR', max_digits=20)),
                ('rate_pct', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Billing rate as percentage', max_digits=9)),
                ('amount_inr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated amount = license_value × rate_pct / 100', max_digits=20)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('incentive_license', models.ForeignKey(help_text='The incentive license being traded', on_delete=django.db.models.deletion.PROTECT, related_name='trade_lines', to='license.incentivelicense')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_lines', to='trade.licensetrade')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LicenseTradeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('hsn_code', models.CharField(blank=True, default='49070000', max_length=10)),
                ('mode', models.CharField(choices=[('QTY', 'Quantity (Kg × Rate)'), ('CIF_INR', 'CIF (INR × %)'), ('FOB_INR', 'FOB (INR × %)')], db_index=True, default='QTY', max_length=10)),
                ('qty_kg', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('rate_inr_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('cif_fc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('exc_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('cif_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('fob_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('pct', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=9)),
                ('amount_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('sr_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_lines', to='license.licenseimportitemsmodel')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='trade.licensetrade')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LicenseTradePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trade.licensetrade')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='licensetrade',
            index=models.Index(fields=['invoice_date'], name='trade_licen_invoice_21c4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='licensetrade',
            index=models.Index(fields=['direction', 'invoice_date'], name='trade_licen_directi_ca4cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='licensetrade',
            index=models.Index(fields=['direction', 'from_company'], name='trade_licen_directi_c3e4ce_idx'),
        ),
        migrations.AddIndex(
            model_name='licensetrade',
            index=models.Index(fields=['direction', 'to_company'], name='trade_licen_directi_2b7c25_idx'),
        ),
        migrations.AddConstraint(
            model_name='licensetrade',
            constraint=models.CheckConstraint(condition=models.Q(('from_company__isnull', True), ('to_company__isnull', True), models.Q(('from_company', models.F('to_company')), _negated=True), _connector='OR'), name='chk_from_to_companies_different'),
        ),
        migrations.AddConstraint(
            model_name='licensetrade',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'PURCHASE'), models.Q(('invoice_number', ''), _negated=True)), fields=('from_company', 'invoice_number', 'direction'), name='uniq_purchase_supplier_invoice'),
        ),
        migrations.AddConstraint(
            model_name='licensetrade',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'SALE'), models.Q(('invoice_number', ''), _negated=True)), fields=('to_company', 'invoice_number', 'direction'), name='uniq_sale_buyer_invoice_nonblank'),
        ),
    ]
