from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

urlpatterns = [
    path('licence/report/biscuits/', login_required(views.PDFSummaryLicenseDetailView.as_view()),
         name='licence_report_biscuits_new'),
    path('analysis/', login_required(views.analysis), name='analysis'),
    path('add/', login_required(views.LicenseDetailCreateView.as_view()), name='license-add'),
    path('<slug:license>/new/', login_required(views.DFIADetailView.as_view()), name='dfia-details'),
    path('<slug:license>/card/', login_required(views.LicenseCardView.as_view()), name='license-card'),
    path('', login_required(views.LicenseListView.as_view()), name='license-list'),
    path('ajax/', login_required(views.LicenseAjaxListView.as_view()), name='license-ajax-list'),
    path('<slug:license>/update', login_required(views.LicenseDetailUpdateView.as_view()), name='license-update'),
    path('<slug:license>/', login_required(views.LicenseDetailView.as_view()), name='license-detail'),
    path('<slug:license>/item/update', login_required(views.LicenseItemListUpdateView.as_view()),
         name='license-item-update'),
    path('<int:pk>/verify', login_required(views.LicenseVerifyView.as_view()), name='license-verify'),
    path('<slug:license>.pdf', login_required(views.PDFLicenseDetailView.as_view()), name='license-pdf'),
    path('amd/<slug:license>.pdf', login_required(views.PDFAmendmentLicenseDetailView.as_view()),
         name='amend-license-pdf'),
    path('<slug:license>.xlsx', login_required(views.ExcelLicenseDetailView.as_view()), name='license-excel'),
    path('ledger/<slug:license>.pdf', login_required(views.PDFLedgerLicenseDetailView.as_view()),
         name='license_ledger'),
    path('ledger/item/<slug:license>.pdf', login_required(views.PDFLedgerItemLicenseDetailView.as_view()),
         name='license_item_ledger_pdf'),
    path('report/other/conversion/', login_required(views.PDFOCReportView.as_view()), name='report_other_conversion'),
    path('report/2015/biscuits/', login_required(views.PDFNewBiscuitsReportView.as_view()), name='report_new_biscuits'),
    path('report/2015/confectinery/', login_required(views.PDFNewConfectioneryReportView.as_view()),
         name='report_new_confectionery'),
    path('report/2015/biscuits/other/', login_required(views.PDFNewBiscuitsOtherReportView.as_view()),
         name='report_new_biscuits_other'),
    path('report/2015/confectinery/other/', login_required(views.PDFNewConfectioneryOtherReportView.as_view()),
         name='report_new_confectionery_other'),
    path('report/2009/biscuits/', login_required(views.PDFOldBisReportView.as_view()), name='report_bis_old'),
    path('report/2009/confectinery/', login_required(views.PDFOldConReportView.as_view()), name='report_con_old'),
    path('biscuits/2015/expiried', login_required(views.PDFBiscuitsNewExpiryReportView.as_view()),
         name='biscuits_expiried_new'),
    path('confectinery/2015/expiried', login_required(views.PDFConfectioneryNewExpiredReportView.as_view()),
         name='confectinery_expiried_new'),
    path('biscuits/2009/expiried', login_required(views.PDFBiscuitsOldExpiryReportView.as_view()),
         name='biscuits_expiried_old'),
    path('confectinery/2009/expiried', login_required(views.PDFConfectioneryOldExpiredReportView.as_view()),
         name='confectinery_expiried_old'),
    path('confectinery/other/2009/expiried', login_required(views.PDFOtherConfectioneryOldExpiredReportView.as_view()),
         name='confectinery_other_expiried_old'),
    path('confectinery/au', login_required(views.PDFAUConfectioneryReportView.as_view()),
         name='confectinery_au'),
    path('biscuits/au', login_required(views.PDFAUBiscuitsReportView.as_view()),
         name='biscuits_au'),
    path('item/report', login_required(views.ItemReportView.as_view()),
         name='item_report'),
    path('item/report/list/', login_required(views.ItemListReportView.as_view()),
         name='item_report_list'),
    path('calc/premium', login_required(views.PremiumCalculationView.as_view()), name='premium'),
    path('generate/report', login_required(views.LicenseReportListView.as_view()), name='report_list'),
    path('consolidate/pdf', login_required(views.LicensePDFConsolidateView.as_view()), name='consolidate'),
    path('movement/list/', login_required(views.MovementListView.as_view()), name='movement-list'),
    path('movement/update/', login_required(views.MovementUpdateView.as_view()), name='movement-update'),
    path('summary/<slug:license>.pdf', login_required(views.PDFSummaryLicenseDetailView.as_view()),
         name='license_summary'),
    path('report/biscuit/live', login_required(views.BiscuitLiveReportView.as_view()), name='report_conversion'),
]
