# Generated by Django 5.2.7 on 2025-10-30 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllotmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AR', 'ARO'), ('AT', 'Allotment')], default='AT', max_length=2)),
                ('required_quantity', models.FloatField(default=0)),
                ('unit_value_per_unit', models.FloatField(default=0)),
                ('item_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_arrival_date', models.DateField(blank=True, null=True)),
                ('bl_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_on', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_allotments', to='core.companymodel')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='core.portmodel')),
                ('related_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_company', to='core.companymodel')),
            ],
            options={
                'ordering': ['estimated_arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='AllotmentItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif_inr', models.FloatField(default=0.0)),
                ('cif_fc', models.FloatField(default=0.0)),
                ('qty', models.FloatField(default=0.0)),
                ('is_boe', models.BooleanField(default=False)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allotment_details', to='license.licenseimportitemsmodel')),
                ('allotment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allotment_details', to='allotment.allotmentmodel')),
            ],
            options={
                'ordering': ['qty'],
                'unique_together': {('item', 'allotment')},
            },
        ),
    ]
