# Generated by Django 2.2.3 on 2019-07-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotmentitems',
            name='is_boe',
            field=models.BooleanField(default=False),
        ),
    ]
