# Generated by Django 4.1.7 on 2024-01-14 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230201_0928'),
        ('allotment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotmentmodel',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='core.portmodel'),
        ),
    ]
