# Generated by Django 2.2.3 on 2020-04-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0002_transferlettermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferLetterModel',
        ),
    ]
