# Generated by Django 4.2.21 on 2025-07-06 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0031_alter_licensedetailsmodel_purchase_status'),
        ('allotment', '0002_alter_allotmentmodel_port'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allotmentitems',
            unique_together={('item', 'allotment')},
        ),
    ]
