# Generated by Django 2.2.3 on 2019-12-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0002_allotmentitems_is_boe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allotmentmodel',
            options={'ordering': ['modified_on']},
        ),
    ]
