# Generated by Django 2.2.3 on 2020-02-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0003_auto_20191229_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotmentmodel',
            name='eta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allotmentmodel',
            name='invoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
