# Generated by Django 2.2.3 on 2020-08-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0003_delete_transferlettermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotmentmodel',
            name='bl_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
