# Generated by Django 3.1.6 on 2021-11-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0004_allotmentmodel_bl_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotmentmodel',
            name='estimated_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
