# Generated by Django 3.1.6 on 2021-11-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0005_allotmentmodel_estimated_arrival_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allotmentmodel',
            options={'ordering': ['estimated_arrival_date']},
        ),
    ]
