# Generated by Django 3.1.6 on 2021-11-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0010_licensedetailsmodel_fob'),
        ('allotment', '0006_auto_20211121_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotmentitems',
            name='allotment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allotment_details', to='allotment.allotmentmodel'),
        ),
        migrations.AlterField(
            model_name='allotmentitems',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allotment_details', to='license.licenseimportitemsmodel'),
        ),
    ]
