# Generated by Django 3.1.6 on 2021-11-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0007_auto_20211124_0850'),
        ('allotment', '0006_auto_20211122_0902'),
    ]

    operations = [
    ]
