# Generated by Django 3.1.6 on 2021-11-26 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0007_auto_20211124_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allotmentmodel',
            name='eta',
        ),
    ]
