# Generated by Django 3.1.6 on 2021-11-26 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0008_merge_20211124_0852'),
        ('allotment', '0008_remove_allotmentmodel_eta'),
    ]

    operations = [
    ]
