# Generated by Django 4.2.20 on 2025-05-04 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True)),
                ('scheme', models.CharField(choices=[('RoDTEP', 'Rodtep'), ('SEIS', 'Seis'), ('MEIS', 'Meis'), ('RoSCTL', 'Rosctl')], max_length=10)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='TradeParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('iec', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuySellInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_purchase', models.BooleanField()),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('license_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other_script.license')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='other_script.tradeparty')),
            ],
        ),
    ]
