# Generated by Django 5.0.3 on 2025-11-16 10:17

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('allotment', '0003_alter_allotmentitems_cif_fc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotmentmodel',
            name='cif_fc',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True,
                                      validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='allotmentmodel',
            name='cif_inr',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True,
                                      validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
