# Generated by Django 5.0.3 on 2025-11-16 10:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0004_allotmentmodel_cif_fc_allotmentmodel_cif_inr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotmentmodel',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.00'), max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
