# Generated by Django 5.0.3 on 2025-11-16 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('allotment', '0005_allotmentmodel_exchange_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='allotmentmodel',
        #     name='created_by',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='allotmentmodel',
        #     name='created_on',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='allotmentmodel',
            name='is_boe',
            field=models.BooleanField(default=False),
        ),
        # migrations.AddField(
        #     model_name='allotmentmodel',
        #     name='modified_by',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
        #                             related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        # ),
        migrations.AlterField(
            model_name='allotmentmodel',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
