# Generated by Django 5.0.3 on 2025-11-16 15:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0007_allotmentmodel_created_by_allotmentmodel_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotmentmodel',
            name='unit_value_per_unit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
