# Generated by Django 5.0.3 on 2025-11-20 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0011_populate_is_allotted'),
        ('core', '0015_alter_invoiceentity_address_line_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['company', 'estimated_arrival_date'], name='allotment_a_company_0dd483_idx'),
        ),
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['port', 'estimated_arrival_date'], name='allotment_a_port_id_200ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['related_company'], name='allotment_a_related_0e68da_idx'),
        ),
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['estimated_arrival_date'], name='allotment_a_estimat_ce64be_idx'),
        ),
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['is_boe', 'is_allotted'], name='allotment_a_is_boe_c48035_idx'),
        ),
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['type'], name='allotment_a_type_6be869_idx'),
        ),
        migrations.AddIndex(
            model_name='allotmentmodel',
            index=models.Index(fields=['invoice'], name='allotment_a_invoice_59d4eb_idx'),
        ),
    ]
