# Generated by Django 5.0.3 on 2026-02-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0014_add_composite_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='allotmentitems',
            name='allot_item_allotment_idx',
        ),
        migrations.RemoveIndex(
            model_name='allotmentitems',
            name='allot_detail_lookup_idx',
        ),
        migrations.RemoveIndex(
            model_name='allotmentitems',
            name='allot_item_qty_idx',
        ),
        migrations.RemoveIndex(
            model_name='allotmentmodel',
            name='allot_company_arrival_idx',
        ),
        migrations.RemoveIndex(
            model_name='allotmentmodel',
            name='allot_port_arrival_idx',
        ),
        migrations.RemoveIndex(
            model_name='allotmentmodel',
            name='allot_boe_status_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='allotmentmodel',
            name='allot_type_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='allotmentmodel',
            name='allot_invoice_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='allotmentmodel',
            name='allot_related_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='allotmentmodel',
            name='allot_approved_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='allotmentmodel',
            name='allot_pending_company_idx',
        ),
    ]
