# Generated by Django 3.1.6 on 2021-11-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseMovementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('S', 'Send'), ('R', 'Received')], max_length=2)),
                ('license_from', models.CharField(max_length=255)),
                ('license_to', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('medium', models.CharField(choices=[('C', 'Courier'), ('P', 'Person')], max_length=2)),
                ('courier_or_person_name', models.CharField(max_length=255)),
                ('courier_or_person_number', models.CharField(max_length=255)),
            ],
        ),
    ]
