# Generated by Django 5.2.7 on 2025-10-30 14:31

import django.db.models.deletion
import license.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlongWithModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.CharField(choices=[('26', '26 - Duty Free Import Authorization')], default='26', max_length=10)),
                ('notification_number', models.CharField(choices=[('019/2015', '019/2015'), ('098/2009', '098/2009'), ('025/2023', '025/2023')], default='025/2023', max_length=10)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('file_number', models.CharField(blank=True, max_length=30, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('condition_sheet', models.TextField(blank=True, null=True)),
                ('user_restrictions', models.TextField(blank=True, null=True)),
                ('ledger_date', models.DateField(blank=True, null=True)),
                ('is_audit', models.BooleanField(default=False)),
                ('is_mnm', models.BooleanField(default=False)),
                ('is_not_registered', models.BooleanField(default=False)),
                ('is_null', models.BooleanField(default=False)),
                ('purchase_status', models.CharField(choices=[('GE', 'GE Purchase'), ('NP', 'GE Operating'), ('IP', 'GE Item Purchase'), ('SM', 'SM Purchase'), ('OT', 'OT Purchase'), ('CO', 'Conversion'), ('RA', 'Ravi Foods'), ('LM', 'LM Purchase')], default='GE', max_length=2)),
                ('is_au', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('balance_cif', models.FloatField(default=0.0)),
                ('export_item', models.CharField(blank=True, max_length=255, null=True)),
                ('is_incomplete', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_individual', models.BooleanField(default=False)),
                ('ge_file_number', models.IntegerField(default=0)),
                ('fob', models.IntegerField(blank=True, default=0, null=True)),
                ('billing_rate', models.FloatField(default=0)),
                ('billing_amount', models.FloatField(default=0)),
                ('file_transfer_status', models.TextField(blank=True, null=True)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_data', to='core.companymodel')),
                ('exporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.companymodel')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.portmodel')),
            ],
            options={
                'ordering': ('license_expiry_date',),
            },
        ),
        migrations.CreateModel(
            name='LicenseDocumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=license.models.license_path)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_documents', to='license.licensedetailsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseExportItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('duty_type', models.CharField(default='Basic', max_length=255)),
                ('net_quantity', models.FloatField(default=0)),
                ('old_quantity', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kg')], default='kg', max_length=10)),
                ('fob_fc', models.FloatField(default=0)),
                ('fob_inr', models.FloatField(default=0)),
                ('fob_exchange_rate', models.FloatField(default=0)),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('euro', 'euro')], default='usd', max_length=5)),
                ('value_addition', models.FloatField(default=15)),
                ('cif_fc', models.FloatField(default=0)),
                ('cif_inr', models.FloatField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_licenses', to='core.itemnamemodel')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_license', to='license.licensedetailsmodel')),
                ('norm_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_item', to='core.sionnormclassmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseTransferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('transfer_status', models.CharField(max_length=50)),
                ('transfer_initiation_date', models.DateTimeField(blank=True, null=True)),
                ('transfer_acceptance_date', models.DateTimeField(blank=True, null=True)),
                ('cbic_status', models.CharField(blank=True, max_length=100, null=True)),
                ('cbic_response_date', models.DateTimeField(blank=True, null=True)),
                ('user_id_transfer_initiation', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id_acceptance', models.CharField(blank=True, max_length=100, null=True)),
                ('from_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='core.companymodel')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='license.licensedetailsmodel')),
                ('to_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='core.companymodel')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseInwardOutwardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('amd_sheets_number', models.CharField(blank=True, max_length=100, null=True)),
                ('copy', models.BooleanField(default=False)),
                ('annexure', models.BooleanField(default=False)),
                ('tl', models.BooleanField(default=False)),
                ('aro', models.BooleanField(default=False)),
                ('along_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.alongwithmodel')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.datemodel')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.licensedetailsmodel')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.officemodel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.statusmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseImportItemsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('duty_type', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('old_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit', models.CharField(choices=[('kg', 'kg')], default='kg', max_length=10)),
                ('cif_fc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cif_inr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('available_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('debited_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('debited_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allotted_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allotted_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_restrict', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('hs_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_item', to='core.hscodemodel')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_items', to='core.itemnamemodel')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_license', to='license.licensedetailsmodel')),
            ],
            options={
                'ordering': ['license__license_expiry_date', 'serial_number'],
                'indexes': [models.Index(fields=['license'], name='license_lic_license_d4d897_idx'), models.Index(fields=['hs_code'], name='license_lic_hs_code_063682_idx'), models.Index(fields=['item'], name='license_lic_item_id_c3fee2_idx')],
                'unique_together': {('license', 'serial_number')},
            },
        ),
    ]
