# Generated by Django 5.2.7 on 2025-11-04 02:37

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0002_alter_billofentrymodel_options_and_more'),
        ('core', '0002_invoiceentity_notificationnumber_purchasestatus_and_more'),
        ('license', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_company_name', models.CharField(max_length=255)),
                ('to_company_pan', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('to_company_gst_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number.', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('to_company_address_line_1', models.TextField()),
                ('to_company_address_line_2', models.TextField(blank=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('billing_mode', models.CharField(choices=[('kg', 'KG'), ('cif', 'CIF %'), ('fob', 'FOB %')], max_length=10)),
                ('total_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_cif_fc', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cif_inr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_fob_inr', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount_in_words', models.TextField(blank=True, null=True)),
                ('sale_type', models.CharField(choices=[('item', 'Item'), ('full', 'Full')], default='item', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=50)),
                ('hsn_code', models.CharField(default='490700', max_length=10)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('cif_fc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cif_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fob_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='LicensePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('supplier_pan', models.CharField(blank=True, max_length=32, null=True)),
                ('supplier_gst', models.CharField(blank=True, max_length=32, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=128, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_copy', models.FileField(blank=True, null=True, upload_to='license_purchases/invoices/')),
                ('mode', models.CharField(choices=[('AMOUNT', 'Amount-based'), ('QTY', 'Quantity-based')], default='AMOUNT', max_length=10)),
                ('amount_source', models.CharField(choices=[('FOB_INR', 'FOB (INR)'), ('CIF_INR', 'CIF (INR)'), ('CIF_USD', 'CIF (USD)')], default='FOB_INR', max_length=10)),
                ('fob_inr', models.FloatField(default=0)),
                ('cif_inr', models.FloatField(default=0)),
                ('cif_usd', models.FloatField(default=0)),
                ('exchange_rate', models.FloatField(default=0)),
                ('markup_pct', models.FloatField(default=0)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_kg', models.FloatField(default=0)),
                ('rate_inr', models.FloatField(default=0)),
                ('amount_inr', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.RemoveIndex(
            model_name='licenseimportitemsmodel',
            name='license_lic_item_id_c3fee2_idx',
        ),
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='item',
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='license_import_item', to='core.itemnamemodel'),
        ),
        migrations.AlterField(
            model_name='alongwithmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='licensedocumentmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='licenseexportitemmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='licenseinwardoutwardmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='licensetransfermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='officemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statusmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bills_of_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='bill_of_entry.billofentrymodel'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='from_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoiceentity'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='license.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sr_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='license.licenseimportitemsmodel'),
        ),
        migrations.AddField(
            model_name='licensepurchase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licensepurchase',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='license.licensedetailsmodel'),
        ),
        migrations.AddField(
            model_name='licensepurchase',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licensepurchase',
            name='purchasing_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_purchases', to='core.companymodel'),
        ),
        migrations.AddField(
            model_name='licensepurchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_purchases', to='core.companymodel'),
        ),
    ]
