# Generated by Django 5.2.7 on 2025-11-15 01:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_alter_licensedetailsmodel_balance_cif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseexportitemmodel',
            name='fob_exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='allotted_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='available_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='debited_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='old_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='licensepurchase',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='licensepurchase',
            name='markup_pct',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='licensepurchase',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
    ]
