# Generated by Django 5.0.3 on 2025-11-20 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0008_cleanup_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='is_restrict',
        ),
    ]
