# Generated by Django 5.0.3 on 2025-11-20 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_invoiceentity_address_line_2'),
        ('license', '0009_remove_licenseimportitemsmodel_is_restrict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='licensedetailsmodel',
            index=models.Index(fields=['license_number'], name='license_lic_license_da9183_idx'),
        ),
        migrations.AddIndex(
            model_name='licensedetailsmodel',
            index=models.Index(fields=['file_number'], name='license_lic_file_nu_3521e3_idx'),
        ),
        migrations.AddIndex(
            model_name='licensedetailsmodel',
            index=models.Index(fields=['exporter', 'license_date'], name='license_lic_exporte_68eed3_idx'),
        ),
        migrations.AddIndex(
            model_name='licensedetailsmodel',
            index=models.Index(fields=['port', 'license_date'], name='license_lic_port_id_939805_idx'),
        ),
        migrations.AddIndex(
            model_name='licensedetailsmodel',
            index=models.Index(fields=['purchase_status'], name='license_lic_purchas_97c381_idx'),
        ),
        migrations.AddIndex(
            model_name='licensedetailsmodel',
            index=models.Index(fields=['license_date'], name='license_lic_license_0bb342_idx'),
        ),
        migrations.AddIndex(
            model_name='licensedetailsmodel',
            index=models.Index(fields=['license_expiry_date'], name='license_lic_license_e4834c_idx'),
        ),
        migrations.AddIndex(
            model_name='licensedetailsmodel',
            index=models.Index(fields=['is_active', 'is_expired'], name='license_lic_is_acti_ea2a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='licensedetailsmodel',
            index=models.Index(fields=['balance_cif'], name='license_lic_balance_bfb1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='licensedetailsmodel',
            index=models.Index(fields=['current_owner'], name='license_lic_current_1e3d2b_idx'),
        ),
    ]
