# Generated by Django 5.0.3 on 2025-12-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensedetailsmodel',
            options={'ordering': ('license_expiry_date', 'license_date')},
        ),
    ]
