# Generated by Django 5.0.3 on 2025-12-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0011_alter_licensedocumentmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='balance_report_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
