# Generated by Django 5.0.3 on 2025-12-18 14:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_celerytasktracker'),
        ('license', '0012_licensedetailsmodel_balance_report_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('license_type', models.CharField(choices=[('RODTEP', 'RODTEP'), ('ROSTL', 'ROSTL'), ('MEIS', 'MEIS')], db_index=True, max_length=10)),
                ('license_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('license_date', models.DateField()),
                ('license_expiry_date', models.DateField(help_text='Auto-calculated as 2 years from license date')),
                ('license_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total license value in INR', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_licenses', to='core.companymodel')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('port_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_licenses', to='core.portmodel')),
            ],
            options={
                'verbose_name': 'Incentive License',
                'verbose_name_plural': 'Incentive Licenses',
                'ordering': ('-license_date', 'license_number'),
                'indexes': [models.Index(fields=['license_number'], name='license_inc_license_0c52e3_idx'), models.Index(fields=['license_type'], name='license_inc_license_d1e17f_idx'), models.Index(fields=['exporter', 'license_date'], name='license_inc_exporte_60be35_idx'), models.Index(fields=['license_date'], name='license_inc_license_4b60f2_idx'), models.Index(fields=['license_expiry_date'], name='license_inc_license_4ead9c_idx'), models.Index(fields=['is_active'], name='license_inc_is_acti_8b39a6_idx')],
            },
        ),
    ]
