# Generated by Django 5.0.3 on 2026-01-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0016_change_purchase_status_to_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='licensedetailsmodel',
            new_name='license_lic_purchas_dadd94_idx',
            old_name='license_lic_purchas_97c381_idx',
        ),
    ]
