# Generated by Django 5.0.3 on 2026-01-21 17:42

from django.db import migrations


def rename_index_if_exists(apps, schema_editor):
    """Rename index only if it exists (it was removed in 0016 when field changed to FK)"""
    # Check if old index exists
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT indexname FROM pg_indexes
            WHERE tablename = 'license_licensedetailsmodel'
            AND indexname = 'license_lic_purchas_97c381_idx'
        """)
        if cursor.fetchone():
            # Index exists, rename it
            cursor.execute("""
                ALTER INDEX license_lic_purchas_97c381_idx
                RENAME TO license_lic_purchas_dadd94_idx
            """)


def reverse_rename(apps, schema_editor):
    """Reverse the rename"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT indexname FROM pg_indexes
            WHERE tablename = 'license_licensedetailsmodel'
            AND indexname = 'license_lic_purchas_dadd94_idx'
        """)
        if cursor.fetchone():
            cursor.execute("""
                ALTER INDEX license_lic_purchas_dadd94_idx
                RENAME TO license_lic_purchas_97c381_idx
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0016_change_purchase_status_to_fk'),
    ]

    operations = [
        migrations.RunPython(rename_index_if_exists, reverse_rename),
    ]
