# Generated by Django 5.0.3 on 2026-01-31 10:09

from django.db import migrations


def remove_index_if_exists(apps, schema_editor):
    """Remove old purchase_status index only if it exists"""
    with schema_editor.connection.cursor() as cursor:
        # Check if index exists
        cursor.execute("""
            SELECT indexname FROM pg_indexes
            WHERE tablename = 'license_licensedetailsmodel'
            AND indexname = 'license_lic_purchas_97c381_idx'
        """)
        if cursor.fetchone():
            # Index exists, drop it
            cursor.execute("DROP INDEX IF EXISTS license_lic_purchas_97c381_idx")


def reverse_migration(apps, schema_editor):
    """
    Reverse is a no-op since we don't want to recreate the old index.
    The ForeignKey auto-creates its own index.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0018_update_purchase_status_index'),
    ]

    operations = [
        migrations.RunPython(remove_index_if_exists, reverse_migration),
    ]
