# Generated by Django 5.0.3 on 2026-01-31 10:13

from django.db import migrations


def remove_index_if_exists(apps, schema_editor):
    """Remove old purchase_status index only if it exists (might have been removed in 0019)"""
    with schema_editor.connection.cursor() as cursor:
        # Check if index exists
        cursor.execute("""
            SELECT indexname FROM pg_indexes
            WHERE tablename = 'license_licensedetailsmodel'
            AND indexname = 'license_lic_purchas_97c381_idx'
        """)
        if cursor.fetchone():
            # Index exists, drop it
            cursor.execute("DROP INDEX IF EXISTS license_lic_purchas_97c381_idx")


def reverse_migration(apps, schema_editor):
    """No-op reverse"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0019_remove_licensedetailsmodel_license_lic_purchas_97c381_idx'),
    ]

    operations = [
        migrations.RunPython(remove_index_if_exists, reverse_migration),
    ]
