# Generated by Django 5.0.3 on 2026-01-31 11:54
# Modified to safely handle missing index

from django.db import migrations


def remove_index_final(apps, schema_editor):
    """Final cleanup - remove index if it somehow still exists"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT indexname FROM pg_indexes
            WHERE tablename = 'license_licensedetailsmodel'
            AND indexname = 'license_lic_purchas_97c381_idx'
        """)
        if cursor.fetchone():
            cursor.execute("DROP INDEX IF EXISTS license_lic_purchas_97c381_idx")


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0021_sync_migration_state'),
    ]

    operations = [
        migrations.RunPython(remove_index_final, migrations.RunPython.noop),
        # This RemoveIndex tells Django's migration state the index is gone
        migrations.RemoveIndex(
            model_name='licensedetailsmodel',
            name='license_lic_purchas_97c381_idx',
        ),
    ]
