# Generated by Django 5.0.3 on 2026-04-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0025_remove_licensedetailsmodel_license_active_balance_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='billing_amount',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='billing_rate',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='export_item',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='fob',
        ),
    ]
