# Generated by Django 5.0.3 on 2026-04-07 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_companymodel_company_iec_name_idx_and_more'),
        ('license', '0026_remove_unused_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='licensedetailsmodel',
            index=models.Index(fields=['notification_number'], name='license_lic_notific_5b1519_idx'),
        ),
        migrations.AddIndex(
            model_name='licensedetailsmodel',
            index=models.Index(fields=['scheme_code'], name='license_lic_scheme__3280bf_idx'),
        ),
    ]
