# Generated by Django 6.0.4 on 2026-05-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0032_licenseimportitemsmodel_condition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseexportitemmodel',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
    ]
