# Generated by Django 6.0.4 on 2026-05-27 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill_of_entry', '0001_initial'),
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowdetails',
            name='sr_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='license.licenseimportitemsmodel'),
        ),
        migrations.AddIndex(
            model_name='billofentrymodel',
            index=models.Index(fields=['bill_of_entry_number'], name='bill_of_ent_bill_of_73d627_idx'),
        ),
        migrations.AddIndex(
            model_name='billofentrymodel',
            index=models.Index(fields=['company', 'bill_of_entry_date'], name='bill_of_ent_company_490ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='billofentrymodel',
            index=models.Index(fields=['port', 'bill_of_entry_date'], name='bill_of_ent_port_id_2e6325_idx'),
        ),
        migrations.AddIndex(
            model_name='billofentrymodel',
            index=models.Index(fields=['bill_of_entry_date'], name='bill_of_ent_bill_of_b80252_idx'),
        ),
        migrations.AddIndex(
            model_name='billofentrymodel',
            index=models.Index(fields=['invoice_no', 'invoice_date'], name='bill_of_ent_invoice_182ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='billofentrymodel',
            index=models.Index(fields=['is_fetch'], name='bill_of_ent_is_fetc_01a03d_idx'),
        ),
        migrations.AddIndex(
            model_name='billofentrymodel',
            index=models.Index(fields=['product_name'], name='bill_of_ent_product_8e07f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billofentrymodel',
            unique_together={('bill_of_entry_number', 'bill_of_entry_date', 'port')},
        ),
        migrations.AlterUniqueTogether(
            name='rowdetails',
            unique_together={('bill_of_entry', 'sr_number', 'transaction_type')},
        ),
    ]
