# Generated by Django 3.1.6 on 2022-07-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eScrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLicenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('license_no', models.CharField(blank=True, max_length=255, null=True)),
                ('scheme', models.CharField(blank=True, max_length=255, null=True)),
                ('license_date', models.DateField(blank=True, null=True)),
                ('dgft_transmission_date', models.DateField(blank=True, null=True)),
                ('date_of_integration', models.DateField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=255, null=True)),
                ('file_number', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eScrap.companylistmodel')),
            ],
        ),
    ]
