# Generated by Django 3.1.6 on 2022-07-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScrap', '0002_companylicensemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylistmodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companylistmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companylistmodel',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='companylistmodel',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companylistmodel',
            name='iec_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
