# Generated by Django 3.1.6 on 2022-07-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScrap', '0003_auto_20220726_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylicensemodel',
            name='is_fetch',
            field=models.BooleanField(default=False),
        ),
    ]
