# Generated by Django 3.1.6 on 2022-07-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScrap', '0004_companylicensemodel_is_fetch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companylicensemodel',
            name='is_fetch',
        ),
        migrations.AddField(
            model_name='companylistmodel',
            name='is_fetch',
            field=models.BooleanField(default=False),
        ),
    ]
