# Generated by Django 3.1.6 on 2022-08-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220722_1042'),
        ('eScrap', '0005_auto_20220726_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylistmodel',
            name='port',
            field=models.ManyToManyField(blank=True, null=True, to='core.PortModel'),
        ),
    ]
