# Generated by Django 3.1.6 on 2022-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eScrap', '0006_companylistmodel_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylicensemodel',
            name='port',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
