# Generated by Django 6.0.4 on 2026-07-03 06:15

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def backfill_modified_on(apps, schema_editor):
    """Existing rows get modified_on = created_on so they are visible to the
    first `updated_since` delta pull (new rows are handled by auto_now)."""
    for model_name in ("HeadSIONNormsModel", "SIONExportModel", "SIONImportModel"):
        Model = apps.get_model("core", model_name)
        Model.objects.filter(modified_on__isnull=True).update(modified_on=F("created_on"))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_materialized_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='headsionnormsmodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='headsionnormsmodel',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sionexportmodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='sionexportmodel',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sionimportmodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='sionimportmodel',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='MasterChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(db_index=True, max_length=100)),
                ('natural_key', models.CharField(db_index=True, max_length=255)),
                ('op', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete')], max_length=10)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['at'],
                'indexes': [models.Index(fields=['model_label', 'at'], name='core_master_model_l_4b5abf_idx')],
            },
        ),
        migrations.RunPython(backfill_modified_on, migrations.RunPython.noop),
    ]
