# Generated by Django 6.0.4 on 2026-07-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_headsionnormsmodel_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headsionnormsmodel',
            name='uid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productdescriptionmodel',
            name='uid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sionexportmodel',
            name='uid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sionimportmodel',
            name='uid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sionnormcondition',
            name='uid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sionnormnote',
            name='uid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='unitpricemodel',
            name='uid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
