# Generated by Django 5.0.3 on 2025-11-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_fix_null_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetradeline',
            name='hsn_code',
            field=models.CharField(blank=True, default='49070000', max_length=10),
        ),
    ]
