# Generated by Django 5.0.3 on 2025-11-29 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_licensetradeline_hsn_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetrade',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licensetrade',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
