# Generated by Django 6.0.4 on 2026-08-14 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_master_sync_fields'),
        ('trade', '0004_tradeinvoicedocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDocumentAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('document_type', models.CharField(choices=[('PURCHASE_UPLOADED', 'Purchase uploaded invoice'), ('SALE_GENERATED', 'Generated sale invoice')], max_length=32)),
                ('storage_name', models.CharField(max_length=500)),
                ('document_version', models.CharField(blank=True, default='', max_length=128)),
                ('signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('max_views', models.PositiveSmallIntegerField(default=2)),
                ('view_count', models.PositiveSmallIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_document_tokens', to='core.companymodel')),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_document_tokens', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_access_tokens', to='trade.licensetrade')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDocumentAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('PURCHASE_DOCUMENT_VIEWED', 'Purchase document viewed'), ('SALE_INVOICE_GENERATED', 'Sale invoice generated'), ('SALE_INVOICE_VIEWED', 'Sale invoice viewed'), ('DOCUMENT_VIEW_EXPIRED', 'Document view expired'), ('DOCUMENT_VIEW_FORBIDDEN', 'Document view forbidden')], db_index=True, max_length=40)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('access_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='trade.invoicedocumentaccesstoken')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_document_events', to='trade.licensetrade')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_document_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='invoicedocumentaccesstoken',
            index=models.Index(fields=['expires_at', 'view_count'], name='trade_invoi_expires_b63aa0_idx'),
        ),
    ]
