# Generated by Django 5.0.3 on 2025-12-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_add_user_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensetrade',
            options={'ordering': ['-invoice_date', '-invoice_number', '-created_on']},
        ),
    ]
