# Generated by Django 5.0.3 on 2025-12-20 17:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0013_incentivelicense'),
        ('trade', '0008_add_incentive_license_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveTradeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='License value in INR', max_digits=20)),
                ('rate_pct', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Billing rate as percentage', max_digits=9)),
                ('amount_inr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated amount = license_value × rate_pct / 100', max_digits=20)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('incentive_license', models.ForeignKey(help_text='The incentive license being traded', on_delete=django.db.models.deletion.PROTECT, related_name='trade_lines', to='license.incentivelicense')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_lines', to='trade.licensetrade')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
