# Generated by Django 6.0.4 on 2026-09-18 15:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_sale_classification_decision_not_applicable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetrade',
            name='final_party_status',
            field=models.CharField(choices=[('UNKNOWN', 'Final party not classified'), ('FINAL_PARTY', 'Final purchasing party'), ('INTERLINKED', 'Interlinked or intermediate party'), ('NOT_APPLICABLE', 'No qualifying final-party sale')], db_index=True, default='UNKNOWN', help_text='Explicit final-party classification for SALE invoice packaging.', max_length=16),
        ),
        migrations.AlterField(
            model_name='licensetradeline',
            name='rate_inr_per_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=20),
        ),
    ]
