# Generated by Django 5.0.3 on 2026-03-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_add_commission_direction_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccounts',
            name='linked_company',
        ),
        migrations.RemoveField(
            model_name='chartofaccounts',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='journalentryline',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='linked_payment',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='linked_trade',
        ),
        migrations.RemoveField(
            model_name='journalentryline',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='payment_journal_entry',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='ChartOfAccounts',
        ),
        migrations.DeleteModel(
            name='JournalEntryLine',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
