# Generated by Django 5.0.3 on 2026-03-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_remove_ledger_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionslab',
            name='agent',
        ),
        migrations.DeleteModel(
            name='Commission',
        ),
        migrations.DeleteModel(
            name='CommissionAgent',
        ),
        migrations.DeleteModel(
            name='CommissionSlab',
        ),
    ]
