import { useEffect, useState } from "react";
import { ArrowLeft, Loader2, Plus, TestTube2, Zap } from "lucide-react";
import Select from "react-select";
import { useLocation, useNavigate, useSearchParams } from "react-router-dom";
import api from "@/api/axios";
import PageHeader from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { createSionPlanningRule, fetchSionPlanningRules, planSavedSionRules, testSionPlanningRule, updateSionPlanningRule, type RuleCondition, type RuleGroup, type SionPlanningRule } from "@/services/api/planningRuleApi";

export function planningPath(licenseId?: string | number | null, origin?: string): string { const p = new URLSearchParams(); if (licenseId) p.set("license_id", String(licenseId)); if (origin) p.set("origin", origin); return `/planning${p.size ? `?${p}` : ""}`; }
const emptyCondition = (): RuleCondition => ({ field: "HSN", comparator: "CONTAINS", value: "" });
const emptyRule = (sion: number): SionPlanningRule => ({ sion, name: "", expression: { operator: "AND", conditions: [emptyCondition()] }, max_unit_price: "", unit: "KG", priority: 0, is_active: true });
const isGroup = (node: RuleCondition | RuleGroup): node is RuleGroup => "conditions" in node;

function GroupEditor({ group, onChange, depth = 0 }: { group: RuleGroup; onChange: (g: RuleGroup) => void; depth?: number }) {
    const replace = (index: number, node: RuleCondition | RuleGroup) => onChange({ ...group, conditions: group.conditions.map((old, i) => i === index ? node : old) });
    return <fieldset className="rounded-lg border p-3"><legend className="px-1 text-xs font-semibold">{depth ? "Nested group" : "Match rules"}</legend>
        <label className="text-xs">Logic <select aria-label={depth ? "Nested group logic" : "Rule logic"} value={group.operator} onChange={(e) => onChange({ ...group, operator: e.target.value as "AND" | "OR" })} className="ml-2 rounded border px-2 py-1"><option value="AND">ALL (AND)</option><option value="OR">ANY (OR)</option></select></label>
        <div className="mt-2 space-y-2">{group.conditions.map((node, index) => isGroup(node)
            ? <GroupEditor key={index} group={node} depth={depth + 1} onChange={(value) => replace(index, value)} />
            : <div key={index} className="grid gap-2 sm:grid-cols-[180px_160px_1fr_auto]"><select aria-label={`Condition ${index + 1} field`} value={node.field} onChange={(e) => replace(index, { ...node, field: e.target.value as RuleCondition["field"] })} className="rounded border px-2"><option value="HSN">HSN</option><option value="PRODUCT_DESCRIPTION">Product Description</option></select><select aria-label={`Condition ${index + 1} comparator`} value={node.comparator} onChange={(e) => replace(index, { ...node, comparator: e.target.value as RuleCondition["comparator"] })} className="rounded border px-2"><option value="CONTAINS">Contains</option><option value="NOT_CONTAINS">Does not contain</option></select><input aria-label={`Condition ${index + 1} value`} value={node.value} onChange={(e) => replace(index, { ...node, value: e.target.value })} className="rounded border px-2" /><Button variant="ghost" onClick={() => onChange({ ...group, conditions: group.conditions.filter((_, i) => i !== index) })}>Remove</Button></div>)}</div>
        <div className="mt-2 flex gap-2"><Button size="sm" variant="outline" onClick={() => onChange({ ...group, conditions: [...group.conditions, emptyCondition()] })}><Plus className="size-3" />Condition</Button><Button size="sm" variant="outline" onClick={() => onChange({ ...group, conditions: [...group.conditions, { operator: "AND", conditions: [emptyCondition()] }] })}><Plus className="size-3" />Group</Button></div>
    </fieldset>;
}

export default function LicensePlanningWorkspace() {
    const [params] = useSearchParams(); const navigate = useNavigate(); const location = useLocation();
    const contextLicense = Number(params.get("license_id")) || null; const origin = params.get("origin") || "/licenses";
    const [sions, setSions] = useState<any[]>([]); const [sion, setSion] = useState<number | null>(null); const [rules, setRules] = useState<SionPlanningRule[]>([]); const [draft, setDraft] = useState<SionPlanningRule | null>(null); const [busy, setBusy] = useState<"save" | "test" | "plan" | "deactivate" | null>(null); const [preview, setPreview] = useState<any>(null); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [loading, setLoading] = useState(true);
    useEffect(() => { setLoading(true); api.get("masters/sion-classes/", { params: { is_active: true, page_size: 500, ordering: "norm_class" } }).then(({ data }) => setSions(data?.results ?? data ?? [])).catch(() => setError("Unable to load SION norms.")).finally(() => setLoading(false)); }, []);
    useEffect(() => { if (!sion) { setRules([]); setDraft(null); return; } setLoading(true); setError(""); fetchSionPlanningRules(sion).then((rows) => { setRules(rows); setDraft(rows[0] ?? emptyRule(sion)); }).catch(() => setError("Unable to load planning rules.")).finally(() => setLoading(false)); }, [sion]);
    const savedDraft = draft?.id ? rules.find((rule) => rule.id === draft.id) : null;
    const hasUnsavedChanges = !!draft && (!savedDraft || JSON.stringify(draft) !== JSON.stringify(savedDraft));
    const save = async () => { if (!draft) return null; const { priority: _databasePriority, ...payload } = draft; const saved = draft.id ? await updateSionPlanningRule(draft.id, payload) : await createSionPlanningRule(payload as SionPlanningRule); const fresh = await fetchSionPlanningRules(saved.sion); setRules(fresh); setDraft(fresh.find((rule) => rule.id === saved.id) ?? saved); setSuccess("Rule saved to the database."); return saved; };
    const testRule = async () => { if (busy || !draft?.id || hasUnsavedChanges) return; setBusy("test"); setError(""); setSuccess(""); try { setPreview(await testSionPlanningRule(draft.id, contextLicense ? [contextLicense] : [])); setSuccess("Saved database rule test completed."); } catch { setError("Rule test failed."); } finally { setBusy(null); } };
    const planSion = async () => { if (busy || !sion || hasUnsavedChanges) return; setBusy("plan"); setError(""); setSuccess(""); try { setPreview(await planSavedSionRules(sion, contextLicense ? [contextLicense] : [])); setSuccess("Saved active SION rules planned in database priority order."); setRules(await fetchSionPlanningRules(sion)); } catch { setError("Planning failed."); } finally { setBusy(null); } };
    return <div><PageHeader pretitle="License Planning" title="SION Planning Rules" description="Select a SION, define backend-evaluated rules, test matches, then plan explicitly." actions={<Button variant="outline" onClick={() => navigate(origin, { state: { fromPlanning: location.pathname + location.search } })}><ArrowLeft className="size-4" />Back</Button>} />
        <section className="space-y-4 rounded-xl border bg-card p-4">{error && <p role="alert" className="rounded bg-destructive/10 p-2 text-sm text-destructive">{error}</p>}{success && <p role="status" className="rounded bg-success/10 p-2 text-sm text-success">{success}</p>}{loading && <p role="status" className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin" />Loading…</p>}<label className="block text-sm font-semibold">SION Norm<Select aria-label="SION Norm" options={sions.map((row) => ({ value: row.id, label: row.norm_class }))} value={sions.filter((row) => row.id === sion).map((row) => ({ value: row.id, label: row.norm_class }))[0] ?? null} onChange={(option) => setSion(option?.value ?? null)} className="mt-1 font-normal" /></label>
            {!sion && <p className="text-sm text-muted-foreground">Select a SION norm to view and author its planning rules.</p>}
            {draft && <><div className="flex flex-wrap gap-2"><label className="flex-1 text-xs">Rule name<input aria-label="Rule name" value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} className="mt-1 h-9 w-full rounded border px-2" /></label><label className="text-xs">Max unit price<input aria-label="Maximum unit price" inputMode="decimal" value={draft.max_unit_price} onChange={(e) => /^\d*(\.\d*)?$/.test(e.target.value) && setDraft({ ...draft, max_unit_price: e.target.value })} className="mt-1 block h-9 rounded border px-2" /></label><label className="text-xs">Unit<input aria-label="Planning unit" value={draft.unit} onChange={(e) => setDraft({ ...draft, unit: e.target.value })} className="mt-1 block h-9 rounded border px-2" /></label><label className="text-xs">Database priority<input aria-label="Rule priority" readOnly value={draft.priority || "Assigned on save"} className="mt-1 block h-9 w-32 rounded border bg-muted px-2" /></label><label className="flex items-center gap-2 self-end pb-2 text-xs"><input aria-label="Rule active" type="checkbox" checked={draft.is_active} onChange={(e) => setDraft({ ...draft, is_active: e.target.checked })} />Active</label></div><p role="status" className="text-xs font-medium">{hasUnsavedChanges ? "Unsaved changes — save before Test or Plan." : "Saved in database"}</p>{draft.id && <p className="text-xs text-muted-foreground">Version {draft.version ?? "—"} · Updated {draft.modified_on ? new Date(draft.modified_on).toLocaleString() : "—"}{draft.modified_by_username ? ` by ${draft.modified_by_username}` : ""}</p>}<GroupEditor group={draft.expression} onChange={(expression) => setDraft({ ...draft, expression })} />
                <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setDraft(emptyRule(sion))}><Plus className="size-4" />New Rule</Button><Button variant="outline" onClick={async () => { if (busy) return; setBusy("save"); try { await save(); } finally { setBusy(null); } }} disabled={!!busy || !draft.name || !hasUnsavedChanges}>{busy === "save" && <Loader2 className="size-4 animate-spin" />}Save</Button>{draft.id && draft.is_active && <Button variant="outline" onClick={async () => { if (busy) return; setBusy("deactivate"); try { await updateSionPlanningRule(draft.id!, { is_active: false }); const fresh = await fetchSionPlanningRules(sion); setRules(fresh); setDraft(fresh[0] ?? emptyRule(sion)); setSuccess("Rule deactivated and priorities normalized."); } finally { setBusy(null); } }} disabled={!!busy}>Deactivate</Button>}<Button variant="outline" onClick={testRule} disabled={!!busy || !draft.id || hasUnsavedChanges}>{busy === "test" ? <Loader2 className="size-4 animate-spin" /> : <TestTube2 className="size-4" />}Test Saved Rule</Button><Button onClick={planSion} disabled={!!busy || !rules.length || hasUnsavedChanges}>{busy === "plan" ? <Loader2 className="size-4 animate-spin" /> : <Zap className="size-4" />}Plan Saved SION Rules</Button></div></>}
            {rules.length > 0 && <div><h2 className="text-sm font-semibold">Saved database rules</h2>{rules.map((rule) => <button key={rule.id} onClick={() => { setDraft(rule); setPreview(null); }} className="mr-2 mt-2 rounded border px-3 py-1 text-sm">#{rule.priority} {rule.name}</button>)}</div>}
            {preview && <section aria-label="Rule match preview" className="overflow-x-auto rounded-lg border bg-muted/20 p-3"><h2 className="font-semibold">Matched item and license preview</h2><p className="text-sm">Licenses requested: {preview.licenses_requested ?? preview.results?.length ?? 0} · Matched licenses: {preview.results?.length ?? 0}</p>{preview.conflicts?.length > 0 && <p role="alert" className="text-sm text-destructive">Conflicts: {preview.conflicts.length}</p>}<table className="mt-2 w-full text-xs"><thead><tr className="border-b text-left"><th>License</th><th>Item</th><th>HSN</th><th>Product</th><th>Unit</th><th>Current Price</th><th>Max Price</th><th>Price Status</th><th>Available</th><th>Existing Planned</th><th>Shortage</th><th>Status</th></tr></thead><tbody>{preview.results?.flatMap((result: any) => (result.matched_lines ?? []).map((line: any, index: number) => <tr className="border-b" key={`${result.license_id}-${line.id ?? index}`}><td>{result.license_number ?? result.license_id}</td><td>{line.item_name ?? line.description ?? "—"}</td><td>{line.hsn ?? line.hsn_code ?? "—"}</td><td>{line.product_description ?? line.description ?? "—"}</td><td>{line.unit ?? "—"}</td><td>{line.current_unit_price ?? line.unit_price ?? "—"}</td><td>{line.max_unit_price ?? preview.rule?.max_unit_price ?? "—"}</td><td>{line.price_status ?? "—"}</td><td>{line.available_qty ?? "—"}</td><td>{line.existing_planned_qty ?? line.planned_qty ?? "—"}</td><td>{line.shortage_qty ?? "—"}</td><td>{line.status ?? result.status ?? "—"}</td></tr>))}</tbody></table></section>}
        </section></div>;
}
