import { useEffect, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowUp, Eye, Loader2, Pencil, Plus, TestTube2, Zap } from "lucide-react";
import Select from "react-select";
import { useLocation, useNavigate, useSearchParams } from "react-router-dom";
import api from "@/api/axios";
import PageHeader from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { createSionPlanningRule, fetchSionPlanningRules, planSavedSionRules, previewSavedSionRules, reorderSionPlanningRules, testSionPlanningRule, updateSionPlanningRule, type RuleCondition, type RuleGroup, type SionPlanningRule } from "@/services/api/planningRuleApi";

export function planningPath(licenseId?: string | number | null, origin?: string): string { const p = new URLSearchParams(); if (licenseId) p.set("license_id", String(licenseId)); if (origin) p.set("origin", origin); return `/planning${p.size ? `?${p}` : ""}`; }
const emptyCondition = (): RuleCondition => ({ field: "HSN", comparator: "CONTAINS", value: "" });
const emptyRule = (sion: number): SionPlanningRule => ({ sion, name: "", expression: { operator: "AND", conditions: [emptyCondition()] }, max_unit_price: "", unit: "KG", priority: 0, is_active: true });
const isGroup = (node: RuleCondition | RuleGroup): node is RuleGroup => "conditions" in node;

function GroupEditor({ group, onChange, depth = 0 }: { group: RuleGroup; onChange: (g: RuleGroup) => void; depth?: number }) {
    const replace = (index: number, node: RuleCondition | RuleGroup) => onChange({ ...group, conditions: group.conditions.map((old, i) => i === index ? node : old) });
    return <fieldset className="rounded-lg border p-3"><legend className="px-1 text-xs font-semibold">{depth ? "Nested group" : "Match rules"}</legend>
        <label className="text-xs">Logic <select aria-label={depth ? "Nested group logic" : "Rule logic"} value={group.operator} onChange={(e) => onChange({ ...group, operator: e.target.value as "AND" | "OR" })} className="ml-2 rounded border px-2 py-1"><option value="AND">ALL (AND)</option><option value="OR">ANY (OR)</option></select></label>
        <div className="mt-2 space-y-2">{group.conditions.map((node, index) => isGroup(node)
            ? <GroupEditor key={index} group={node} depth={depth + 1} onChange={(value) => replace(index, value)} />
            : <div key={index} className="grid gap-2 sm:grid-cols-[180px_160px_1fr_auto]"><select aria-label={`Condition ${index + 1} field`} value={node.field} onChange={(e) => replace(index, { ...node, field: e.target.value as RuleCondition["field"] })} className="rounded border px-2"><option value="HSN">HSN</option><option value="PRODUCT_DESCRIPTION">Product Description</option></select><select aria-label={`Condition ${index + 1} comparator`} value={node.comparator} onChange={(e) => replace(index, { ...node, comparator: e.target.value as RuleCondition["comparator"] })} className="rounded border px-2"><option value="CONTAINS">Contains</option><option value="NOT_CONTAINS">Does not contain</option></select><input aria-label={`Condition ${index + 1} value`} value={node.value} onChange={(e) => replace(index, { ...node, value: e.target.value })} className="rounded border px-2" /><Button variant="ghost" onClick={() => onChange({ ...group, conditions: group.conditions.filter((_, i) => i !== index) })}>Remove</Button></div>)}</div>
        <div className="mt-2 flex gap-2"><Button size="sm" variant="outline" onClick={() => onChange({ ...group, conditions: [...group.conditions, emptyCondition()] })}><Plus className="size-3" />Condition</Button><Button size="sm" variant="outline" onClick={() => onChange({ ...group, conditions: [...group.conditions, { operator: "AND", conditions: [emptyCondition()] }] })}><Plus className="size-3" />Group</Button></div>
    </fieldset>;
}

export default function LicensePlanningWorkspace() {
    const [params, setParams] = useSearchParams(); const navigate = useNavigate(); const location = useLocation();
    const origin = params.get("origin") || "/licenses";
    const [sions, setSions] = useState<any[]>([]); const [sion, setSion] = useState<number | null>(null); const [rules, setRules] = useState<SionPlanningRule[]>([]); const [draft, setDraft] = useState<SionPlanningRule | null>(null); const [pendingSion, setPendingSion] = useState<number | null | undefined>(undefined); const [busy, setBusy] = useState<"save" | "test" | "preview" | "plan" | "deactivate" | "reorder" | null>(null); const [preview, setPreview] = useState<any>(null); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [loading, setLoading] = useState(true);
    useEffect(() => { setLoading(true); api.get("masters/sion-classes/", { params: { is_active: true, page_size: 500, ordering: "norm_class" } }).then(({ data }) => { const rows = data?.results ?? data ?? []; setSions(rows); const requested = params.get("sion"); if (requested) { const match = rows.find((row: any) => String(row.id) === requested || String(row.norm_class).toUpperCase() === requested.toUpperCase()); if (match) setSion(match.id); } }).catch(() => setError("Unable to load SION norms.")).finally(() => setLoading(false)); }, []);
    useEffect(() => { if (!sion) { setRules([]); setDraft(null); setPreview(null); return; } setLoading(true); setError(""); setDraft(null); setPreview(null); fetchSionPlanningRules(sion).then((rows) => setRules([...rows].sort((a, b) => a.priority - b.priority))).catch(() => setError("Unable to load planning rules.")).finally(() => setLoading(false)); }, [sion]);
    const savedDraft = draft?.id ? rules.find((rule) => rule.id === draft.id) : null;
    const hasUnsavedChanges = !!draft && (!savedDraft || JSON.stringify(draft) !== JSON.stringify(savedDraft));
    // PLAN/Preview execute saved active database rules only. Keep the UI gate
    // aligned with that backend contract even if an inactive row is returned
    // by an older/cached API response.
    const activeSavedRules = rules.filter((rule) => rule.id != null && rule.is_active);
    const canExecuteSion = activeSavedRules.length > 0 && !hasUnsavedChanges;
    const save = async () => { if (!draft) return null; const { priority: _databasePriority, ...payload } = draft; const saved = draft.id ? await updateSionPlanningRule(draft.id, payload) : await createSionPlanningRule(payload as SionPlanningRule); const fresh = await fetchSionPlanningRules(saved.sion); setRules(fresh); setDraft(fresh.find((rule) => rule.id === saved.id) ?? saved); setSuccess("Rule saved to the database."); return saved; };
    const testRule = async () => { if (busy || !draft?.id || hasUnsavedChanges) return; setBusy("test"); setError(""); setSuccess(""); try { setPreview(await testSionPlanningRule(draft.id)); setSuccess("Saved database rule test completed."); } catch { setError("Rule test failed."); } finally { setBusy(null); } };
    const planSion = async () => { if (busy || !sion || !canExecuteSion) return; setBusy("plan"); setError(""); setSuccess(""); try { await planSavedSionRules(sion); setPreview(await previewSavedSionRules(sion)); setSuccess("Saved active SION rules planned in database priority order."); setRules(await fetchSionPlanningRules(sion)); } catch { setError("Planning failed."); } finally { setBusy(null); } };
    const selectedSion = sions.find((row) => row.id === sion); const sionLabel = selectedSion?.norm_class ?? "SION";
    const selectSion = (next: number | null) => { if (hasUnsavedChanges) { setPendingSion(next); return; } applySion(next); };
    const applySion = (next: number | null) => { setSion(next); setPendingSion(undefined); const nextParams = new URLSearchParams(params); if (next) { const row = sions.find((item) => item.id === next); nextParams.set("sion", row?.norm_class ?? String(next)); } else nextParams.delete("sion"); setParams(nextParams, { replace: true }); };
    const previewSion = async () => { if (!sion || busy || !canExecuteSion) return; setBusy("preview"); setError(""); setSuccess(""); try { setPreview(await previewSavedSionRules(sion)); setSuccess(`${sionLabel} preview completed without planning writes.`); } catch { setError("Plan preview failed."); } finally { setBusy(null); } };
    const reorder = async (index: number, offset: number) => { if (!sion || busy) return; const next = [...rules]; const target = index + offset; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setBusy("reorder"); setError(""); try { const fresh = await reorderSionPlanningRules(sion, next.map((rule) => rule.id!)); setRules([...fresh].sort((a, b) => a.priority - b.priority)); setSuccess("Database rule priority updated."); } catch { setError("Unable to reorder rules."); } finally { setBusy(null); } };
    return <div><PageHeader pretitle="License Planning" title={sion ? `${sionLabel} Planning` : "SION Planning"} description="One reusable workspace, driven entirely by the selected SION's saved database rules." actions={<Button variant="outline" onClick={() => navigate(origin, { state: { fromPlanning: location.pathname + location.search } })}><ArrowLeft className="size-4" />Back</Button>} />
        <section className="space-y-5 rounded-xl border bg-card p-4">{error && <p role="alert" className="rounded bg-destructive/10 p-2 text-sm text-destructive">{error}</p>}{success && <p role="status" className="rounded bg-success/10 p-2 text-sm text-success">{success}</p>}{loading && <p role="status" className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin" />Loading…</p>}<label className="block max-w-xl text-sm font-semibold">SION Norm<Select aria-label="SION Norm" options={sions.map((row) => ({ value: row.id, label: row.norm_class }))} value={sions.filter((row) => row.id === sion).map((row) => ({ value: row.id, label: row.norm_class }))[0] ?? null} onChange={(option) => selectSion(option?.value ?? null)} className="mt-1 font-normal" /></label>
            {!sion && <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">Select a SION norm to load its saved planning rules.</div>}
            {sion && <><div className="grid gap-3 sm:grid-cols-4"><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">SION</p><p className="font-semibold">{sionLabel}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Rules</p><p className="font-semibold">{rules.length}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Active</p><p className="font-semibold">{activeSavedRules.length}</p></div><div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">Authority</p><p className="font-semibold">Saved database rules</p></div></div>
                <div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">{sionLabel} — Planning Rules</h2><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => { setDraft(emptyRule(sion)); setPreview(null); }}><Plus className="size-4" />New Rule</Button><Button variant="outline" onClick={previewSion} disabled={!!busy || !canExecuteSion}>{busy === "preview" ? <Loader2 className="size-4 animate-spin" /> : <Eye className="size-4" />}Preview {sionLabel} Plan</Button><Button onClick={planSion} disabled={!!busy || !canExecuteSion}>{busy === "plan" ? <Loader2 className="size-4 animate-spin" /> : <Zap className="size-4" />}PLAN {sionLabel}</Button></div></div>
                {!loading && rules.length > 0 && activeSavedRules.length === 0 && <p role="status" className="rounded-lg border border-dashed p-3 text-sm text-muted-foreground">Activate and save at least one rule before previewing or planning {sionLabel}.</p>}
                {!loading && !rules.length && !draft && <div className="rounded-lg border border-dashed p-8 text-center"><p className="text-sm text-muted-foreground">{sionLabel} has no planning rules yet.</p><Button className="mt-3" variant="outline" onClick={() => setDraft(emptyRule(sion))}><Plus className="size-4" />New Rule</Button></div>}
                {!!rules.length && <ol className="space-y-2">{rules.map((rule, index) => <li key={rule.id} className="flex items-center gap-3 rounded-lg border p-3"><span className="w-8 font-semibold">#{rule.priority}</span><div className="min-w-0 flex-1"><p className="truncate font-medium">{rule.name}</p><p className="text-xs text-muted-foreground">Max {rule.max_unit_price} {rule.unit} · Version {rule.version ?? "—"} · {rule.is_active ? "Active" : "Inactive"}</p></div><Button size="icon" variant="ghost" aria-label={`Move ${rule.name} up`} disabled={!!busy || index === 0} onClick={() => reorder(index, -1)}><ArrowUp className="size-4" /></Button><Button size="icon" variant="ghost" aria-label={`Move ${rule.name} down`} disabled={!!busy || index === rules.length - 1} onClick={() => reorder(index, 1)}><ArrowDown className="size-4" /></Button><Button size="sm" variant="outline" onClick={() => { setDraft(rule); setPreview(null); }}><Pencil className="size-4" />Edit</Button></li>)}</ol>}
            </>}
            {draft && <section aria-label="Rule editor" className="space-y-3 rounded-lg border bg-muted/10 p-4"><h2 className="font-semibold">{draft.id ? `Edit ${draft.name}` : `New ${sionLabel} Rule`}</h2><div className="flex flex-wrap gap-2"><label className="flex-1 text-xs">Rule name<input aria-label="Rule name" value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} className="mt-1 h-9 w-full rounded border px-2" /></label><label className="text-xs">Max unit price<input aria-label="Maximum unit price" inputMode="decimal" value={draft.max_unit_price} onChange={(e) => /^\d*(\.\d*)?$/.test(e.target.value) && setDraft({ ...draft, max_unit_price: e.target.value })} className="mt-1 block h-9 rounded border px-2" /></label><label className="text-xs">Unit<input aria-label="Planning unit" value={draft.unit} onChange={(e) => setDraft({ ...draft, unit: e.target.value })} className="mt-1 block h-9 rounded border px-2" /></label><label className="flex items-center gap-2 self-end pb-2 text-xs"><input aria-label="Rule active" type="checkbox" checked={draft.is_active} onChange={(e) => setDraft({ ...draft, is_active: e.target.checked })} />Active</label></div><p role="status" className="text-xs font-medium">{hasUnsavedChanges ? "Unsaved changes — save or discard before switching SION, Preview, or Plan." : "Saved in database"}</p>{draft.id && <p className="text-xs text-muted-foreground">Priority #{draft.priority} · Version {draft.version ?? "—"} · Updated {draft.modified_on ? new Date(draft.modified_on).toLocaleString() : "—"}</p>}<GroupEditor group={draft.expression} onChange={(expression) => setDraft({ ...draft, expression })} /><div className="flex flex-wrap gap-2"><Button onClick={async () => { if (busy) return; setBusy("save"); setError(""); try { await save(); } catch { setError("Unable to save rule."); } finally { setBusy(null); } }} disabled={!!busy || !draft.name || !hasUnsavedChanges}>{busy === "save" && <Loader2 className="size-4 animate-spin" />}Save</Button><Button variant="outline" onClick={() => setDraft(null)}>Discard / Close</Button>{draft.id && <Button variant="outline" onClick={testRule} disabled={!!busy || hasUnsavedChanges}>{busy === "test" ? <Loader2 className="size-4 animate-spin" /> : <TestTube2 className="size-4" />}Test Saved Rule</Button>}</div></section>}
            {pendingSion !== undefined && <section role="alertdialog" aria-label="Unsaved changes" className="rounded-lg border border-warning bg-warning/10 p-4"><h2 className="font-semibold">Unsaved changes</h2><p className="mt-1 text-sm">Save or discard the current rule before switching SION norms.</p><div className="mt-3 flex gap-2"><Button onClick={async () => { setBusy("save"); try { const saved = await save(); if (saved) applySion(pendingSion ?? null); } catch { setError("Unable to save rule."); } finally { setBusy(null); } }}>Save and switch</Button><Button variant="outline" onClick={() => applySion(pendingSion ?? null)}>Discard and switch</Button><Button variant="ghost" onClick={() => setPendingSion(undefined)}>Cancel</Button></div></section>}
            {preview && <section aria-label="Rule match preview" className="overflow-x-auto rounded-lg border bg-muted/20 p-3"><h2 className="font-semibold">Matched item and license preview</h2><p className="text-sm">Licenses requested: {preview.licenses_requested ?? preview.results?.length ?? preview.licenses?.length ?? 0} · Rules processed: {preview.rules_processed?.length ?? preview.rules_executed?.length ?? (preview.rule ? 1 : 0)} · Existing plans: {preview.summary?.existing_plans ?? "—"} · Shortages: {preview.summary?.shortages ?? "—"}</p>{preview.conflicts?.length > 0 && <p role="alert" className="text-sm text-destructive">Conflicts: {preview.conflicts.length}</p>}<table className="mt-2 w-full text-xs"><thead><tr className="border-b text-left"><th>License</th><th>Item</th><th>HSN</th><th>Product</th><th>Unit</th><th>Current Price</th><th>Max Price</th><th>Price Status</th><th>Available</th><th>Proposed</th><th>Existing Planned</th><th>Shortage</th><th>Status</th></tr></thead><tbody>{preview.results?.flatMap((result: any) => (result.matched_lines ?? []).map((line: any, index: number) => <tr className="border-b" key={`${result.license_id}-${line.id ?? index}`}><td>{result.license_number ?? result.license_id}</td><td>{line.item_name ?? line.description ?? "—"}</td><td>{line.hsn ?? line.hsn_code ?? "—"}</td><td>{line.product_description ?? line.description ?? "—"}</td><td>{line.unit ?? "—"}</td><td>{line.current_unit_price ?? line.unit_price ?? "—"}</td><td>{line.max_unit_price ?? preview.rule?.max_unit_price ?? "—"}</td><td>{line.price_status ?? "—"}</td><td>{line.available_qty ?? "—"}</td><td>{line.proposed_planned_qty ?? "—"}</td><td>{line.existing_planned_qty ?? "—"}</td><td>{line.shortage_qty ?? "—"}</td><td>{line.status ?? result.status ?? "—"}</td></tr>))}</tbody></table></section>}
        </section></div>;
}
