# Generated by Django 6.0.4 on 2026-08-24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("accounts", "0004_remove_user_company")]

    operations = [
        migrations.CreateModel(
            name="RevokedAccessToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("jti", models.CharField(db_index=True, max_length=255, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"indexes": [models.Index(fields=["expires_at"], name="accounts_re_expires_5b8ff5_idx")]},
        ),
    ]
