export type LedgerTaskRef = { task_id: string; license: string };
export type LedgerFileTask = { file: string; total: number; tasks: LedgerTaskRef[] };
export type LedgerUploadError = { file: string; error: string };
const MAX_ERROR_DETAILS = 10;
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null;
const normalizeText = (value: unknown, fallback: string): string => String(value ?? "").trim() || fallback;
export function normalizeLedgerFileTasks(value: unknown): LedgerFileTask[] { if (!Array.isArray(value)) return []; return value.flatMap((fileEntry, fileIndex) => { if (!isRecord(fileEntry) || !Array.isArray(fileEntry.tasks)) return []; const seen = new Set<string>(); const tasks = fileEntry.tasks.flatMap((entry) => { if (!isRecord(entry)) return []; const id = String(entry.task_id ?? "").trim(); if (!id || seen.has(id)) return []; seen.add(id); return [{ task_id: id, license: normalizeText(entry.license, "Unknown license") }]; }); return tasks.length ? [{ file: normalizeText(fileEntry.file, `File ${fileIndex + 1}`), total: tasks.length, tasks }] : []; }); }
export function normalizeLedgerUploadErrors(value: unknown): LedgerUploadError[] { return !Array.isArray(value) ? [] : value.flatMap((entry, index) => isRecord(entry) ? [{ file: normalizeText(entry.file, `File ${index + 1}`), error: normalizeText(entry.error, "Unknown upload error") }] : []); }
export function buildAsyncUploadErrorMessage(errors: LedgerUploadError[]): string { const shown = errors.slice(0, MAX_ERROR_DETAILS).map((error) => `${error.file}: ${error.error}`).join("; "); const remaining = errors.length > MAX_ERROR_DETAILS ? `; ${errors.length - MAX_ERROR_DETAILS} more not shown` : ""; return `${errors.length} file(s) failed: ${shown}${remaining}`; }
export function getLedgerUploadErrorMessage(error: unknown): string { if (isRecord(error) && isRecord(error.response) && isRecord(error.response.data)) { const detail = error.response.data.error ?? error.response.data.detail ?? error.response.data.message; if (detail) return normalizeText(detail, "Upload failed. Please try again."); } return error instanceof Error ? normalizeText(error.message, "Upload failed. Please try again.") : "Upload failed. Please try again."; }
export function normalizeProgressValue(value: unknown): number { const progress = Number(value); return Number.isFinite(progress) ? Math.min(100, Math.max(0, Math.round(progress))) : 0; }
