import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { RefreshCw } from "lucide-react";
import PageHeader from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { getDownloadRequests, retryDownloadRequest, safeCount } from "@/services/licenseDownloadRequests";
import { toast } from "sonner";
const label=(s:string)=>s.replace(/_/g, " ").replace(/\b\w/g,c=>c.toUpperCase());
export default function LicenseDownloadRequests() {
 const {data, isLoading, refetch}=useQuery({queryKey:["license-download-requests"],queryFn:()=>getDownloadRequests()}); const rows=data?.results??[];
 const summary=[['All Requests',rows.length],['In Progress',rows.filter(x=>safeCount(x.processing_count)>0).length],['Ready',rows.filter(x=>x.zip_ready).length],['Needs Attention',rows.filter(x=>safeCount(x.blocked_count)+safeCount(x.failed_count)>0).length]];
 const retry=async(id:string)=>{try{await retryDownloadRequest(id);toast.success("Request queued for retry.");await refetch()}catch{toast.error("Unable to retry this request.")}};
 return <><PageHeader pretitle="License ledger" title="License Download Requests" description="Persistent, server-verified license files." actions={<div className="flex gap-2"><Button asChild><Link to="/license-ledger">New Download Request</Link></Button><Button variant="outline" onClick={()=>void refetch()}><RefreshCw className="mr-1 size-4"/>Refresh</Button></div>}/><div className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{summary.map(([name,count])=><Card key={String(name)}><CardContent className="p-4"><p className="text-sm text-muted-foreground">{name}</p><p className="text-2xl font-semibold">{count}</p></CardContent></Card>)}</div><Card><CardContent className="p-0">{isLoading?<p className="p-5">Loading requests…</p>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-muted/50 text-left"><tr>{['Request','Created','User','Licences','Progress','Status','Files','Actions'].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=>{const canRetry=r.status==='dispatch_failed'||safeCount(r.failed_count)+safeCount(r.blocked_count)>0;return <tr className="border-t" key={r.id}><td className="p-3 font-mono">{r.request_key}</td><td className="p-3">{new Date(r.created_at).toLocaleString()}</td><td className="p-3">{r.created_by}</td><td className="p-3">{safeCount(r.requested_count)}</td><td className="p-3">{safeCount(r.server_ready_count)} / {safeCount(r.requested_count)}</td><td className="p-3"><span className="rounded-full bg-muted px-2 py-1 text-xs">{label(r.status)}</span></td><td className="p-3">{safeCount(r.server_ready_count)} ready</td><td className="flex gap-2 p-3"><Button asChild size="sm" variant="outline"><Link to={`/license-ledger/download-requests/${r.id}`}>View</Link></Button>{canRetry&&<Button size="sm" onClick={()=>void retry(r.id)}>Retry</Button>}</td></tr>})}{!rows.length&&<tr><td className="p-5 text-muted-foreground" colSpan={8}>No download requests yet.</td></tr>}</tbody></table></div>}</CardContent></Card></>;
}
