# Generated by Django 6.0.4 on 2026-07-03 06:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('iec', models.CharField(max_length=10, unique=True)),
                ('pan', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number.', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line_1', models.TextField(blank=True, default='')),
                ('address_line_2', models.TextField(blank=True, default='')),
                ('logo', models.CharField(blank=True, default='', max_length=512)),
                ('signature', models.CharField(blank=True, default='', max_length=512)),
                ('stamp', models.CharField(blank=True, default='', max_length=512)),
                ('bill_colour', models.CharField(default='#333', max_length=20)),
                ('bank_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code.', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('account_type', models.CharField(blank=True, choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('OD', 'Overdraft')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('date', models.DateField(unique=True)),
                ('usd', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('euro', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('pound_sterling', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('chinese_yuan', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HeadSIONNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('hs_code', models.CharField(max_length=8, unique=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('basic_duty', models.CharField(blank=True, max_length=225, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('policy', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('hs_code',),
            },
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('label', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(db_index=True, max_length=100)),
                ('natural_key', models.CharField(db_index=True, max_length=255)),
                ('op', models.CharField(choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete')], max_length=10)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['at'],
                'indexes': [models.Index(fields=['model_label', 'at'], name='masters_mas_model_l_6d86de_idx')],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('code', 'name'),
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_description', models.TextField()),
                ('hs_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_descriptions', to='masters.hscode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SIONNormClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('norm_class', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('head_norm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sion_head', to='masters.headsionnorm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SIONImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('hsn_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sion_imports', to='masters.hscode')),
                ('norm_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_norm', to='masters.sionnormclass')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='SIONExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('norm_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_norm', to='masters.sionnormclass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('restriction_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('display_order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.itemgroup')),
                ('sion_norm_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='masters.sionnormclass')),
            ],
            options={
                'ordering': ['display_order', 'group__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_restricted', models.BooleanField(default=False)),
                ('restriction_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('dict_key', models.CharField(blank=True, max_length=255, null=True)),
                ('restriction_norm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricted_heads', to='masters.sionnormclass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SIONNormCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('condition_text', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('sion_norm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='masters.sionnormclass')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SIONNormNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('note_text', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('sion_norm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='masters.sionnormclass')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
