# Generated by Django 5.0.3 on 2025-12-18 04:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_celerytasktracker'),
        ('trade', '0005_alter_licensetrade_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Account code (e.g., 1000, 2000)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Account name (e.g., Cash, Accounts Receivable)', max_length=255)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('linked_company', models.ForeignKey(blank=True, help_text='Link to company for party ledgers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_accounts', to='core.companymodel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='trade.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='Account name/label', max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opening balance', max_digits=20)),
                ('opening_balance_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('ledger_account', models.ForeignKey(help_text='Link to bank account in chart of accounts', on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='trade.chartofaccounts')),
            ],
            options={
                'ordering': ['bank_name', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('entry_type', models.CharField(choices=[('GENERAL', 'General Entry'), ('SALES', 'Sales Entry'), ('PURCHASE', 'Purchase Entry'), ('PAYMENT', 'Payment Entry'), ('RECEIPT', 'Receipt Entry'), ('JOURNAL', 'Journal Entry')], default='GENERAL', max_length=20)),
                ('narration', models.TextField(help_text='Description of the transaction')),
                ('reference_number', models.CharField(blank=True, help_text='External reference (invoice, receipt no.)', max_length=100)),
                ('is_posted', models.BooleanField(default=False, help_text='Posted entries cannot be modified')),
                ('is_auto_generated', models.BooleanField(default=False, help_text='Auto-generated from trades/payments')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL)),
                ('linked_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='trade.licensetradepayment')),
                ('linked_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='trade.licensetrade')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-entry_date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit amount (0 if credit entry)', max_digits=20)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount (0 if debit entry)', max_digits=20)),
                ('description', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lines', to='trade.chartofaccounts')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='trade.journalentry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
