# Generated by Django 5.0.3 on 2025-12-18 05:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_chartofaccounts_bankaccount_journalentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(help_text='Agent code/ID', max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('pan', models.CharField(blank=True, help_text='PAN number', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('default_purchase_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default commission % for purchases', max_digits=5)),
                ('default_sale_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default commission % for sales', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Agent',
                'verbose_name_plural': 'Commission Agents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission rate in %', max_digits=5)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Amount on which commission is calculated', max_digits=20)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Calculated commission amount', max_digits=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('payment_note', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_created', to=settings.AUTH_USER_MODEL)),
                ('payment_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payments', to='trade.journalentry')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='trade.licensetrade')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='trade.commissionagent')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-trade__invoice_date', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='CommissionSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('BOTH', 'Both')], default='BOTH', max_length=10)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum transaction amount for this slab', max_digits=20)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum transaction amount (null = no upper limit)', max_digits=20, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission rate % for this slab', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_slabs', to='trade.commissionagent')),
            ],
            options={
                'verbose_name': 'Commission Slab',
                'verbose_name_plural': 'Commission Slabs',
                'ordering': ['agent', 'direction', 'min_amount'],
            },
        ),
        migrations.AddConstraint(
            model_name='commissionslab',
            constraint=models.CheckConstraint(check=models.Q(('max_amount__isnull', True), ('max_amount__gt', models.F('min_amount')), _connector='OR'), name='chk_min_less_than_max'),
        ),
    ]
