# Generated by Django 5.0.3 on 2026-01-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_incentivetradeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionslab',
            name='direction',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('COMMISSION_PURCHASE', 'Commission Purchase'), ('COMMISSION_SALE', 'Commission Sale'), ('BOTH', 'Both')], default='BOTH', max_length=20),
        ),
        migrations.AlterField(
            model_name='licensetrade',
            name='direction',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('COMMISSION_PURCHASE', 'Commission Purchase'), ('COMMISSION_SALE', 'Commission Sale')], db_index=True, max_length=20),
        ),
    ]
