# Generated by Django 5.0.3 on 2026-03-18 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0006_remove_billofentrymodel_boe_company_date_desc_idx_and_more'),
        ('core', '0032_remove_companymodel_company_iec_name_idx_and_more'),
        ('license', '0025_remove_licensedetailsmodel_license_active_balance_idx_and_more'),
        ('trade', '0012_remove_commission_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='licensetrade',
            name='uniq_purchase_supplier_invoice',
        ),
        migrations.RemoveConstraint(
            model_name='licensetrade',
            name='uniq_sale_buyer_invoice_nonblank',
        ),
        migrations.AddConstraint(
            model_name='licensetrade',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'PURCHASE'), models.Q(('invoice_number', ''), _negated=True)), fields=('from_company', 'invoice_number', 'direction'), name='uniq_purchase_supplier_invoice'),
        ),
        migrations.AddConstraint(
            model_name='licensetrade',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'SALE'), models.Q(('invoice_number', ''), _negated=True)), fields=('to_company', 'invoice_number', 'direction'), name='uniq_sale_buyer_invoice_nonblank'),
        ),
    ]
