# Generated by Django 6.0.4 on 2026-04-30 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_remove_licensetrade_uniq_purchase_supplier_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetrade',
            name='linked_trade',
            field=models.ForeignKey(blank=True, help_text='Links this trade to its paired counterpart (Sale↔Purchase)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_trades', to='trade.licensetrade'),
        ),
    ]
