# Generated by Django 5.0.3 on 2026-03-18 18:00

from django.db import migrations


def remove_old_constraints(apps, schema_editor):
    """Remove old unique constraints that don't include direction field"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE trade_licensetrade
            DROP CONSTRAINT IF EXISTS trade_licensetrade_from_company_id_invoice_number_353e6302_uniq;
        """)
        cursor.execute("""
            ALTER TABLE trade_licensetrade
            DROP CONSTRAINT IF EXISTS trade_licensetrade_to_company_id_invoice_number_7226fe9e_uniq;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_remove_licensetrade_uniq_purchase_supplier_invoice_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_old_constraints, migrations.RunPython.noop),
    ]
