# Generated by Django 6.0.4 on 2026-05-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_add_trade_composite_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='licensetrade',
            new_name='trade_licen_invoice_21c4f7_idx',
            old_name='trade_invoice_date_idx',
        ),
        migrations.RenameIndex(
            model_name='licensetrade',
            new_name='trade_licen_directi_ca4cd8_idx',
            old_name='trade_dir_date_idx',
        ),
        migrations.RenameIndex(
            model_name='licensetrade',
            new_name='trade_licen_directi_c3e4ce_idx',
            old_name='trade_dir_from_co_idx',
        ),
        migrations.RenameIndex(
            model_name='licensetrade',
            new_name='trade_licen_directi_2b7c25_idx',
            old_name='trade_dir_to_co_idx',
        ),
    ]
