# Generated by Django 6.0.4 on 2026-07-27 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill_of_entry', '0003_alter_billofentrymodel_unique_together'),
        ('license', '0014_backfill_licenseitemplan_baseline_used'),
        ('trade', '0003_licensetrade_boe_to_boes_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LINK', 'Link'), ('MERGE_BOE', 'Merge BOE'), ('IGNORE', 'Ignore'), ('MARK_PENDING', 'Mark Pending'), ('RECALCULATE', 'Recalculate')], db_index=True, max_length=20)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bill_of_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_logs', to='bill_of_entry.billofentrymodel')),
                ('license_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_logs', to='license.licenseimportitemsmodel')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_logs', to='trade.licensetrade')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['action', 'created_on'], name='reconciliat_action_6c196b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IGNORED', 'Ignored'), ('PENDING', 'Pending')], db_index=True, default='PENDING', max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('bill_of_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_notes', to='bill_of_entry.billofentrymodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('license_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_notes', to='license.licenseimportitemsmodel')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_notes', to='trade.licensetrade')),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['status'], name='reconciliat_status_8ae75e_idx')],
            },
        ),
    ]
