# Generated by Django 6.0.4 on 2026-07-27 15:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0003_allotmentitems_indexes'),
        ('bill_of_entry', '0003_alter_billofentrymodel_unique_together'),
        ('reconciliation', '0001_initial'),
        ('trade', '0003_licensetrade_boe_to_boes_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationlog',
            name='action',
            field=models.CharField(choices=[('LINK', 'Link'), ('MERGE_BOE', 'Merge BOE'), ('IGNORE', 'Ignore'), ('MARK_PENDING', 'Mark Pending'), ('RECALCULATE', 'Recalculate'), ('ALLOCATE', 'Allocate'), ('EDIT_ALLOCATION', 'Edit Allocation'), ('REVERSE_ALLOCATION', 'Reverse Allocation')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='BOEAllotmentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('allocated_qty', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('allocated_cif_fc', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('allocated_cif_inr', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVERSED', 'Reversed')], db_index=True, default='ACTIVE', max_length=10)),
                ('is_current', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('allotment_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boe_allocations', to='allotment.allotmentitems')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('row_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allotment_allocations', to='bill_of_entry.rowdetails')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='reconciliation.boeallotmentallocation')),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['status'], name='reconciliat_status_f5b131_idx'), models.Index(fields=['is_current'], name='reconciliat_is_curr_0dc47b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('allocated_qty__gte', 0), ('allocated_cif_fc__gte', 0), ('allocated_cif_inr__gte', 0)), name='boeallotmentallocation_non_negative_amounts')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceBOEAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('allocated_qty', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('allocated_cif_fc', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('allocated_cif_inr', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVERSED', 'Reversed')], db_index=True, default='ACTIVE', max_length=10)),
                ('is_current', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('row_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_allocations', to='bill_of_entry.rowdetails')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='reconciliation.invoiceboeallocation')),
                ('trade_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boe_allocations', to='trade.licensetradeline')),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['status'], name='reconciliat_status_73c918_idx'), models.Index(fields=['is_current'], name='reconciliat_is_curr_c794d5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('allocated_qty__gte', 0), ('allocated_cif_fc__gte', 0), ('allocated_cif_inr__gte', 0)), name='invoiceboeallocation_non_negative_amounts')],
            },
        ),
    ]
