# Generated by Django 6.0.4 on 2026-07-27 17:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0003_alter_billofentrymodel_unique_together'),
        ('reconciliation', '0002_allocation_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationlog',
            name='action',
            field=models.CharField(choices=[('LINK', 'Link'), ('MERGE_BOE', 'Merge BOE'), ('IGNORE', 'Ignore'), ('MARK_PENDING', 'Mark Pending'), ('RECALCULATE', 'Recalculate'), ('ALLOCATE', 'Allocate'), ('EDIT_ALLOCATION', 'Edit Allocation'), ('REVERSE_ALLOCATION', 'Reverse Allocation'), ('MARK_EXTERNAL_INVOICE', 'Mark External Invoice'), ('REVERSE_EXTERNAL_INVOICE', 'Reverse External Invoice')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='ExternalInvoiceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cif_fc', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cif_inr', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVERSED', 'Reversed')], db_index=True, default='ACTIVE', max_length=10)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('row_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_invoice_links', to='bill_of_entry.rowdetails')),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['status'], name='reconciliat_status_59ed69_idx'), models.Index(fields=['is_current'], name='reconciliat_is_curr_d800a9_idx'), models.Index(fields=['invoice_number'], name='reconciliat_invoice_bef8ba_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gte', 0), ('cif_fc__gte', 0), ('cif_inr__gte', 0)), name='externalinvoicelink_non_negative_amounts')],
            },
        ),
    ]
