# Generated by Django 6.0.4 on 2026-07-28 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0014_backfill_licenseitemplan_baseline_used'),
        ('reconciliation', '0003_alter_reconciliationlog_action_externalinvoicelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationlog',
            name='action',
            field=models.CharField(choices=[('LINK', 'Link'), ('MERGE_BOE', 'Merge BOE'), ('IGNORE', 'Ignore'), ('MARK_PENDING', 'Mark Pending'), ('RECALCULATE', 'Recalculate'), ('ALLOCATE', 'Allocate'), ('EDIT_ALLOCATION', 'Edit Allocation'), ('REVERSE_ALLOCATION', 'Reverse Allocation'), ('MARK_EXTERNAL_INVOICE', 'Mark External Invoice'), ('REVERSE_EXTERNAL_INVOICE', 'Reverse External Invoice'), ('WARNING_IGNORED', 'Warning Ignored'), ('WARNING_RESTORED', 'Warning Restored')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='IgnoredWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(db_index=True, max_length=64)),
                ('entity_type', models.CharField(db_index=True, max_length=32)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('ignored', models.BooleanField(db_index=True, default=True)),
                ('ignored_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('ignored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_warnings', to='license.licensedetailsmodel')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['license', 'ignored'], name='reconciliat_license_9f7c12_idx')],
                'constraints': [models.UniqueConstraint(fields=('license', 'warning_type', 'entity_type', 'entity_id'), name='uniq_ignored_warning_identity')],
            },
        ),
    ]
