# Generated by Django 6.0.4 on 2026-07-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0004_alter_reconciliationlog_action_ignoredwarning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationlog',
            name='action',
            field=models.CharField(choices=[('LINK', 'Link'), ('MERGE_BOE', 'Merge BOE'), ('IGNORE', 'Ignore'), ('MARK_PENDING', 'Mark Pending'), ('RECALCULATE', 'Recalculate'), ('ALLOCATE', 'Allocate'), ('EDIT_ALLOCATION', 'Edit Allocation'), ('REVERSE_ALLOCATION', 'Reverse Allocation'), ('MARK_EXTERNAL_INVOICE', 'Mark External Invoice'), ('REVERSE_EXTERNAL_INVOICE', 'Reverse External Invoice'), ('WARNING_IGNORED', 'Warning Ignored'), ('WARNING_RESTORED', 'Warning Restored'), ('HIDE_BOE', 'Hide BOE (Previous Owner)'), ('RESTORE_BOE', 'Restore BOE')], db_index=True, max_length=30),
        ),
    ]
