; Supervisor config for license-manager-v1 Celery worker.
;
; Install:
;   sudo cp /home/django/license-manager/backend/deploy/celery.conf \
;            /etc/supervisor/conf.d/license-manager-v1-celery.conf
;   sudo supervisorctl reread && sudo supervisorctl update
;
; The Celery app name is "config" (backend/config/celery.py).
; Legacy Celery is named "license-manager-celery" — these are distinct processes.

[program:license-manager-v1-celery]
command=/home/django/license-manager/venv/bin/celery -A config worker -l info --concurrency=4
directory=/home/django/license-manager/backend
user=django
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/license-manager-v1/celery-error.log
stdout_logfile=/var/log/license-manager-v1/celery-out.log
environment=DJANGO_SETTINGS_MODULE="config.settings.prod"
