# Generated by Django 5.2.7 on 2025-11-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invoiceentity_notificationnumber_purchasestatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceentity',
            name='gst_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='invoiceentity',
            name='pan_number',
            field=models.CharField(max_length=10),
        ),
    ]
