# Generated by Django 5.0.3 on 2025-11-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_invoiceentity_gst_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sionimportmodel',
            options={'ordering': ['serial_number']},
        ),
        migrations.RenameField(
            model_name='sionimportmodel',
            old_name='sr_no',
            new_name='serial_number',
        ),
    ]
