# Generated by Django 5.0.3 on 2025-11-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fix_product_description_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HSCodeDutyModel',
        ),
    ]
