# Generated by Django 5.0.3 on 2025-11-17 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_itemnamemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemheadmodel',
            name='restriction_norm',
            field=models.ForeignKey(blank=True, help_text='Norm class for restriction (e.g., E132)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricted_heads', to='core.sionnormclassmodel'),
        ),
    ]
