# Generated by Django 5.0.3 on 2025-11-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_fix_null_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceentity',
            name='address_line_2',
            field=models.TextField(blank=True),
        ),
    ]
