# Generated by Django 5.0.3 on 2025-11-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_invoiceentity_address_line_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sionnormclassmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
