# Generated by Django 5.0.3 on 2025-11-27 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_replace_restriction_group_with_sion_norm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemheadmodel',
            options={'verbose_name': 'Item Head (Deprecated)', 'verbose_name_plural': 'Item Heads (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='itemnamemodel',
            options={'ordering': ['group__name', 'name']},
        ),
        migrations.RemoveField(
            model_name='itemnamemodel',
            name='head',
        ),
        migrations.RemoveField(
            model_name='itemnamemodel',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='ItemGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='itemnamemodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.itemgroupmodel'),
        ),
    ]
