# Generated by Django 5.0.3 on 2025-11-29 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_itemheadmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemnamemodel',
            options={'ordering': ['display_order', 'group__name', 'name']},
        ),
        migrations.AddField(
            model_name='itemnamemodel',
            name='display_order',
            field=models.IntegerField(default=1, help_text='Display order in reports (lower numbers appear first). Must be unique per norm class.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='itemnamemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
