# Generated by Django 5.0.3 on 2026-01-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_celerytasktracker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferlettermodel',
            options={'ordering': ['name', 'id']},
        ),
    ]
