# Generated by Django 6.0.4 on 2026-05-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_activitylog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_user_id_81b1f1_idx',
            old_name='core_actlog_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_action_549521_idx',
            old_name='core_actlog_action_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_module_a92616_idx',
            old_name='core_actlog_module_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_usernam_a16faf_idx',
            old_name='core_actlog_uname_ts_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
