# Generated by Django 6.0.4 on 2026-05-27 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_companymodel_address'),
        ('license', '0003_remove_licensedetailsmodel_license_lic_notific_5b1519_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='archived_exporter_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='exporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.companymodel'),
        ),
    ]
