# Generated by Django 5.2.7 on 2025-11-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_alter_licenseexportitemmodel_fob_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='notification_number',
            field=models.CharField(choices=[('019/2015', '019/2015'), ('098/2009', '098/2009'), ('025/2023', '025/2023')], default='019/2015', max_length=10),
        ),
    ]
