# Generated by Django 5.0.3 on 2025-11-16 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_alter_licensedetailsmodel_notification_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='hsn_code',
            new_name='hs_code',
        ),
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='duty_type',
        ),
    ]
