# Generated by Django 6.0.4 on 2026-07-01 10:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_materialized_views'),
        ('license', '0009_licenseitemplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseitemplan',
            name='item_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_lines', to='core.itemnamemodel'),
        ),
        migrations.AddField(
            model_name='licenseitemplan',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='licenseitemplan',
            name='import_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilization_plans', to='license.licenseimportitemsmodel'),
        ),
        migrations.AddIndex(
            model_name='licenseitemplan',
            index=models.Index(fields=['import_item'], name='license_lic_import__259dda_idx'),
        ),
    ]
