# Generated by Django 5.0.3 on 2025-12-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0010_alter_licensedetailsmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedocumentmodel',
            name='type',
            field=models.CharField(choices=[('LICENSE COPY', 'LICENSE COPY'), ('TRANSFER LETTER', 'TRANSFER LETTER'), ('OTHER', 'OTHER')], max_length=255),
        ),
    ]
