# Generated by Django 6.0.4 on 2026-07-16 05:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_entry', '0003_alter_billofentrymodel_unique_together'),
        ('core', '0011_split_milk_into_swp_dwp_wpc'),
        ('license', '0011_harden_invoice_validation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_qty__gte', Decimal('0.000')), ('total_cif_fc__gte', Decimal('0.00')), ('total_cif_inr__gte', Decimal('0.00')), ('total_fob_inr__gte', Decimal('0.00')), ('total_amount__gte', Decimal('0.00'))), name='license_invoice_non_negative_totals'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('qty__gte', Decimal('0.000')), ('qty__isnull', True), _connector='OR'), models.Q(('cif_fc__gte', Decimal('0.00')), ('cif_fc__isnull', True), _connector='OR'), models.Q(('cif_inr__gte', Decimal('0.00')), ('cif_inr__isnull', True), _connector='OR'), models.Q(('fob_inr__gte', Decimal('0.00')), ('fob_inr__isnull', True), _connector='OR'), ('rate__gte', Decimal('0.00')), ('amount__gte', Decimal('0.00'))), name='license_invoiceitem_non_negative_values'),
        ),
    ]
