# Generated by Django 6.0.4 on 2026-07-23 09:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0012_enforce_invoice_non_negative_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseitemplan',
            name='baseline_used_cif_fc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='licenseitemplan',
            name='baseline_used_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
    ]
