# Generated by Django 5.0.3 on 2025-12-22 14:16

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_celerytasktracker'),
        ('license', '0013_incentivelicense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incentivelicense',
            name='balance_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining balance in INR (auto-calculated)', max_digits=15),
        ),
        migrations.AddField(
            model_name='incentivelicense',
            name='sold_status',
            field=models.CharField(choices=[('NO', 'Not Sold'), ('PARTIAL', 'Partially Sold'), ('YES', 'Fully Sold')], db_index=True, default='NO', help_text='Sold status (auto-calculated)', max_length=10),
        ),
        migrations.AddField(
            model_name='incentivelicense',
            name='sold_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total sold value in INR (auto-calculated)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='incentivelicense',
            index=models.Index(fields=['sold_status'], name='license_inc_sold_st_6466d5_idx'),
        ),
    ]
