# Generated by Django 5.0.3 on 2026-01-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_transferlettermodel_options'),
        ('license', '0014_add_sold_status_fields_to_incentive_license'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='licenseimportitemsmodel',
            index=models.Index(fields=['available_quantity'], name='license_lic_availab_1f176a_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseimportitemsmodel',
            index=models.Index(fields=['available_value'], name='license_lic_availab_42a15c_idx'),
        ),
    ]
