# Generated by Django 6.0.4 on 2026-08-04 11:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0014_backfill_licenseitemplan_baseline_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseitemplan',
            name='remaining_cif_fc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='licenseitemplan',
            name='remaining_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
    ]
