# Generated by Django 6.0.4 on 2026-08-07 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_split_milk_into_swp_dwp_wpc'),
        ('license', '0016_backfill_licenseitemplan_remaining_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.portmodel'),
        ),
    ]
