# Generated by Django 6.0.4 on 2026-08-17 06:51

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_master_sync_fields'),
        ('license', '0019_sion_rule_priority_and_provenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SionPlanningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stable_key', models.CharField(max_length=100, unique=True)),
                ('strategy_type', models.CharField(default='ACTION_PIPELINE', max_length=50)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('sion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_profiles', to='core.sionnormclassmodel')),
            ],
            options={
                'ordering': ('sion_id', '-is_active', '-version'),
            },
        ),
        migrations.CreateModel(
            name='SionPlanningOutputMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stable_key', models.CharField(max_length=100)),
                ('conversion_factor', models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(choices=[('kg', 'Kgs'), ('pcs', 'Pcs'), ('nos', 'Nos'), ('mts', 'Mts')], max_length=10)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('output_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sion_planning_output_mappings', to='core.itemnamemodel')),
                ('source_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_mappings', to='license.sionplanningrule')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_mappings', to='license.sionplanningprofile')),
            ],
            options={
                'ordering': ('profile_id', 'priority', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SionPlanningAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stable_key', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('MATCH', 'Match'), ('PRICE', 'Price'), ('GROUP', 'Group'), ('ALLOCATE', 'Allocate'), ('SPLIT', 'Split'), ('REBALANCE', 'Rebalance'), ('ROUND', 'Round'), ('MAP_OUTPUT', 'Map output')], max_length=20)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('config', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='license.sionplanningprofile')),
            ],
            options={
                'ordering': ('profile_id', 'priority', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SionPlanningRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('run_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profile_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SHADOW', 'Shadow')], db_index=True, default='PENDING', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('config_snapshot', models.JSONField(default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='license.sionplanningprofile')),
                ('sion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_runs', to='core.sionnormclassmodel')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.AddConstraint(
            model_name='sionplanningprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('sion',), name='uniq_active_sion_planning_profile'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningprofile',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='sion_profile_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningoutputmapping',
            constraint=models.UniqueConstraint(fields=('profile', 'stable_key'), name='uniq_profile_output_mapping_key'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningoutputmapping',
            constraint=models.CheckConstraint(condition=models.Q(('conversion_factor__gte', 0)), name='sion_mapping_factor_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningoutputmapping',
            constraint=models.CheckConstraint(condition=models.Q(('rate__isnull', True), ('rate__gte', 0), _connector='OR'), name='sion_mapping_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningoutputmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('profile', 'priority'), name='uniq_active_profile_mapping_priority'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningoutputmapping',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1)), name='sion_mapping_priority_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningoutputmapping',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='sion_mapping_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningaction',
            constraint=models.UniqueConstraint(fields=('profile', 'stable_key'), name='uniq_profile_action_key'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningaction',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('profile', 'priority'), name='uniq_active_profile_action_priority'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningaction',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 1)), name='sion_action_priority_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningaction',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='sion_action_version_gte_1'),
        ),
        migrations.AddIndex(
            model_name='sionplanningrun',
            index=models.Index(fields=['sion', 'status', 'created_on'], name='license_sio_sion_id_e34ac7_idx'),
        ),
    ]
