# Generated by Django 5.0.3 on 2026-02-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0024_add_composite_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='licensedetailsmodel',
            name='license_active_balance_idx',
        ),
        migrations.RemoveIndex(
            model_name='licensedetailsmodel',
            name='license_active_expiry_idx',
        ),
        migrations.RemoveIndex(
            model_name='licensedetailsmodel',
            name='license_status_expiry_idx',
        ),
        migrations.RemoveIndex(
            model_name='licensedetailsmodel',
            name='license_status_active_bal_idx',
        ),
        migrations.RemoveIndex(
            model_name='licensedetailsmodel',
            name='license_exporter_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='licensedetailsmodel',
            name='license_port_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='licensedetailsmodel',
            name='license_null_expired_idx',
        ),
        migrations.RemoveIndex(
            model_name='licenseexportitemmodel',
            name='export_item_norm_idx',
        ),
        migrations.RemoveIndex(
            model_name='licenseexportitemmodel',
            name='export_item_license_idx',
        ),
        migrations.RemoveIndex(
            model_name='licenseimportitemsmodel',
            name='import_item_license_restr_idx',
        ),
        migrations.RemoveIndex(
            model_name='licenseimportitemsmodel',
            name='import_item_serial_idx',
        ),
        migrations.RemoveIndex(
            model_name='licenseimportitemsmodel',
            name='import_item_hscode_idx',
        ),
        migrations.RemoveIndex(
            model_name='licensetransfermodel',
            name='transfer_license_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='licensetransfermodel',
            name='transfer_to_company_idx',
        ),
        migrations.RemoveIndex(
            model_name='licensetransfermodel',
            name='transfer_from_company_idx',
        ),
    ]
