# Generated by Django 6.0.4 on 2026-08-17 18:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0026_sionplanningrule_output_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='sionplanningrule',
            name='percentage_constraint',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage cap for this input under the parent SION norm (e.g., 50.00 for E126 PKO)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
