# Generated by Django 6.0.4 on 2026-04-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0027_add_indexes_notification_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseexportitemmodel',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kgs'), ('pcs', 'Pcs'), ('nos', 'Nos'), ('mts', 'Mts')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kgs'), ('pcs', 'Pcs'), ('nos', 'Nos'), ('mts', 'Mts')], default='kg', max_length=10),
        ),
    ]
