# Generated by Django 6.0.4 on 2026-08-18 07:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_master_sync_fields'),
        ('license', '0030_populate_rule_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SionPlanningPercentageRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('rule_id', 'priority', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SionPlanningUnitValueRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('min_unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('preferred_unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('priority', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('rule_id', 'priority', 'pk'),
            },
        ),
        migrations.RenameIndex(
            model_name='sioninputaliasconfig',
            new_name='license_sio_sion_id_4c078b_idx',
            old_name='sion_alias_sion_output_idx',
        ),
        migrations.RenameIndex(
            model_name='sioninputaliasconfig',
            new_name='license_sio_sion_id_9c0fe4_idx',
            old_name='sion_alias_norm_idx',
        ),
        migrations.RenameIndex(
            model_name='sioninputaliasconfig',
            new_name='license_sio_alias_n_0d4dac_idx',
            old_name='sion_alias_active_idx',
        ),
        migrations.AddField(
            model_name='sionplanningrule',
            name='strategy',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('SPLIT_BY_UNIT_VALUE', 'Split by Unit Value'), ('SPLIT_BY_PERCENT', 'Split by %')], db_index=True, help_text='Planning strategy for this rule (null = legacy dispatch path)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sioninputaliasconfig',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sioninputaliasconfig',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sioninputaliasconfig',
            name='source_description',
            field=models.TextField(blank=True, help_text="Source or reason for this mapping (e.g., 'From E126 specification')"),
        ),
        migrations.AlterField(
            model_name='sionplanningrule',
            name='rule_type',
            field=models.CharField(choices=[('PERCENTAGE_CAP', 'Master percentage cap'), ('SPLIT_BY_PERCENTAGE', 'Split by percentage'), ('QUANTITY_CAP', 'Quantity cap')], default='PERCENTAGE_CAP', help_text='Type of rule: master percentage cap or transaction split strategy', max_length=50),
        ),
        migrations.AddField(
            model_name='sionplanningpercentagerow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sionplanningpercentagerow',
            name='import_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.itemnamemodel'),
        ),
        migrations.AddField(
            model_name='sionplanningpercentagerow',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sionplanningpercentagerow',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percentage_rows', to='license.sionplanningrule'),
        ),
        migrations.AddField(
            model_name='sionplanningunitvaluerow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sionplanningunitvaluerow',
            name='import_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.itemnamemodel'),
        ),
        migrations.AddField(
            model_name='sionplanningunitvaluerow',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sionplanningunitvaluerow',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_value_rows', to='license.sionplanningrule'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningpercentagerow',
            constraint=models.UniqueConstraint(fields=('rule', 'import_item'), name='uniq_percentage_row_per_item'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningunitvaluerow',
            constraint=models.UniqueConstraint(fields=('rule', 'import_item'), name='uniq_unit_value_row_per_item'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningunitvaluerow',
            constraint=models.CheckConstraint(condition=models.Q(('max_unit_price__gte', models.F('min_unit_price'))), name='unit_value_max_gte_min'),
        ),
        migrations.AddConstraint(
            model_name='sionplanningunitvaluerow',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_unit_price__gte', models.F('min_unit_price')), ('preferred_unit_price__lte', models.F('max_unit_price'))), name='unit_value_preferred_in_range'),
        ),
    ]
