# Generated by Django 6.0.4 on 2026-08-18 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_master_sync_fields'),
        ('license', '0031_add_strategy_field_and_row_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sionplanningrule',
            name='output_item',
        ),
        migrations.AddField(
            model_name='sionplanningrule',
            name='import_item',
            field=models.ForeignKey(blank=True, help_text='Import item this rule plans (STANDARD strategy)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sion_planning_rules', to='core.itemnamemodel'),
        ),
    ]
