# Generated by Django 6.0.4 on 2026-05-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0031_backfill_transfer_user_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='condition_type',
            field=models.CharField(blank=True, default='', help_text="Per-item licence condition extracted from the condition sheet: 'AU', '2%', '3%', '5%', '10%' etc. Drives the colour badge in the UI. Empty means no special condition.", max_length=8),
        ),
    ]
