# Generated by Django 6.0.4 on 2026-08-18 14:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_master_sync_fields'),
        ('license', '0034_sionplanningpercentagerow_max_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sionplanningunitvaluerow',
            name='unit_value_preferred_in_range',
        ),
        migrations.AddConstraint(
            model_name='sionplanningunitvaluerow',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_unit_price__gte', Decimal('0.00'))), name='unit_value_preferred_non_negative'),
        ),
    ]
