# Generated by Django 6.0.4 on 2026-09-18 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0054_persistent_license_download_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='licenseledgerrecoveryaudit',
            new_name='license_lic_trade_i_795ec5_idx',
            old_name='license_led_trade_i_0b20a4_idx',
        ),
        migrations.AlterField(
            model_name='licenseledgerpackagejob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('validating_sources', 'Validating Sources'), ('merging', 'Merging'), ('server_ready', 'Server Ready'), ('failed', 'Failed'), ('partial_failed', 'Partial Failed'), ('dispatch_failed', 'Dispatch Failed')], db_index=True, default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='licenseledgerrecoveryaudit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='licensepackageartifact',
            name='kind',
            field=models.CharField(choices=[('01-custom-ledger', '01-custom-ledger'), ('02-financial-ledger', '02-financial-ledger'), ('03-main-purchase-invoices', '03-main-purchase-invoices'), ('04-final-party-sales-invoices', '04-final-party-sales-invoices'), ('FINAL_MERGED_PDF', 'FINAL_MERGED_PDF'), ('FINAL_ZIP', 'FINAL_ZIP')], max_length=48),
        ),
        migrations.AddIndex(
            model_name='licensepackageartifact',
            index=models.Index(fields=['request', 'item', 'kind'], name='license_lic_request_4a8cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='licensepackageauditevent',
            index=models.Index(fields=['request', 'created_at'], name='license_lic_request_0f6f85_idx'),
        ),
    ]
