# Generated by Django 3.1.6 on 2022-05-25 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import license.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlongWithModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LicenseDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_created=True, blank=True, null=True)),
                ('scheme_code', models.CharField(choices=[('26', '26 - Duty Free Import Authorization')], default='26', max_length=10)),
                ('notification_number', models.CharField(choices=[('019/2015', '019/2015'), ('098/2009', '098/2009')], default='019/2015', max_length=10)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('file_number', models.CharField(blank=True, max_length=30, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('user_restrictions', models.TextField(blank=True, null=True)),
                ('ledger_date', models.DateField(blank=True, null=True)),
                ('is_audit', models.BooleanField(default=False)),
                ('is_not_registered', models.BooleanField(default=False)),
                ('is_null', models.BooleanField(default=False)),
                ('is_self', models.BooleanField(default=True)),
                ('is_au', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('balance_cif', models.FloatField(default=0.0)),
                ('export_item', models.CharField(blank=True, max_length=255, null=True)),
                ('is_incomplete', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_individual', models.BooleanField(default=False)),
                ('ge_file_number', models.IntegerField(default=0)),
                ('fob', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_on', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dfia_created', to=settings.AUTH_USER_MODEL)),
                ('exporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.companymodel')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dfia_updated', to=settings.AUTH_USER_MODEL)),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.portmodel')),
            ],
            options={
                'ordering': ('license_expiry_date',),
            },
        ),
        migrations.CreateModel(
            name='OfficeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseInwardOutwardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('amd_sheets_number', models.CharField(blank=True, max_length=100, null=True)),
                ('copy', models.BooleanField(default=False)),
                ('annexure', models.BooleanField(default=False)),
                ('tl', models.BooleanField(default=False)),
                ('aro', models.BooleanField(default=False)),
                ('along_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.alongwithmodel')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.datemodel')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.licensedetailsmodel')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.officemodel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.statusmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseImportItemsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(default=0)),
                ('duty_type', models.CharField(default='Basic', max_length=255)),
                ('quantity', models.FloatField(default=0)),
                ('old_quantity', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kg')], default='kg', max_length=10)),
                ('cif_fc', models.FloatField(blank=True, null=True)),
                ('cif_inr', models.FloatField(default=0)),
                ('restricted_value_in_percentage', models.FloatField(default=0)),
                ('restricted_value_per_unit', models.FloatField(default=0)),
                ('blocked_value', models.FloatField(default=0.0)),
                ('blocked_quantity', models.FloatField(default=0.0)),
                ('available_quantity', models.FloatField(default=0.0)),
                ('available_value', models.FloatField(default=0.0)),
                ('is_restrict', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('hs_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_item', to='core.hscodemodel')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_items', to='core.itemnamemodel')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_license', to='license.licensedetailsmodel')),
            ],
            options={
                'ordering': ['license__license_expiry_date', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='LicenseExportItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_type', models.CharField(default='Basic', max_length=255)),
                ('net_quantity', models.FloatField(default=0)),
                ('old_quantity', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kg')], default='kg', max_length=10)),
                ('fob_fc', models.FloatField(default=0)),
                ('fob_inr', models.FloatField(default=0)),
                ('fob_exchange_rate', models.FloatField(default=0)),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('euro', 'euro')], default='usd', max_length=5)),
                ('value_addition', models.FloatField(default=15)),
                ('cif_fc', models.FloatField(default=0)),
                ('cif_inr', models.FloatField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_licenses', to='core.itemnamemodel')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_license', to='license.licensedetailsmodel')),
                ('norm_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_item', to='core.sionnormclassmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseDocumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=license.models.license_path)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_documents', to='license.licensedetailsmodel')),
            ],
        ),
    ]
