# Generated by Django 2.2.3 on 2019-07-17 17:49

from django.db import migrations, models
import django.db.models.deletion
import license.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.CharField(default='DFIA', max_length=5)),
                ('notification_number', models.CharField(default='N2015', max_length=5)),
                ('license_number', models.CharField(max_length=10, unique=True)),
                ('license_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file_number', models.CharField(blank=True, max_length=30, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('user_restrictions', models.TextField(blank=True, null=True)),
                ('license', models.FileField(blank=True, null=True, upload_to=license.models.license_path)),
                ('transfer_letter', models.FileField(blank=True, null=True, upload_to=license.models.transfer_letter_path)),
                ('exporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CompanyModel')),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PortModel')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseImportItemsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(default=0)),
                ('duty_type', models.CharField(default='Basic', max_length=255)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kg')], default='kg', max_length=10)),
                ('cif_fc', models.FloatField(default=0)),
                ('cif_inr', models.FloatField(default=0)),
                ('restricted_value_in_percentage', models.FloatField(default=0)),
                ('restricted_value_per_unit', models.FloatField(default=0)),
                ('blocked_value', models.FloatField(default=0.0)),
                ('blocked_quantity', models.FloatField(default=0.0)),
                ('alloted_value', models.FloatField(default=0.0)),
                ('alloted_quantity', models.FloatField(default=0.0)),
                ('available_quantity', models.FloatField(default=0.0)),
                ('available_value', models.FloatField(default=0.0)),
                ('hs_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_item', to='core.HSCodeModel')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_items', to='core.ItemNameModel')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_list', to='license.LicenseDetailsModel')),
            ],
            options={
                'ordering': ['serial_number', 'license__license_expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='LicenseExportItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_type', models.CharField(default='Basic', max_length=255)),
                ('net_quantity', models.FloatField(default=0)),
                ('unit', models.CharField(choices=[('kg', 'kg')], default='kg', max_length=10)),
                ('fob_fc', models.FloatField(default=0)),
                ('fob_inr', models.FloatField(default=0)),
                ('fob_exchange_rate', models.FloatField(default=0)),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('euro', 'euro')], default='usd', max_length=5)),
                ('value_addition', models.FloatField(default=15)),
                ('cif_fc', models.FloatField(default=0)),
                ('cif_inr', models.FloatField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_licenses', to='core.ItemNameModel')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_license', to='license.LicenseDetailsModel')),
                ('norm_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_item', to='core.SionNormClassModel')),
            ],
        ),
    ]
