# Generated by Django 2.2.3 on 2020-06-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='is_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
