# Generated by Django 2.2.3 on 2019-07-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licensedetailsmodel',
            old_name='expiry_date',
            new_name='license_expiry_date',
        ),
    ]
