# Generated by Django 2.2.3 on 2019-07-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_null',
            field=models.BooleanField(default=False),
        ),
    ]
