# Generated by Django 3.1.6 on 2022-09-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='is_cheese',
            field=models.BooleanField(default=True),
        ),
    ]
