# Generated by Django 3.1.6 on 2022-09-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_licenseimportitemsmodel_is_cheese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='is_cheese',
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_cheese',
            field=models.BooleanField(default=True),
        ),
    ]
