# Generated by Django 2.2.3 on 2019-07-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_auto_20190718_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_audit',
            field=models.BooleanField(default=False),
        ),
    ]
