# Generated by Django 2.2.3 on 2019-07-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_licensedetailsmodel_is_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='ledger_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
