# Generated by Django 2.2.3 on 2020-06-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_licenseimportitemsmodel_is_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='is_allowed',
        ),
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='is_restrict',
            field=models.BooleanField(default=False),
        ),
    ]
