# Generated by Django 2.2.3 on 2019-07-18 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_licensedetailsmodel_is_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_license', to='license.LicenseDetailsModel'),
        ),
    ]
