# Generated by Django 2.2.3 on 2019-07-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_licensedetailsmodel_ledger_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='notification_number',
            field=models.CharField(default='019/2015', max_length=5),
        ),
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='scheme_code',
            field=models.CharField(default='26', max_length=5),
        ),
    ]
