# Generated by Django 3.1.6 on 2022-09-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_auto_20220920_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_wpc',
            field=models.BooleanField(default=True),
        ),
    ]
