# Generated by Django 2.2.3 on 2020-07-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_auto_20200608_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlongWithModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseInwardOutwardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('amd_sheets_number', models.CharField(blank=True, max_length=100, null=True)),
                ('copy', models.BooleanField(default=False)),
                ('annexure', models.BooleanField(default=False)),
                ('along_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.AlongWithModel')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.DateModel')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.LicenseDetailsModel')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.OfficeModel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_status', to='license.StatusModel')),
            ],
        ),
    ]
