# Generated by Django 2.2.3 on 2019-07-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_auto_20190721_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='license_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='notification_number',
            field=models.CharField(default='019/2015', max_length=10),
        ),
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='scheme_code',
            field=models.CharField(default='26', max_length=10),
        ),
    ]
