# Generated by Django 2.2.3 on 2019-07-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_auto_20190718_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='cif_fc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
