# Generated by Django 2.2.3 on 2020-07-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_alongwithmodel_datemodel_licenseinwardoutwardmodel_officemodel_statusmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseinwardoutwardmodel',
            name='ge_file_number',
            field=models.IntegerField(default=0),
        ),
    ]
