# Generated by Django 3.1.6 on 2022-09-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_licensedetailsmodel_is_wpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_gluten',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_yeast',
            field=models.BooleanField(default=True),
        ),
    ]
