# Generated by Django 2.2.3 on 2019-07-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_auto_20190721_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='license_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
