# Generated by Django 2.2.3 on 2019-07-19 02:47

from django.db import migrations, models
import license.models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_auto_20190718_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='annexure',
            field=models.FileField(blank=True, null=True, upload_to=license.models.annexure_path),
        ),
    ]
