# Generated by Django 2.2.3 on 2020-07-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_licenseinwardoutwardmodel_ge_file_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseinwardoutwardmodel',
            name='ge_file_number',
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='ge_file_number',
            field=models.IntegerField(default=0),
        ),
    ]
