# Generated by Django 3.1.6 on 2022-10-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_auto_20220920_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='palmolein',
            field=models.BooleanField(default=True),
        ),
    ]
