# Generated by Django 2.2.3 on 2020-07-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_auto_20200711_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseinwardoutwardmodel',
            name='aro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licenseinwardoutwardmodel',
            name='tl',
            field=models.BooleanField(default=False),
        ),
    ]
