# Generated by Django 3.1.6 on 2022-10-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_licensedetailsmodel_palmolein'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licensedetailsmodel',
            old_name='palmolein',
            new_name='is_palmolein',
        ),
    ]
