# Generated by Django 2.2.3 on 2019-07-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_auto_20190721_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='notification_number',
            field=models.CharField(choices=[('019/2015', '019/2015'), ('098/2009', '098/2009')], default='019/2015', max_length=10),
        ),
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='scheme_code',
            field=models.CharField(choices=[('26', '26 - Duty Free Import Authorization')], default='26', max_length=10),
        ),
    ]
