# Generated by Django 2.2.10 on 2020-11-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0007_auto_20200712_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='export_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
