# Generated by Django 2.2.3 on 2019-07-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0007_auto_20190722_0457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenseimportitemsmodel',
            options={'ordering': ['serial_number']},
        ),
    ]
