# Generated by Django 3.1.6 on 2022-10-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0007_auto_20221003_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='is_cheese',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='is_gluten',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='is_palmolein',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='is_wpc',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='is_yeast',
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='cheese_unit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='gluten_unit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='juice_unit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='palmolein_unit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='wpc_unit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='yeast_unit',
            field=models.FloatField(default=0),
        ),
    ]
