# Generated by Django 3.1.6 on 2022-10-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0008_auto_20221003_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_item',
            field=models.CharField(default='gluten,palmolein,yeast,juice,milk,Packing Material', max_length=255),
        ),
    ]
