# Generated by Django 2.2.3 on 2019-08-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0008_auto_20190728_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='self',
            field=models.BooleanField(default=True),
        ),
    ]
