# Generated by Django 3.1.6 on 2021-11-07 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('license', '0008_licensedetailsmodel_export_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dfia_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='created_on',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dfia_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='modified_on',
            field=models.DateField(auto_now=True),
        ),
    ]
