# Generated by Django 2.2.3 on 2019-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_companymodel_failed'),
        ('license', '0008_auto_20190728_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='hs_code',
        ),
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='hs_code',
            field=models.ManyToManyField(blank=True, null=True, related_name='import_item', to='core.HSCodeModel'),
        ),
    ]
