# Generated by Django 2.2.3 on 2019-08-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0009_licensedetailsmodel_self'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licensedetailsmodel',
            old_name='self',
            new_name='is_self',
        ),
    ]
