# Generated by Django 3.1.6 on 2021-11-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0009_auto_20211107_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='fob',
            field=models.IntegerField(default=0),
        ),
    ]
