# Generated by Django 4.1.7 on 2023-05-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0009_licensedetailsmodel_is_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='notification_number',
            field=models.CharField(choices=[('019/2015', '019/2015'), ('098/2009', '098/2009'), ('025/2023', '025/2023')], default='025/2023', max_length=10),
        ),
    ]
