# Generated by Django 3.1.6 on 2021-11-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0010_licensedetailsmodel_fob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='fob',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
