# Generated by Django 4.1.7 on 2023-06-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0010_alter_licensedetailsmodel_notification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='billing_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='billing_rate',
            field=models.FloatField(default=0),
        ),
    ]
