# Generated by Django 2.2.3 on 2019-10-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0010_auto_20190812_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='alloted_quantity',
        ),
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='alloted_value',
        ),
    ]
