# Generated by Django 3.1.6 on 2021-12-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0011_auto_20211124_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_not_registered',
            field=models.BooleanField(default=False),
        ),
    ]
