# Generated by Django 2.2.3 on 2019-12-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0011_auto_20191011_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseexportitemmodel',
            name='old_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='old_quantity',
            field=models.FloatField(default=0),
        ),
    ]
