# Generated by Django 4.1.7 on 2024-02-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0011_licensedetailsmodel_billing_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licensedetailsmodel',
            old_name='is_self',
            new_name='is_ge',
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_mi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_oth',
            field=models.BooleanField(default=False),
        ),
    ]
