# Generated by Django 3.1.6 on 2022-01-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0012_licensedetailsmodel_is_not_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='created_on',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
