# Generated by Django 2.2.3 on 2020-01-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0012_auto_20191229_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='balance_cif',
            field=models.FloatField(default=0.0),
        ),
    ]
