# Generated by Django 4.1.7 on 2024-02-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0012_rename_is_self_licensedetailsmodel_is_ge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='is_ge',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='is_mi',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='is_oth',
        ),
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='purchase_status',
            field=models.CharField(choices=[('GE', 'GE Purchase'), ('NP', 'GE Operating'), ('IP', 'GE Item Purchase')], default='GE', max_length=2),
        ),
    ]
