# Generated by Django 4.2.14 on 2024-08-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0013_remove_licensedetailsmodel_is_ge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
