# Generated by Django 2.2.3 on 2020-02-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0013_licensedetailsmodel_balance_cif'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_au',
            field=models.BooleanField(default=False),
        ),
    ]
