# Generated by Django 3.1.6 on 2022-01-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0013_auto_20220103_0705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensedetailsmodel',
            options={'ordering': ('license_expiry_date',)},
        ),
        migrations.AlterModelOptions(
            name='licenseimportitemsmodel',
            options={'ordering': ['license__license_expiry_date', 'serial_number']},
        ),
    ]
