# Generated by Django 4.2.15 on 2024-08-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0013_remove_licensedetailsmodel_is_ge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='blocked_quantity',
        ),
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='blocked_value',
        ),
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='restricted_value_in_percentage',
        ),
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='restricted_value_per_unit',
        ),
        migrations.AddField(
            model_name='licenseexportitemmodel',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='allotted_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='allotted_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='debited_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='debited_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='available_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='available_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='cif_fc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='cif_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='duty_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='old_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
