# Generated by Django 4.2.14 on 2024-08-08 20:11

from django.db import migrations

from django.db import migrations

from core.scripts.calculate_balance import calculate_debited_quantity, calculate_allotted_quantity, \
    calculate_debited_value, calculate_allotted_value, calculate_available_quantity


def backwards(apps, schema_editor):
    pass


def calculate_fields(apps, schema_editor):
    LicenseImportItemsModel = apps.get_model('license',
                                             'LicenseImportItemsModel')  # Replace with real app and model name
    for instance in LicenseImportItemsModel.objects.all():
        instance.debited_quantity = calculate_debited_quantity(instance)  # Replace with real calculation logic
        instance.allotted_quantity = calculate_allotted_quantity(instance)  # Replace with real calculation logic
        instance.debited_value = calculate_debited_value(instance)  # Replace with real calculation logic
        instance.allotted_value = calculate_allotted_value(instance)  # Replace with real calculation logic
        instance.available_quantity = calculate_available_quantity(instance)  # Replace with real calculation logic
        if instance.item is not None:
            instance.description = instance.item.name
        else:
            instance.description = ""
        instance.save()
    LicenseExportItemModel = apps.get_model('license', 'LicenseExportItemModel')
    for instance in LicenseExportItemModel.objects.all():
        if instance.item is not None:
            instance.description = instance.item.name
        else:
            instance.description = ""
        instance.save()


def remove_item(apps, schema_editor):
    LicenseImportItemsModel = apps.get_model('license',
                                             'LicenseImportItemsModel')  # Replace with real app and model name
    LicenseImportItemsModel.objects.all().update(item=None)
    LicenseExportItemModel = apps.get_model('license', 'LicenseExportItemModel')
    LicenseExportItemModel.objects.all().update(item=None)


class Migration(migrations.Migration):
    dependencies = [
        ('license', '0014_remove_licenseimportitemsmodel_blocked_quantity_and_more'),
    ]

    operations = [
        migrations.RunPython(calculate_fields, backwards),
        migrations.RunPython(remove_item, backwards),
    ]
