# Generated by Django 2.2.3 on 2020-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0014_licensedetailsmodel_is_au'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
