# Generated by Django 4.2.14 on 2024-08-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0015_auto_20240808_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
