# Generated by Django 4.2.14 on 2024-08-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0015_auto_20240809_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='allotted_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='allotted_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='available_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='available_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='cif_fc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='cif_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='debited_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='debited_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='duty_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='old_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
