# Generated by Django 4.2.14 on 2024-08-08 20:11

from django.db import migrations

from django.db import migrations

from core.scripts.calculate_balance import calculate_debited_quantity, calculate_allotted_quantity, \
    calculate_debited_value, calculate_allotted_value, calculate_available_quantity


def backwards(apps, schema_editor):
    LicenseImportItemsModel = apps.get_model('license', 'LicenseImportItemsModel')
    LicenseImportItemsModel.objects.all().update(item=None)


def delete_item(apps, schema_editor):
    LicenseExportItemModel = apps.get_model('license', 'LicenseExportItemModel')
    LicenseExportItemModel.objects.all().update(item=None)
    LicenseImportItemsModel = apps.get_model('license', 'LicenseImportItemsModel')
    LicenseImportItemsModel.objects.all().update(item=None)
    SionNormClassModel = apps.get_model('core', 'SionNormClassModel')
    SionNormClassModel.objects.all().update(item=None)
    SIONExportModel = apps.get_model('core', 'SIONExportModel')
    SIONExportModel.objects.all().update(item=None)
    SIONImportModel = apps.get_model('core', 'SIONImportModel')
    SIONImportModel.objects.all().update(item=None)


def createITEM(apps, schema_editor):
    from setup.migrations_script import null_all_export_items
    null_all_export_items()
    from setup.migrations_script import delete_all_items
    delete_all_items()
    from setup.migrations_script import createItem
    createItem()
    from setup.migrations_script import set_items
    set_items()


class Migration(migrations.Migration):
    dependencies = [
        ('license', '0015_auto_20240813_0131'),
    ]

    operations = [
        migrations.RunPython(createITEM, backwards),
    ]
