# Generated by Django 2.2.3 on 2020-03-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0015_licenseimportitemsmodel_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
