# Generated by Django 4.2.14 on 2024-08-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0016_alter_licenseimportitemsmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='blocked_quantity',
        ),
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='blocked_value',
        ),
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='restricted_value_in_percentage',
        ),
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='restricted_value_per_unit',
        ),
    ]
