# Generated by Django 4.2.15 on 2024-08-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0016_auto_20240813_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='cheese_unit',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='gluten_unit',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='is_item',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='juice_unit',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='palmolein_unit',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='wpc_unit',
        ),
        migrations.RemoveField(
            model_name='licensedetailsmodel',
            name='yeast_unit',
        ),
    ]
