# Generated by Django 4.2.14 on 2024-08-08 20:11

from django.db import migrations

from django.db import migrations

from core.scripts.calculate_balance import calculate_debited_quantity, calculate_allotted_quantity, \
    calculate_debited_value, calculate_allotted_value, calculate_available_quantity


def backwards(apps, schema_editor):
    pass


def createITEM(apps, schema_editor):
    ItemNameModel = apps.get_model('core',
                                   'ItemNameModel')  # Replace with real app and model name
    ItemHeadModel = apps.get_model('core',
                                   'ItemHeadModel')  # Replace with real app and model name
    head,bool = ItemHeadModel.objects.get_or_create(name='WHEAT GLUTEN')
    ItemNameModel.objects.get_or_create(name='WHEAT GLUTEN', head=head)
    head,bool = ItemHeadModel.objects.get_or_create(name='SUGAR')
    ItemNameModel.objects.get_or_create(name='SUGAR', head=head)
    head,bool = ItemHeadModel.objects.get_or_create(name='VEGETABLE OIL')
    ItemNameModel.objects.get_or_create(name='RBD PALMOLEIN OIL', head=head)
    ItemNameModel.objects.get_or_create(name='EDIBLE VEGETABLE OIL', head=head)
    ItemNameModel.objects.get_or_create(name='PALM KERNEL OIL', head=head)
    head,bool = ItemHeadModel.objects.get_or_create(name='BISCUIT 10% Restriction')
    ItemNameModel.objects.get_or_create(name='FOOD FLAVOUR BISCUITS', head=head)
    ItemNameModel.objects.get_or_create(name='JUICE', head=head)
    ItemNameModel.objects.get_or_create(name='DIETARY FIBRE', head=head)
    ItemNameModel.objects.get_or_create(name='FRUIT/COCOA', head=head)
    ItemNameModel.objects.get_or_create(name='LEAVENING AGENT', head=head)
    ItemNameModel.objects.get_or_create(name='STARCH 1108', head=head)
    ItemNameModel.objects.get_or_create(name='STARCH 3505', head=head)
    head,bool = ItemHeadModel.objects.get_or_create(name='MILK & MILK Product')
    ItemNameModel.objects.get_or_create(name='CHEESE', head=head)
    ItemNameModel.objects.get_or_create(name='WPC', head=head)
    ItemNameModel.objects.get_or_create(name='SWP', head=head)
    head,bool = ItemHeadModel.objects.get_or_create(name='PACKING MATERIAL')
    item,bool = ItemNameModel.objects.get_or_create(name='PP')
    item.head = head
    item.save()
    ItemNameModel.objects.get_or_create(name='PAPER & PAPER', head=head)
    ItemNameModel.objects.get_or_create(name='ALUMINIUM FOIL', head=head)
    head,bool = ItemHeadModel.objects.get_or_create(name='JUICE')
    ItemNameModel.objects.get_or_create(name='FRUIT JUICE', head=head)
    ItemNameModel.objects.get_or_create(name='TARTARIC ACID')
    head,bool = ItemHeadModel.objects.get_or_create(name='CONFECTIONERY 5% Restriction')
    ItemNameModel.objects.get_or_create(name='FOOD FLAVOUR CONFECTIONERY', head=head)
    ItemNameModel.objects.get_or_create(name='ESSENTIAL OIL', head=head)
    head,bool = ItemHeadModel.objects.get_or_create(name='CONFECTIONERY 3% Restriction')
    ItemNameModel.objects.get_or_create(name='EMULSIFIER', head=head)
    head,bool = ItemHeadModel.objects.get_or_create(name='CONFECTIONERY 2% Restriction')
    ItemNameModel.objects.get_or_create(name='OTHER CONFECTIONERY INGREDIENTS', head=head)
    ItemNameModel.objects.get_or_create(name='CEREALS FLAKES')
    head,bool = ItemHeadModel.objects.get_or_create(name='NAMKEEN 5% Restriction')
    ItemNameModel.objects.get_or_create(name='RELEVANT ADDITIVES DESCRIPTION', head=head)
    head,bool = ItemHeadModel.objects.get_or_create(name='NAMKEEN 3% Restriction')
    ItemNameModel.objects.get_or_create(name='FOOD FLAVOUR NAMKEEN', head=head)
    head,bool = ItemHeadModel.objects.get_or_create(name='PICKLE 3% Restriction')
    ItemNameModel.objects.get_or_create(name='FOOD FLAVOUR PICKLE', head=head)
    head,bool = ItemHeadModel.objects.get_or_create(name='GLASS FORMERS')
    ItemNameModel.objects.get_or_create(name='RUTILE', head=head)
    ItemNameModel.objects.get_or_create(name='BORAX', head=head)
    ItemNameModel.objects.get_or_create(name='INTERMEDIATES NAMELY')
    ItemNameModel.objects.get_or_create(name='SODA ASH')
    ItemNameModel.objects.get_or_create(name='TITANIUM DIOXIDE')


class Migration(migrations.Migration):
    dependencies = [
        ('license', '0016_alter_licenseimportitemsmodel_allotted_quantity_and_more'),
    ]

    operations = [
        migrations.RunPython(createITEM, backwards),
    ]
