# Generated by Django 4.2.14 on 2024-08-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0016_alter_licenseimportitemsmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='blocked_quantity',
        ),
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='blocked_value',
        ),
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='restricted_value_in_percentage',
        ),
        migrations.RemoveField(
            model_name='licenseimportitemsmodel',
            name='restricted_value_per_unit',
        ),
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='allotted_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='allotted_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='debited_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='licenseimportitemsmodel',
            name='debited_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='available_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='available_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
