# Generated by Django 2.2.3 on 2020-04-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0016_licensedetailsmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_incomplete',
            field=models.BooleanField(default=False),
        ),
    ]
