# Generated by Django 4.2.15 on 2024-08-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0017_remove_licensedetailsmodel_cheese_unit_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='licenseimportitemsmodel',
            unique_together={('license', 'serial_number')},
        ),
    ]
