# Generated by Django 4.2.14 on 2024-08-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0017_auto_20240809_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseexportitemmodel',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
