# Generated by Django 2.2.3 on 2020-04-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0017_licensedetailsmodel_is_incomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
