# Generated by Django 2.2.3 on 2020-04-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0018_licensedetailsmodel_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
    ]
