# Generated by Django 4.2.15 on 2024-08-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0018_alter_licenseimportitemsmodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='purchase_status',
            field=models.CharField(choices=[('GE', 'GE Purchase'), ('NP', 'GE Operating'), ('IP', 'GE Item Purchase'), ('SM', 'SM Purchase'), ('OT', 'OT Purchase')], default='GE', max_length=2),
        ),
    ]
