# Generated by Django 4.2.18 on 2025-02-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0019_alter_licensedetailsmodel_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='condition_sheet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
