# Generated by Django 2.2.3 on 2020-04-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0019_licensedetailsmodel_is_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
