# Generated by Django 4.2.20 on 2025-03-18 07:24

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('license', '0020_licensedetailsmodel_condition_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='license',
            field=models.ForeignKey(
                related_name='import_license',
                db_index=True,
                to='license.LicenseDetailsModel',
                on_delete=models.CASCADE
            ),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='hs_code',
            field=models.ForeignKey(
                related_name='import_item',
                db_index=True,
                blank=True,
                null=True,
                to='core.HSCodeModel',
                on_delete=models.CASCADE
            ),
        ),
        migrations.AlterField(
            model_name='licenseimportitemsmodel',
            name='item',
            field=models.ForeignKey(
                related_name='license_items',
                db_index=True,
                blank=True,
                null=True,
                to='core.ItemNameModel',
                on_delete=models.CASCADE
            ),
        ),
    ]
