# Generated by Django 4.2.20 on 2025-03-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0021_auto_20250318_0724'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='licenseimportitemsmodel',
            index=models.Index(fields=['license'], name='license_lic_license_d4d897_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseimportitemsmodel',
            index=models.Index(fields=['hs_code'], name='license_lic_hs_code_063682_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseimportitemsmodel',
            index=models.Index(fields=['item'], name='license_lic_item_id_c3fee2_idx'),
        ),
    ]
