# Generated by Django 4.2.20 on 2025-04-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_itemnamemodel_unit_price'),
        ('license', '0022_licenseimportitemsmodel_license_lic_license_d4d897_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_data', to='core.companymodel'),
        ),
    ]
