# Generated by Django 4.2.20 on 2025-04-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0023_licensedetailsmodel_current_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='is_mnm',
            field=models.BooleanField(default=False),
        ),
    ]
