# Generated by Django 4.2.20 on 2025-04-07 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0024_licensedetailsmodel_is_mnm'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseTransferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('from_iec', models.CharField(max_length=15)),
                ('to_iec', models.CharField(max_length=15)),
                ('transfer_status', models.CharField(max_length=50)),
                ('transfer_initiation_date', models.DateTimeField()),
                ('transfer_acceptance_date', models.DateTimeField(blank=True, null=True)),
                ('cbic_status', models.CharField(blank=True, max_length=100, null=True)),
                ('cbic_response_date', models.DateTimeField(blank=True, null=True)),
                ('user_id_transfer_initiation', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id_acceptance', models.CharField(blank=True, max_length=100, null=True)),
                ('from_iec_entity_name', models.CharField(max_length=255)),
                ('to_iec_entity_name', models.CharField(max_length=255)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='license.licensedetailsmodel')),
            ],
        ),
    ]
