# Generated by Django 4.2.20 on 2025-04-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0025_licensetransfermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetransfermodel',
            name='transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licensetransfermodel',
            name='transfer_initiation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
