# Generated by Django 4.2.20 on 2025-04-10 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_itemnamemodel_unit_price'),
        ('license', '0026_alter_licensetransfermodel_transfer_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensetransfermodel',
            name='from_iec',
        ),
        migrations.RemoveField(
            model_name='licensetransfermodel',
            name='from_iec_entity_name',
        ),
        migrations.RemoveField(
            model_name='licensetransfermodel',
            name='to_iec',
        ),
        migrations.RemoveField(
            model_name='licensetransfermodel',
            name='to_iec_entity_name',
        ),
        migrations.AddField(
            model_name='licensetransfermodel',
            name='from_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='core.companymodel'),
        ),
        migrations.AddField(
            model_name='licensetransfermodel',
            name='to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='core.companymodel'),
        ),
    ]
