# Generated by Django 4.2.20 on 2025-04-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0027_remove_licensetransfermodel_from_iec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedetailsmodel',
            name='file_transfer_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
