# Generated by Django 4.2.20 on 2025-04-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0029_alter_licensedetailsmodel_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='purchase_status',
            field=models.CharField(choices=[('GE', 'GE Purchase'), ('NP', 'GE Operating'), ('IP', 'GE Item Purchase'), ('SM', 'SM Purchase'), ('OT', 'OT Purchase'), ('RA', 'Ravi Foods')], default='GE', max_length=2),
        ),
    ]
