# Generated by Django 4.2.21 on 2025-07-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0031_alter_licensedetailsmodel_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensedetailsmodel',
            name='purchase_status',
            field=models.CharField(choices=[('GE', 'GE Purchase'), ('NP', 'GE Operating'), ('IP', 'GE Item Purchase'), ('SM', 'SM Purchase'), ('OT', 'OT Purchase'), ('CO', 'Conversion'), ('RA', 'Ravi Foods'), ('LM', 'LM Purchase')], default='GE', max_length=2),
        ),
    ]
