[program:license-manager-celery]
command=/home/django/license-manager/venv/bin/celery -A lmanagement worker --beat -Q celery,ledger -l info --concurrency=4 --max-tasks-per-child=100
directory=/home/django/license-manager/backend
user=django
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/django/license-manager/logs/celery.log
stderr_logfile=/home/django/license-manager/logs/celery_err.log
stopwaitsecs=600
stopasgroup=true
killasgroup=true
